// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jobquery

import (
	"database/sql"
)

type JobExecution struct {
	ID                  string         `json:"id"`
	Kind                string         `json:"kind"`
	DefinitionID        string         `json:"definition_id"`
	Trigger             string         `json:"trigger"`
	DedupeKey           string         `json:"dedupe_key"`
	Payload             string         `json:"payload"`
	State               string         `json:"state"`
	Attempt             int64          `json:"attempt"`
	MaxAttempts         int64          `json:"max_attempts"`
	RetryInitialSeconds int64          `json:"retry_initial_seconds"`
	RetryMaxSeconds     int64          `json:"retry_max_seconds"`
	RunAt               int64          `json:"run_at"`
	LeaseOwner          sql.NullString `json:"lease_owner"`
	LeaseUntil          sql.NullInt64  `json:"lease_until"`
	CancelRequested     int64          `json:"cancel_requested"`
	LastError           sql.NullString `json:"last_error"`
	ParentExecutionID   sql.NullString `json:"parent_execution_id"`
	CreatedAt           int64          `json:"created_at"`
	StartedAt           sql.NullInt64  `json:"started_at"`
	FinishedAt          sql.NullInt64  `json:"finished_at"`
}

type JobExecutionActivity struct {
	ExecutionID string         `json:"execution_id"`
	Name        string         `json:"name"`
	InputHash   string         `json:"input_hash"`
	State       string         `json:"state"`
	Attempt     int64          `json:"attempt"`
	Result      sql.NullString `json:"result"`
	Checkpoint  sql.NullString `json:"checkpoint"`
	LastError   sql.NullString `json:"last_error"`
	CreatedAt   int64          `json:"created_at"`
	StartedAt   sql.NullInt64  `json:"started_at"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
}

type JobExecutionEvent struct {
	Sequence    int64  `json:"sequence"`
	ExecutionID string `json:"execution_id"`
	EventType   string `json:"event_type"`
	Data        string `json:"data"`
	CreatedAt   int64  `json:"created_at"`
}

type JobExecutionResource struct {
	ExecutionID string `json:"execution_id"`
	ResourceKey string `json:"resource_key"`
}

type JobResourceLock struct {
	ResourceKey string `json:"resource_key"`
	ExecutionID string `json:"execution_id"`
	LeaseUntil  int64  `json:"lease_until"`
}
