// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jobquery

import (
	"context"
)

type Querier interface {
	CancelPendingExecution(ctx context.Context, arg CancelPendingExecutionParams) (int64, error)
	CheckpointActivity(ctx context.Context, arg CheckpointActivityParams) (int64, error)
	ClaimExecution(ctx context.Context, arg ClaimExecutionParams) (int64, error)
	CompleteActivity(ctx context.Context, arg CompleteActivityParams) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (int64, error)
	CreateExecution(ctx context.Context, arg CreateExecutionParams) error
	CreateExecutionEvent(ctx context.Context, arg CreateExecutionEventParams) error
	CreateExecutionResource(ctx context.Context, arg CreateExecutionResourceParams) error
	CreateResourceLock(ctx context.Context, arg CreateResourceLockParams) (int64, error)
	DelayExecution(ctx context.Context, arg DelayExecutionParams) error
	DeleteExpiredResourceLocks(ctx context.Context, leaseUntil int64) error
	DeleteResourceLocks(ctx context.Context, executionID string) error
	FailActivity(ctx context.Context, arg FailActivityParams) (int64, error)
	FinishExecution(ctx context.Context, arg FinishExecutionParams) (int64, error)
	GetActiveExecutionByDefinition(ctx context.Context, arg GetActiveExecutionByDefinitionParams) (JobExecution, error)
	GetActivity(ctx context.Context, arg GetActivityParams) (JobExecutionActivity, error)
	GetExecution(ctx context.Context, id string) (JobExecution, error)
	GetExecutionByDedupeKey(ctx context.Context, dedupeKey string) (JobExecution, error)
	ListClaimableExecutionIDs(ctx context.Context, runAt int64) ([]string, error)
	ListExecutionEvents(ctx context.Context, executionID string) ([]JobExecutionEvent, error)
	ListExecutionResources(ctx context.Context, executionID string) ([]string, error)
	ReleaseExecutionClaim(ctx context.Context, arg ReleaseExecutionClaimParams) error
	RenewExecutionLease(ctx context.Context, arg RenewExecutionLeaseParams) (int64, error)
	RenewResourceLocks(ctx context.Context, arg RenewResourceLocksParams) error
	RequestExecutionCancellation(ctx context.Context, id string) (int64, error)
	RequeueExpiredExecutions(ctx context.Context, arg RequeueExpiredExecutionsParams) error
	StartActivity(ctx context.Context, arg StartActivityParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
