// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_engine.sql

package jobquery

import (
	"context"
	"database/sql"
)

const cancelPendingExecution = `-- name: CancelPendingExecution :execrows
UPDATE job_executions
SET state = 'canceled', finished_at = ?, lease_owner = NULL, lease_until = NULL
WHERE id = ? AND state = 'pending' AND cancel_requested = 1
`

type CancelPendingExecutionParams struct {
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) CancelPendingExecution(ctx context.Context, arg CancelPendingExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelPendingExecution, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const checkpointActivity = `-- name: CheckpointActivity :execrows
UPDATE job_execution_activities
SET checkpoint = ?
WHERE execution_id = ? AND name = ? AND state = 'running'
`

type CheckpointActivityParams struct {
	Checkpoint  sql.NullString `json:"checkpoint"`
	ExecutionID string         `json:"execution_id"`
	Name        string         `json:"name"`
}

func (q *Queries) CheckpointActivity(ctx context.Context, arg CheckpointActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, checkpointActivity, arg.Checkpoint, arg.ExecutionID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimExecution = `-- name: ClaimExecution :execrows
UPDATE job_executions
SET state = 'running', attempt = attempt + 1, lease_owner = ?, lease_until = ?,
    started_at = COALESCE(started_at, ?)
WHERE id = ? AND state = 'pending' AND cancel_requested = 0 AND run_at <= ?
`

type ClaimExecutionParams struct {
	LeaseOwner sql.NullString `json:"lease_owner"`
	LeaseUntil sql.NullInt64  `json:"lease_until"`
	StartedAt  sql.NullInt64  `json:"started_at"`
	ID         string         `json:"id"`
	RunAt      int64          `json:"run_at"`
}

func (q *Queries) ClaimExecution(ctx context.Context, arg ClaimExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimExecution,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.StartedAt,
		arg.ID,
		arg.RunAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeActivity = `-- name: CompleteActivity :execrows
UPDATE job_execution_activities
SET state = 'completed', result = ?, completed_at = ?
WHERE execution_id = ? AND name = ? AND state = 'running'
`

type CompleteActivityParams struct {
	Result      sql.NullString `json:"result"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
	ExecutionID string         `json:"execution_id"`
	Name        string         `json:"name"`
}

func (q *Queries) CompleteActivity(ctx context.Context, arg CompleteActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeActivity,
		arg.Result,
		arg.CompletedAt,
		arg.ExecutionID,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createActivity = `-- name: CreateActivity :execrows
INSERT INTO job_execution_activities (
    execution_id, name, input_hash, state, created_at
) VALUES (?, ?, ?, 'pending', ?)
ON CONFLICT(execution_id, name) DO NOTHING
`

type CreateActivityParams struct {
	ExecutionID string `json:"execution_id"`
	Name        string `json:"name"`
	InputHash   string `json:"input_hash"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createActivity,
		arg.ExecutionID,
		arg.Name,
		arg.InputHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createExecution = `-- name: CreateExecution :exec
INSERT INTO job_executions (
    id, kind, definition_id, trigger, dedupe_key, payload, state, attempt,
    max_attempts, retry_initial_seconds, retry_max_seconds, run_at, created_at,
    parent_execution_id
) VALUES (?, ?, ?, ?, ?, ?, 'pending', 0, ?, ?, ?, ?, ?, ?)
`

type CreateExecutionParams struct {
	ID                  string         `json:"id"`
	Kind                string         `json:"kind"`
	DefinitionID        string         `json:"definition_id"`
	Trigger             string         `json:"trigger"`
	DedupeKey           string         `json:"dedupe_key"`
	Payload             string         `json:"payload"`
	MaxAttempts         int64          `json:"max_attempts"`
	RetryInitialSeconds int64          `json:"retry_initial_seconds"`
	RetryMaxSeconds     int64          `json:"retry_max_seconds"`
	RunAt               int64          `json:"run_at"`
	CreatedAt           int64          `json:"created_at"`
	ParentExecutionID   sql.NullString `json:"parent_execution_id"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) error {
	_, err := q.db.ExecContext(ctx, createExecution,
		arg.ID,
		arg.Kind,
		arg.DefinitionID,
		arg.Trigger,
		arg.DedupeKey,
		arg.Payload,
		arg.MaxAttempts,
		arg.RetryInitialSeconds,
		arg.RetryMaxSeconds,
		arg.RunAt,
		arg.CreatedAt,
		arg.ParentExecutionID,
	)
	return err
}

const createExecutionEvent = `-- name: CreateExecutionEvent :exec
INSERT INTO job_execution_events (execution_id, event_type, data, created_at)
VALUES (?, ?, ?, ?)
`

type CreateExecutionEventParams struct {
	ExecutionID string `json:"execution_id"`
	EventType   string `json:"event_type"`
	Data        string `json:"data"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateExecutionEvent(ctx context.Context, arg CreateExecutionEventParams) error {
	_, err := q.db.ExecContext(ctx, createExecutionEvent,
		arg.ExecutionID,
		arg.EventType,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const createExecutionResource = `-- name: CreateExecutionResource :exec
INSERT INTO job_execution_resources (execution_id, resource_key) VALUES (?, ?)
`

type CreateExecutionResourceParams struct {
	ExecutionID string `json:"execution_id"`
	ResourceKey string `json:"resource_key"`
}

func (q *Queries) CreateExecutionResource(ctx context.Context, arg CreateExecutionResourceParams) error {
	_, err := q.db.ExecContext(ctx, createExecutionResource, arg.ExecutionID, arg.ResourceKey)
	return err
}

const createResourceLock = `-- name: CreateResourceLock :execrows
INSERT INTO job_resource_locks (resource_key, execution_id, lease_until)
VALUES (?, ?, ?)
ON CONFLICT(resource_key) DO UPDATE SET
    execution_id = excluded.execution_id,
    lease_until = excluded.lease_until
WHERE job_resource_locks.execution_id = excluded.execution_id
`

type CreateResourceLockParams struct {
	ResourceKey string `json:"resource_key"`
	ExecutionID string `json:"execution_id"`
	LeaseUntil  int64  `json:"lease_until"`
}

func (q *Queries) CreateResourceLock(ctx context.Context, arg CreateResourceLockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createResourceLock, arg.ResourceKey, arg.ExecutionID, arg.LeaseUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const delayExecution = `-- name: DelayExecution :exec
UPDATE job_executions SET run_at = ? WHERE id = ? AND state = 'pending'
`

type DelayExecutionParams struct {
	RunAt int64  `json:"run_at"`
	ID    string `json:"id"`
}

func (q *Queries) DelayExecution(ctx context.Context, arg DelayExecutionParams) error {
	_, err := q.db.ExecContext(ctx, delayExecution, arg.RunAt, arg.ID)
	return err
}

const deleteExpiredResourceLocks = `-- name: DeleteExpiredResourceLocks :exec
DELETE FROM job_resource_locks WHERE lease_until < ?
`

func (q *Queries) DeleteExpiredResourceLocks(ctx context.Context, leaseUntil int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredResourceLocks, leaseUntil)
	return err
}

const deleteResourceLocks = `-- name: DeleteResourceLocks :exec
DELETE FROM job_resource_locks WHERE execution_id = ?
`

func (q *Queries) DeleteResourceLocks(ctx context.Context, executionID string) error {
	_, err := q.db.ExecContext(ctx, deleteResourceLocks, executionID)
	return err
}

const failActivity = `-- name: FailActivity :execrows
UPDATE job_execution_activities
SET state = 'pending', last_error = ?
WHERE execution_id = ? AND name = ? AND state = 'running'
`

type FailActivityParams struct {
	LastError   sql.NullString `json:"last_error"`
	ExecutionID string         `json:"execution_id"`
	Name        string         `json:"name"`
}

func (q *Queries) FailActivity(ctx context.Context, arg FailActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failActivity, arg.LastError, arg.ExecutionID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishExecution = `-- name: FinishExecution :execrows
UPDATE job_executions
SET state = ?, run_at = ?, lease_owner = NULL, lease_until = NULL,
    last_error = ?, finished_at = ?
WHERE id = ? AND state = 'running' AND lease_owner = ?
`

type FinishExecutionParams struct {
	State      string         `json:"state"`
	RunAt      int64          `json:"run_at"`
	LastError  sql.NullString `json:"last_error"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
	ID         string         `json:"id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
}

func (q *Queries) FinishExecution(ctx context.Context, arg FinishExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishExecution,
		arg.State,
		arg.RunAt,
		arg.LastError,
		arg.FinishedAt,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveExecutionByDefinition = `-- name: GetActiveExecutionByDefinition :one
SELECT id, kind, definition_id, trigger, dedupe_key, payload, state, attempt,
    max_attempts, retry_initial_seconds, retry_max_seconds, run_at, lease_owner,
    lease_until, cancel_requested, last_error, parent_execution_id, created_at,
    started_at, finished_at
FROM job_executions
WHERE kind = ? AND definition_id = ? AND state IN ('pending', 'running')
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveExecutionByDefinitionParams struct {
	Kind         string `json:"kind"`
	DefinitionID string `json:"definition_id"`
}

func (q *Queries) GetActiveExecutionByDefinition(ctx context.Context, arg GetActiveExecutionByDefinitionParams) (JobExecution, error) {
	row := q.db.QueryRowContext(ctx, getActiveExecutionByDefinition, arg.Kind, arg.DefinitionID)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DefinitionID,
		&i.Trigger,
		&i.DedupeKey,
		&i.Payload,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryInitialSeconds,
		&i.RetryMaxSeconds,
		&i.RunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CancelRequested,
		&i.LastError,
		&i.ParentExecutionID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getActivity = `-- name: GetActivity :one
SELECT execution_id, name, input_hash, state, attempt, result, checkpoint,
    last_error, created_at, started_at, completed_at
FROM job_execution_activities
WHERE execution_id = ? AND name = ?
`

type GetActivityParams struct {
	ExecutionID string `json:"execution_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetActivity(ctx context.Context, arg GetActivityParams) (JobExecutionActivity, error) {
	row := q.db.QueryRowContext(ctx, getActivity, arg.ExecutionID, arg.Name)
	var i JobExecutionActivity
	err := row.Scan(
		&i.ExecutionID,
		&i.Name,
		&i.InputHash,
		&i.State,
		&i.Attempt,
		&i.Result,
		&i.Checkpoint,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT id, kind, definition_id, trigger, dedupe_key, payload, state, attempt,
    max_attempts, retry_initial_seconds, retry_max_seconds, run_at, lease_owner,
    lease_until, cancel_requested, last_error, parent_execution_id, created_at,
    started_at, finished_at
FROM job_executions
WHERE id = ?
`

func (q *Queries) GetExecution(ctx context.Context, id string) (JobExecution, error) {
	row := q.db.QueryRowContext(ctx, getExecution, id)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DefinitionID,
		&i.Trigger,
		&i.DedupeKey,
		&i.Payload,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryInitialSeconds,
		&i.RetryMaxSeconds,
		&i.RunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CancelRequested,
		&i.LastError,
		&i.ParentExecutionID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getExecutionByDedupeKey = `-- name: GetExecutionByDedupeKey :one
SELECT id, kind, definition_id, trigger, dedupe_key, payload, state, attempt,
    max_attempts, retry_initial_seconds, retry_max_seconds, run_at, lease_owner,
    lease_until, cancel_requested, last_error, parent_execution_id, created_at,
    started_at, finished_at
FROM job_executions
WHERE dedupe_key = ?
`

func (q *Queries) GetExecutionByDedupeKey(ctx context.Context, dedupeKey string) (JobExecution, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByDedupeKey, dedupeKey)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DefinitionID,
		&i.Trigger,
		&i.DedupeKey,
		&i.Payload,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryInitialSeconds,
		&i.RetryMaxSeconds,
		&i.RunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CancelRequested,
		&i.LastError,
		&i.ParentExecutionID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const invalidateActivity = `-- name: InvalidateActivity :execrows
UPDATE job_execution_activities
SET state = 'pending', result = NULL, checkpoint = NULL, completed_at = NULL
WHERE execution_id = ? AND name = ? AND state = 'completed'
`

type InvalidateActivityParams struct {
	ExecutionID string `json:"execution_id"`
	Name        string `json:"name"`
}

func (q *Queries) InvalidateActivity(ctx context.Context, arg InvalidateActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, invalidateActivity, arg.ExecutionID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listClaimableExecutionIDs = `-- name: ListClaimableExecutionIDs :many
SELECT id
FROM job_executions
WHERE state = 'pending' AND cancel_requested = 0 AND run_at <= ?
ORDER BY run_at, created_at
LIMIT 32
`

func (q *Queries) ListClaimableExecutionIDs(ctx context.Context, runAt int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listClaimableExecutionIDs, runAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionEvents = `-- name: ListExecutionEvents :many
SELECT sequence, execution_id, event_type, data, created_at
FROM job_execution_events
WHERE execution_id = ?
ORDER BY sequence
`

func (q *Queries) ListExecutionEvents(ctx context.Context, executionID string) ([]JobExecutionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionEvents, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobExecutionEvent{}
	for rows.Next() {
		var i JobExecutionEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.ExecutionID,
			&i.EventType,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionResources = `-- name: ListExecutionResources :many
SELECT resource_key FROM job_execution_resources WHERE execution_id = ? ORDER BY resource_key
`

func (q *Queries) ListExecutionResources(ctx context.Context, executionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionResources, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var resource_key string
		if err := rows.Scan(&resource_key); err != nil {
			return nil, err
		}
		items = append(items, resource_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseExecutionClaim = `-- name: ReleaseExecutionClaim :exec
UPDATE job_executions
SET state = 'pending', lease_owner = NULL, lease_until = NULL, run_at = ?
WHERE id = ? AND state = 'running' AND lease_owner = ?
`

type ReleaseExecutionClaimParams struct {
	RunAt      int64          `json:"run_at"`
	ID         string         `json:"id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
}

func (q *Queries) ReleaseExecutionClaim(ctx context.Context, arg ReleaseExecutionClaimParams) error {
	_, err := q.db.ExecContext(ctx, releaseExecutionClaim, arg.RunAt, arg.ID, arg.LeaseOwner)
	return err
}

const renewExecutionLease = `-- name: RenewExecutionLease :execrows
UPDATE job_executions SET lease_until = ?
WHERE id = ? AND state = 'running' AND lease_owner = ?
`

type RenewExecutionLeaseParams struct {
	LeaseUntil sql.NullInt64  `json:"lease_until"`
	ID         string         `json:"id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
}

func (q *Queries) RenewExecutionLease(ctx context.Context, arg RenewExecutionLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewExecutionLease, arg.LeaseUntil, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewResourceLocks = `-- name: RenewResourceLocks :exec
UPDATE job_resource_locks SET lease_until = ? WHERE execution_id = ?
`

type RenewResourceLocksParams struct {
	LeaseUntil  int64  `json:"lease_until"`
	ExecutionID string `json:"execution_id"`
}

func (q *Queries) RenewResourceLocks(ctx context.Context, arg RenewResourceLocksParams) error {
	_, err := q.db.ExecContext(ctx, renewResourceLocks, arg.LeaseUntil, arg.ExecutionID)
	return err
}

const requestExecutionCancellation = `-- name: RequestExecutionCancellation :execrows
UPDATE job_executions SET cancel_requested = 1
WHERE id = ? AND state IN ('pending', 'running')
`

func (q *Queries) RequestExecutionCancellation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestExecutionCancellation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueExpiredExecutions = `-- name: RequeueExpiredExecutions :exec
UPDATE job_executions
SET state = 'pending', lease_owner = NULL, lease_until = NULL, run_at = ?
WHERE state = 'running' AND lease_until < ? AND cancel_requested = 0
`

type RequeueExpiredExecutionsParams struct {
	RunAt      int64         `json:"run_at"`
	LeaseUntil sql.NullInt64 `json:"lease_until"`
}

func (q *Queries) RequeueExpiredExecutions(ctx context.Context, arg RequeueExpiredExecutionsParams) error {
	_, err := q.db.ExecContext(ctx, requeueExpiredExecutions, arg.RunAt, arg.LeaseUntil)
	return err
}

const startActivity = `-- name: StartActivity :execrows
UPDATE job_execution_activities
SET state = 'running', attempt = attempt + 1, started_at = ?, last_error = NULL
WHERE execution_id = ? AND name = ? AND state IN ('pending', 'running')
`

type StartActivityParams struct {
	StartedAt   sql.NullInt64 `json:"started_at"`
	ExecutionID string        `json:"execution_id"`
	Name        string        `json:"name"`
}

func (q *Queries) StartActivity(ctx context.Context, arg StartActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startActivity, arg.StartedAt, arg.ExecutionID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
