ALTER TABLE backups ADD COLUMN expand_zip BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE backups ADD COLUMN expand_7z BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE backups ADD COLUMN expand_max_depth INTEGER NOT NULL DEFAULT 8;
