// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_hosts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const agentHostExists = `-- name: AgentHostExists :one
SELECT 1 FROM agent_hosts WHERE name = ? LIMIT 1
`

func (q *Queries) AgentHostExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, agentHostExists, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAgentHost = `-- name: CreateAgentHost :exec
INSERT INTO agent_hosts (name, ip, auth, token_used, os)
VALUES (?, ?, ?, ?, ?)
`

type CreateAgentHostParams struct {
	Name      string         `json:"name"`
	Ip        string         `json:"ip"`
	Auth      sql.NullString `json:"auth"`
	TokenUsed sql.NullString `json:"token_used"`
	Os        string         `json:"os"`
}

func (q *Queries) CreateAgentHost(ctx context.Context, arg CreateAgentHostParams) error {
	_, err := q.db.ExecContext(ctx, createAgentHost,
		arg.Name,
		arg.Ip,
		arg.Auth,
		arg.TokenUsed,
		arg.Os,
	)
	return err
}

const deleteAgentHost = `-- name: DeleteAgentHost :execrows
DELETE FROM agent_hosts WHERE name = ?
`

func (q *Queries) DeleteAgentHost(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentHost, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentHost = `-- name: GetAgentHost :one
SELECT name, ip, auth, token_used, os
FROM agent_hosts
WHERE name = ?
`

func (q *Queries) GetAgentHost(ctx context.Context, name string) (AgentHost, error) {
	row := q.db.QueryRowContext(ctx, getAgentHost, name)
	var i AgentHost
	err := row.Scan(
		&i.Name,
		&i.Ip,
		&i.Auth,
		&i.TokenUsed,
		&i.Os,
	)
	return i, err
}

const getAgentHostAuth = `-- name: GetAgentHostAuth :one
SELECT auth FROM agent_hosts WHERE name = ?
`

func (q *Queries) GetAgentHostAuth(ctx context.Context, name string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getAgentHostAuth, name)
	var auth sql.NullString
	err := row.Scan(&auth)
	return auth, err
}

const listAllAgentHosts = `-- name: ListAllAgentHosts :many
SELECT name, ip, auth, token_used, os
FROM agent_hosts
ORDER BY name
`

func (q *Queries) ListAllAgentHosts(ctx context.Context) ([]AgentHost, error) {
	rows, err := q.db.QueryContext(ctx, listAllAgentHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentHost{}
	for rows.Next() {
		var i AgentHost
		if err := rows.Scan(
			&i.Name,
			&i.Ip,
			&i.Auth,
			&i.TokenUsed,
			&i.Os,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentHost = `-- name: UpdateAgentHost :exec
UPDATE agent_hosts SET
    ip = ?, auth = ?, token_used = ?, os = ?
WHERE name = ?
`

type UpdateAgentHostParams struct {
	Ip        string         `json:"ip"`
	Auth      sql.NullString `json:"auth"`
	TokenUsed sql.NullString `json:"token_used"`
	Os        string         `json:"os"`
	Name      string         `json:"name"`
}

func (q *Queries) UpdateAgentHost(ctx context.Context, arg UpdateAgentHostParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentHost,
		arg.Ip,
		arg.Auth,
		arg.TokenUsed,
		arg.Os,
		arg.Name,
	)
	return err
}
