// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_settings.sql

package sqlc

import (
	"context"
)

const deleteAlertSetting = `-- name: DeleteAlertSetting :exec
DELETE FROM alert_settings WHERE name = ?
`

func (q *Queries) DeleteAlertSetting(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteAlertSetting, name)
	return err
}

const getAlertSetting = `-- name: GetAlertSetting :one
SELECT name, enabled, threshold, severity, comment, last_sent
FROM alert_settings
WHERE name = ?
`

func (q *Queries) GetAlertSetting(ctx context.Context, name string) (AlertSetting, error) {
	row := q.db.QueryRowContext(ctx, getAlertSetting, name)
	var i AlertSetting
	err := row.Scan(
		&i.Name,
		&i.Enabled,
		&i.Threshold,
		&i.Severity,
		&i.Comment,
		&i.LastSent,
	)
	return i, err
}

const listAlertSettings = `-- name: ListAlertSettings :many
SELECT name, enabled, threshold, severity, comment, last_sent
FROM alert_settings
ORDER BY name
`

func (q *Queries) ListAlertSettings(ctx context.Context) ([]AlertSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAlertSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertSetting{}
	for rows.Next() {
		var i AlertSetting
		if err := rows.Scan(
			&i.Name,
			&i.Enabled,
			&i.Threshold,
			&i.Severity,
			&i.Comment,
			&i.LastSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertLastSent = `-- name: UpdateAlertLastSent :exec
UPDATE alert_settings SET last_sent = ? WHERE name = ?
`

type UpdateAlertLastSentParams struct {
	LastSent int64  `json:"last_sent"`
	Name     string `json:"name"`
}

func (q *Queries) UpdateAlertLastSent(ctx context.Context, arg UpdateAlertLastSentParams) error {
	_, err := q.db.ExecContext(ctx, updateAlertLastSent, arg.LastSent, arg.Name)
	return err
}

const upsertAlertSetting = `-- name: UpsertAlertSetting :exec
INSERT INTO alert_settings (name, enabled, threshold, severity, comment, last_sent)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    enabled   = excluded.enabled,
    threshold = excluded.threshold,
    severity  = excluded.severity,
    comment   = excluded.comment,
    last_sent = excluded.last_sent
`

type UpsertAlertSettingParams struct {
	Name      string `json:"name"`
	Enabled   int64  `json:"enabled"`
	Threshold int64  `json:"threshold"`
	Severity  string `json:"severity"`
	Comment   string `json:"comment"`
	LastSent  int64  `json:"last_sent"`
}

func (q *Queries) UpsertAlertSetting(ctx context.Context, arg UpsertAlertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlertSetting,
		arg.Name,
		arg.Enabled,
		arg.Threshold,
		arg.Severity,
		arg.Comment,
		arg.LastSent,
	)
	return err
}
