// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_exclusions.sql

package sqlc

import (
	"context"
)

const createAlertExclusion = `-- name: CreateAlertExclusion :exec
INSERT INTO alert_exclusions (alert_type, exclude_type, exclude_value, comment)
VALUES (?, ?, ?, ?)
ON CONFLICT (alert_type, exclude_type, exclude_value) DO UPDATE SET
    comment = excluded.comment
`

type CreateAlertExclusionParams struct {
	AlertType    string `json:"alert_type"`
	ExcludeType  string `json:"exclude_type"`
	ExcludeValue string `json:"exclude_value"`
	Comment      string `json:"comment"`
}

func (q *Queries) CreateAlertExclusion(ctx context.Context, arg CreateAlertExclusionParams) error {
	_, err := q.db.ExecContext(ctx, createAlertExclusion,
		arg.AlertType,
		arg.ExcludeType,
		arg.ExcludeValue,
		arg.Comment,
	)
	return err
}

const deleteAlertExclusion = `-- name: DeleteAlertExclusion :exec
DELETE FROM alert_exclusions WHERE id = ?
`

func (q *Queries) DeleteAlertExclusion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlertExclusion, id)
	return err
}

const deleteAlertExclusionsByType = `-- name: DeleteAlertExclusionsByType :exec
DELETE FROM alert_exclusions WHERE alert_type = ?
`

func (q *Queries) DeleteAlertExclusionsByType(ctx context.Context, alertType string) error {
	_, err := q.db.ExecContext(ctx, deleteAlertExclusionsByType, alertType)
	return err
}

const getAlertExclusion = `-- name: GetAlertExclusion :one
SELECT id, alert_type, exclude_type, exclude_value, comment
FROM alert_exclusions
WHERE id = ?
`

func (q *Queries) GetAlertExclusion(ctx context.Context, id int64) (AlertExclusion, error) {
	row := q.db.QueryRowContext(ctx, getAlertExclusion, id)
	var i AlertExclusion
	err := row.Scan(
		&i.ID,
		&i.AlertType,
		&i.ExcludeType,
		&i.ExcludeValue,
		&i.Comment,
	)
	return i, err
}

const getAlertExclusionsByType = `-- name: GetAlertExclusionsByType :many
SELECT id, alert_type, exclude_type, exclude_value, comment
FROM alert_exclusions
WHERE alert_type = ? AND exclude_type = ?
`

type GetAlertExclusionsByTypeParams struct {
	AlertType   string `json:"alert_type"`
	ExcludeType string `json:"exclude_type"`
}

func (q *Queries) GetAlertExclusionsByType(ctx context.Context, arg GetAlertExclusionsByTypeParams) ([]AlertExclusion, error) {
	rows, err := q.db.QueryContext(ctx, getAlertExclusionsByType, arg.AlertType, arg.ExcludeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertExclusion{}
	for rows.Next() {
		var i AlertExclusion
		if err := rows.Scan(
			&i.ID,
			&i.AlertType,
			&i.ExcludeType,
			&i.ExcludeValue,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertExclusions = `-- name: ListAlertExclusions :many
SELECT id, alert_type, exclude_type, exclude_value, comment
FROM alert_exclusions
WHERE alert_type = ?
ORDER BY exclude_type, exclude_value
`

func (q *Queries) ListAlertExclusions(ctx context.Context, alertType string) ([]AlertExclusion, error) {
	rows, err := q.db.QueryContext(ctx, listAlertExclusions, alertType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertExclusion{}
	for rows.Next() {
		var i AlertExclusion
		if err := rows.Scan(
			&i.ID,
			&i.AlertType,
			&i.ExcludeType,
			&i.ExcludeValue,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAlertExclusions = `-- name: ListAllAlertExclusions :many
SELECT id, alert_type, exclude_type, exclude_value, comment
FROM alert_exclusions
ORDER BY alert_type, exclude_type, exclude_value
`

func (q *Queries) ListAllAlertExclusions(ctx context.Context) ([]AlertExclusion, error) {
	rows, err := q.db.QueryContext(ctx, listAllAlertExclusions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertExclusion{}
	for rows.Next() {
		var i AlertExclusion
		if err := rows.Scan(
			&i.ID,
			&i.AlertType,
			&i.ExcludeType,
			&i.ExcludeValue,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
