// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type AgentHost struct {
	Name      string         `json:"name"`
	Ip        string         `json:"ip"`
	Auth      sql.NullString `json:"auth"`
	TokenUsed sql.NullString `json:"token_used"`
	Os        string         `json:"os"`
}

type Backup struct {
	ID                 string         `json:"id"`
	Store              string         `json:"store"`
	Mode               interface{}    `json:"mode"`
	SourceMode         interface{}    `json:"source_mode"`
	Target             string         `json:"target"`
	Subpath            sql.NullString `json:"subpath"`
	Schedule           sql.NullString `json:"schedule"`
	Comment            sql.NullString `json:"comment"`
	NotificationMode   sql.NullString `json:"notification_mode"`
	Namespace          sql.NullString `json:"namespace"`
	CurrentPid         sql.NullString `json:"current_pid"`
	LastRunUpid        sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid sql.NullString `json:"last_successful_upid"`
	Retry              sql.NullInt64  `json:"retry"`
	RetryInterval      sql.NullInt64  `json:"retry_interval"`
	MaxDirEntries      sql.NullInt64  `json:"max_dir_entries"`
	ReadMode           interface{}    `json:"read_mode"`
	PreScript          string         `json:"pre_script"`
	PostScript         string         `json:"post_script"`
	IncludeXattr       sql.NullInt64  `json:"include_xattr"`
	LegacyXattr        sql.NullInt64  `json:"legacy_xattr"`
	LastRunStatus      sql.NullInt64  `json:"last_run_status"`
	RetryCount         sql.NullInt64  `json:"retry_count"`
}

type Exclusion struct {
	JobID   string         `json:"job_id"`
	Path    string         `json:"path"`
	Comment sql.NullString `json:"comment"`
}

type Restore struct {
	ID                 string         `json:"id"`
	Store              string         `json:"store"`
	Namespace          sql.NullString `json:"namespace"`
	Snapshot           string         `json:"snapshot"`
	SrcPath            string         `json:"src_path"`
	DestTarget         string         `json:"dest_target"`
	DestTargetPath     sql.NullString `json:"dest_target_path"`
	DestSubpath        sql.NullString `json:"dest_subpath"`
	Comment            sql.NullString `json:"comment"`
	CurrentPid         sql.NullString `json:"current_pid"`
	LastRunUpid        sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid sql.NullString `json:"last_successful_upid"`
	Retry              sql.NullInt64  `json:"retry"`
	RetryInterval      sql.NullInt64  `json:"retry_interval"`
	PreScript          string         `json:"pre_script"`
	PostScript         string         `json:"post_script"`
	RestoreMode        int64          `json:"restore_mode"`
	LastRunStatus      sql.NullInt64  `json:"last_run_status"`
	RetryCount         sql.NullInt64  `json:"retry_count"`
	NotificationMode   sql.NullString `json:"notification_mode"`
}

type Script struct {
	Path        string         `json:"path"`
	Description sql.NullString `json:"description"`
}

type Target struct {
	Name             string         `json:"name"`
	Path             string         `json:"path"`
	AgentHost        sql.NullString `json:"agent_host"`
	VolumeID         sql.NullString `json:"volume_id"`
	VolumeType       sql.NullString `json:"volume_type"`
	VolumeName       sql.NullString `json:"volume_name"`
	VolumeFs         sql.NullString `json:"volume_fs"`
	VolumeTotalBytes sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes  sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes  sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal      sql.NullString `json:"volume_total"`
	VolumeUsed       sql.NullString `json:"volume_used"`
	VolumeFree       sql.NullString `json:"volume_free"`
	MountScript      string         `json:"mount_script"`
	SecretS3         string         `json:"secret_s3"`
}

type Token struct {
	Token     string         `json:"token"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt sql.NullInt64  `json:"created_at"`
	Revoked   sql.NullBool   `json:"revoked"`
}

type VerificationJob struct {
	ID                    string         `json:"id"`
	BackupJobID           string         `json:"backup_job_id"`
	Store                 string         `json:"store"`
	Namespace             sql.NullString `json:"namespace"`
	Mode                  string         `json:"mode"`
	Schedule              sql.NullString `json:"schedule"`
	Comment               sql.NullString `json:"comment"`
	SpotConfig            sql.NullString `json:"spot_config"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	Retry                 sql.NullInt64  `json:"retry"`
	RetryInterval         sql.NullInt64  `json:"retry_interval"`
	CreatedAt             sql.NullInt64  `json:"created_at"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	RunOnBackupComplete   sql.NullInt64  `json:"run_on_backup_complete"`
	PendingSince          sql.NullInt64  `json:"pending_since"`
	TargetMode            sql.NullString `json:"target_mode"`
	Recursive             sql.NullInt64  `json:"recursive"`
	NotificationMode      sql.NullString `json:"notification_mode"`
}

type VerificationResult struct {
	ID                int64          `json:"id"`
	VerificationJobID string         `json:"verification_job_id"`
	Upid              sql.NullString `json:"upid"`
	Snapshot          string         `json:"snapshot"`
	SnapshotTime      int64          `json:"snapshot_time"`
	TotalFiles        sql.NullInt64  `json:"total_files"`
	VerifiedFiles     sql.NullInt64  `json:"verified_files"`
	FailedFiles       sql.NullInt64  `json:"failed_files"`
	SkippedFiles      sql.NullInt64  `json:"skipped_files"`
	Status            sql.NullString `json:"status"`
	StartedAt         sql.NullInt64  `json:"started_at"`
	CompletedAt       sql.NullInt64  `json:"completed_at"`
	Details           sql.NullString `json:"details"`
	TotalPopulation   int64          `json:"total_population"`
}
