// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_batches.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addJobToBatch = `-- name: AddJobToBatch :exec
INSERT INTO notification_batch_jobs (batch_name, job_type, job_id)
VALUES (?, ?, ?)
`

type AddJobToBatchParams struct {
	BatchName string `json:"batch_name"`
	JobType   string `json:"job_type"`
	JobID     string `json:"job_id"`
}

func (q *Queries) AddJobToBatch(ctx context.Context, arg AddJobToBatchParams) error {
	_, err := q.db.ExecContext(ctx, addJobToBatch, arg.BatchName, arg.JobType, arg.JobID)
	return err
}

const createNotificationBatch = `-- name: CreateNotificationBatch :exec
INSERT INTO notification_batches (name, comment, notification_mode, wait_timeout_secs, send_on_timeout)
VALUES (?, ?, ?, ?, ?)
`

type CreateNotificationBatchParams struct {
	Name             string         `json:"name"`
	Comment          sql.NullString `json:"comment"`
	NotificationMode sql.NullString `json:"notification_mode"`
	WaitTimeoutSecs  sql.NullInt64  `json:"wait_timeout_secs"`
	SendOnTimeout    sql.NullInt64  `json:"send_on_timeout"`
}

func (q *Queries) CreateNotificationBatch(ctx context.Context, arg CreateNotificationBatchParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationBatch,
		arg.Name,
		arg.Comment,
		arg.NotificationMode,
		arg.WaitTimeoutSecs,
		arg.SendOnTimeout,
	)
	return err
}

const deleteNotificationBatch = `-- name: DeleteNotificationBatch :exec
DELETE FROM notification_batches WHERE name = ?
`

func (q *Queries) DeleteNotificationBatch(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationBatch, name)
	return err
}

const getBatchForJob = `-- name: GetBatchForJob :one
SELECT nb.name, nb.comment, nb.notification_mode, nb.wait_timeout_secs, nb.send_on_timeout, nb.created_at
FROM notification_batches nb
JOIN notification_batch_jobs nbj ON nb.name = nbj.batch_name
WHERE nbj.job_type = ? AND nbj.job_id = ?
`

type GetBatchForJobParams struct {
	JobType string `json:"job_type"`
	JobID   string `json:"job_id"`
}

func (q *Queries) GetBatchForJob(ctx context.Context, arg GetBatchForJobParams) (NotificationBatch, error) {
	row := q.db.QueryRowContext(ctx, getBatchForJob, arg.JobType, arg.JobID)
	var i NotificationBatch
	err := row.Scan(
		&i.Name,
		&i.Comment,
		&i.NotificationMode,
		&i.WaitTimeoutSecs,
		&i.SendOnTimeout,
		&i.CreatedAt,
	)
	return i, err
}

const getBatchJobsByBatch = `-- name: GetBatchJobsByBatch :many
SELECT batch_name, job_type, job_id FROM notification_batch_jobs WHERE batch_name = ?
`

func (q *Queries) GetBatchJobsByBatch(ctx context.Context, batchName string) ([]NotificationBatchJob, error) {
	rows, err := q.db.QueryContext(ctx, getBatchJobsByBatch, batchName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationBatchJob{}
	for rows.Next() {
		var i NotificationBatchJob
		if err := rows.Scan(&i.BatchName, &i.JobType, &i.JobID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchJobsByJobType = `-- name: GetBatchJobsByJobType :many
SELECT batch_name, job_type, job_id FROM notification_batch_jobs WHERE job_type = ?
`

func (q *Queries) GetBatchJobsByJobType(ctx context.Context, jobType string) ([]NotificationBatchJob, error) {
	rows, err := q.db.QueryContext(ctx, getBatchJobsByJobType, jobType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationBatchJob{}
	for rows.Next() {
		var i NotificationBatchJob
		if err := rows.Scan(&i.BatchName, &i.JobType, &i.JobID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationBatch = `-- name: GetNotificationBatch :one
SELECT name, comment, notification_mode, wait_timeout_secs, send_on_timeout, created_at FROM notification_batches WHERE name = ?
`

func (q *Queries) GetNotificationBatch(ctx context.Context, name string) (NotificationBatch, error) {
	row := q.db.QueryRowContext(ctx, getNotificationBatch, name)
	var i NotificationBatch
	err := row.Scan(
		&i.Name,
		&i.Comment,
		&i.NotificationMode,
		&i.WaitTimeoutSecs,
		&i.SendOnTimeout,
		&i.CreatedAt,
	)
	return i, err
}

const listBatchJobs = `-- name: ListBatchJobs :many
SELECT batch_name, job_type, job_id FROM notification_batch_jobs ORDER BY batch_name, job_type, job_id
`

func (q *Queries) ListBatchJobs(ctx context.Context) ([]NotificationBatchJob, error) {
	rows, err := q.db.QueryContext(ctx, listBatchJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationBatchJob{}
	for rows.Next() {
		var i NotificationBatchJob
		if err := rows.Scan(&i.BatchName, &i.JobType, &i.JobID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationBatches = `-- name: ListNotificationBatches :many
SELECT name, comment, notification_mode, wait_timeout_secs, send_on_timeout, created_at FROM notification_batches ORDER BY name
`

func (q *Queries) ListNotificationBatches(ctx context.Context) ([]NotificationBatch, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationBatch{}
	for rows.Next() {
		var i NotificationBatch
		if err := rows.Scan(
			&i.Name,
			&i.Comment,
			&i.NotificationMode,
			&i.WaitTimeoutSecs,
			&i.SendOnTimeout,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeJobFromAllBatches = `-- name: RemoveJobFromAllBatches :exec
DELETE FROM notification_batch_jobs WHERE job_type = ? AND job_id = ?
`

type RemoveJobFromAllBatchesParams struct {
	JobType string `json:"job_type"`
	JobID   string `json:"job_id"`
}

func (q *Queries) RemoveJobFromAllBatches(ctx context.Context, arg RemoveJobFromAllBatchesParams) error {
	_, err := q.db.ExecContext(ctx, removeJobFromAllBatches, arg.JobType, arg.JobID)
	return err
}

const removeJobFromBatch = `-- name: RemoveJobFromBatch :exec
DELETE FROM notification_batch_jobs
WHERE batch_name = ? AND job_type = ? AND job_id = ?
`

type RemoveJobFromBatchParams struct {
	BatchName string `json:"batch_name"`
	JobType   string `json:"job_type"`
	JobID     string `json:"job_id"`
}

func (q *Queries) RemoveJobFromBatch(ctx context.Context, arg RemoveJobFromBatchParams) error {
	_, err := q.db.ExecContext(ctx, removeJobFromBatch, arg.BatchName, arg.JobType, arg.JobID)
	return err
}

const removeJobsByBatch = `-- name: RemoveJobsByBatch :exec
DELETE FROM notification_batch_jobs WHERE batch_name = ?
`

func (q *Queries) RemoveJobsByBatch(ctx context.Context, batchName string) error {
	_, err := q.db.ExecContext(ctx, removeJobsByBatch, batchName)
	return err
}

const updateNotificationBatch = `-- name: UpdateNotificationBatch :exec
UPDATE notification_batches
SET comment = ?, notification_mode = ?, wait_timeout_secs = ?, send_on_timeout = ?
WHERE name = ?
`

type UpdateNotificationBatchParams struct {
	Comment          sql.NullString `json:"comment"`
	NotificationMode sql.NullString `json:"notification_mode"`
	WaitTimeoutSecs  sql.NullInt64  `json:"wait_timeout_secs"`
	SendOnTimeout    sql.NullInt64  `json:"send_on_timeout"`
	Name             string         `json:"name"`
}

func (q *Queries) UpdateNotificationBatch(ctx context.Context, arg UpdateNotificationBatchParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationBatch,
		arg.Comment,
		arg.NotificationMode,
		arg.WaitTimeoutSecs,
		arg.SendOnTimeout,
		arg.Name,
	)
	return err
}
