// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (token, comment, created_at, revoked)
VALUES (?, ?, ?, ?)
`

type CreateTokenParams struct {
	Token     string         `json:"token"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt sql.NullInt64  `json:"created_at"`
	Revoked   sql.NullBool   `json:"revoked"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.Token,
		arg.Comment,
		arg.CreatedAt,
		arg.Revoked,
	)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens WHERE token = ?
`

func (q *Queries) DeleteToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteToken, token)
	return err
}

const getToken = `-- name: GetToken :one
SELECT token, comment, created_at, revoked
FROM tokens
WHERE token = ?
`

func (q *Queries) GetToken(ctx context.Context, token string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getToken, token)
	var i Token
	err := row.Scan(
		&i.Token,
		&i.Comment,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const listAllTokens = `-- name: ListAllTokens :many
SELECT token, comment, created_at, revoked
FROM tokens
ORDER BY created_at DESC
`

func (q *Queries) ListAllTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.Token,
			&i.Comment,
			&i.CreatedAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTokensWithDetails = `-- name: ListAllTokensWithDetails :many
SELECT token, created_at, revoked
FROM tokens
`

type ListAllTokensWithDetailsRow struct {
	Token     string        `json:"token"`
	CreatedAt sql.NullInt64 `json:"created_at"`
	Revoked   sql.NullBool  `json:"revoked"`
}

func (q *Queries) ListAllTokensWithDetails(ctx context.Context) ([]ListAllTokensWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTokensWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTokensWithDetailsRow{}
	for rows.Next() {
		var i ListAllTokensWithDetailsRow
		if err := rows.Scan(&i.Token, &i.CreatedAt, &i.Revoked); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonRevokedTokens = `-- name: ListNonRevokedTokens :many
SELECT token, comment, created_at, revoked
FROM tokens
WHERE revoked = 0
ORDER BY created_at DESC
`

func (q *Queries) ListNonRevokedTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listNonRevokedTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.Token,
			&i.Comment,
			&i.CreatedAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE tokens 
SET revoked = 1 
WHERE token = ?
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
