// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_jobs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createVerificationJob = `-- name: CreateVerificationJob :exec
INSERT INTO verification_jobs (
    id, backup_job_id, store, namespace, mode, schedule, comment,
    spot_config, last_run_upid, last_successful_upid,
    last_run_status, retry_count, retry, retry_interval,
    last_run_starttime, last_run_endtime, last_successful_endtime,
    run_on_backup_complete, pending_since, notification_mode
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVerificationJobParams struct {
	ID                    string         `json:"id"`
	BackupJobID           string         `json:"backup_job_id"`
	Store                 string         `json:"store"`
	Namespace             sql.NullString `json:"namespace"`
	Mode                  string         `json:"mode"`
	Schedule              sql.NullString `json:"schedule"`
	Comment               sql.NullString `json:"comment"`
	SpotConfig            sql.NullString `json:"spot_config"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	Retry                 sql.NullInt64  `json:"retry"`
	RetryInterval         sql.NullInt64  `json:"retry_interval"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	RunOnBackupComplete   sql.NullInt64  `json:"run_on_backup_complete"`
	PendingSince          sql.NullInt64  `json:"pending_since"`
	NotificationMode      sql.NullString `json:"notification_mode"`
}

func (q *Queries) CreateVerificationJob(ctx context.Context, arg CreateVerificationJobParams) error {
	_, err := q.db.ExecContext(ctx, createVerificationJob,
		arg.ID,
		arg.BackupJobID,
		arg.Store,
		arg.Namespace,
		arg.Mode,
		arg.Schedule,
		arg.Comment,
		arg.SpotConfig,
		arg.LastRunUpid,
		arg.LastSuccessfulUpid,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.Retry,
		arg.RetryInterval,
		arg.LastRunStarttime,
		arg.LastRunEndtime,
		arg.LastSuccessfulEndtime,
		arg.RunOnBackupComplete,
		arg.PendingSince,
		arg.NotificationMode,
	)
	return err
}

const createVerificationResult = `-- name: CreateVerificationResult :execresult
INSERT INTO verification_results (
    verification_job_id, upid, snapshot, snapshot_time,
    total_files, verified_files, failed_files, skipped_files,
    status, started_at, completed_at, details, total_population
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVerificationResultParams struct {
	VerificationJobID string         `json:"verification_job_id"`
	Upid              sql.NullString `json:"upid"`
	Snapshot          string         `json:"snapshot"`
	SnapshotTime      int64          `json:"snapshot_time"`
	TotalFiles        sql.NullInt64  `json:"total_files"`
	VerifiedFiles     sql.NullInt64  `json:"verified_files"`
	FailedFiles       sql.NullInt64  `json:"failed_files"`
	SkippedFiles      sql.NullInt64  `json:"skipped_files"`
	Status            sql.NullString `json:"status"`
	StartedAt         sql.NullInt64  `json:"started_at"`
	CompletedAt       sql.NullInt64  `json:"completed_at"`
	Details           sql.NullString `json:"details"`
	TotalPopulation   int64          `json:"total_population"`
}

func (q *Queries) CreateVerificationResult(ctx context.Context, arg CreateVerificationResultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVerificationResult,
		arg.VerificationJobID,
		arg.Upid,
		arg.Snapshot,
		arg.SnapshotTime,
		arg.TotalFiles,
		arg.VerifiedFiles,
		arg.FailedFiles,
		arg.SkippedFiles,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Details,
		arg.TotalPopulation,
	)
}

const deleteVerificationJob = `-- name: DeleteVerificationJob :execrows
DELETE FROM verification_jobs WHERE id = ?
`

func (q *Queries) DeleteVerificationJob(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVerificationJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVerificationResults = `-- name: DeleteVerificationResults :execrows
DELETE FROM verification_results WHERE verification_job_id = ?
`

func (q *Queries) DeleteVerificationResults(ctx context.Context, verificationJobID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVerificationResults, verificationJobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestVerificationResult = `-- name: GetLatestVerificationResult :one
SELECT id, verification_job_id, upid, snapshot, snapshot_time, total_files, verified_files, failed_files, skipped_files, status, started_at, completed_at, details, total_population
FROM verification_results
WHERE verification_job_id = ?
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestVerificationResult(ctx context.Context, verificationJobID string) (VerificationResult, error) {
	row := q.db.QueryRowContext(ctx, getLatestVerificationResult, verificationJobID)
	var i VerificationResult
	err := row.Scan(
		&i.ID,
		&i.VerificationJobID,
		&i.Upid,
		&i.Snapshot,
		&i.SnapshotTime,
		&i.TotalFiles,
		&i.VerifiedFiles,
		&i.FailedFiles,
		&i.SkippedFiles,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Details,
		&i.TotalPopulation,
	)
	return i, err
}

const getVerificationJob = `-- name: GetVerificationJob :one
SELECT id, backup_job_id, store, namespace, mode, schedule, comment, spot_config, last_run_upid, last_successful_upid, last_run_status, retry_count, retry, retry_interval, created_at, last_run_starttime, last_run_endtime, last_successful_endtime, run_on_backup_complete, pending_since, target_mode, "recursive", notification_mode
FROM verification_jobs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetVerificationJob(ctx context.Context, id string) (VerificationJob, error) {
	row := q.db.QueryRowContext(ctx, getVerificationJob, id)
	var i VerificationJob
	err := row.Scan(
		&i.ID,
		&i.BackupJobID,
		&i.Store,
		&i.Namespace,
		&i.Mode,
		&i.Schedule,
		&i.Comment,
		&i.SpotConfig,
		&i.LastRunUpid,
		&i.LastSuccessfulUpid,
		&i.LastRunStatus,
		&i.RetryCount,
		&i.Retry,
		&i.RetryInterval,
		&i.CreatedAt,
		&i.LastRunStarttime,
		&i.LastRunEndtime,
		&i.LastSuccessfulEndtime,
		&i.RunOnBackupComplete,
		&i.PendingSince,
		&i.TargetMode,
		&i.Recursive,
		&i.NotificationMode,
	)
	return i, err
}

const getVerificationResults = `-- name: GetVerificationResults :many
SELECT id, verification_job_id, upid, snapshot, snapshot_time, total_files, verified_files, failed_files, skipped_files, status, started_at, completed_at, details, total_population
FROM verification_results
WHERE verification_job_id = ?
ORDER BY started_at DESC
`

func (q *Queries) GetVerificationResults(ctx context.Context, verificationJobID string) ([]VerificationResult, error) {
	rows, err := q.db.QueryContext(ctx, getVerificationResults, verificationJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationResult{}
	for rows.Next() {
		var i VerificationResult
		if err := rows.Scan(
			&i.ID,
			&i.VerificationJobID,
			&i.Upid,
			&i.Snapshot,
			&i.SnapshotTime,
			&i.TotalFiles,
			&i.VerifiedFiles,
			&i.FailedFiles,
			&i.SkippedFiles,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Details,
			&i.TotalPopulation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVerificationJobs = `-- name: ListAllVerificationJobs :many
SELECT id, backup_job_id, store, namespace, mode, schedule, comment, spot_config, last_run_upid, last_successful_upid, last_run_status, retry_count, retry, retry_interval, created_at, last_run_starttime, last_run_endtime, last_successful_endtime, run_on_backup_complete, pending_since, target_mode, "recursive", notification_mode
FROM verification_jobs
ORDER BY id
`

func (q *Queries) ListAllVerificationJobs(ctx context.Context) ([]VerificationJob, error) {
	rows, err := q.db.QueryContext(ctx, listAllVerificationJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationJob{}
	for rows.Next() {
		var i VerificationJob
		if err := rows.Scan(
			&i.ID,
			&i.BackupJobID,
			&i.Store,
			&i.Namespace,
			&i.Mode,
			&i.Schedule,
			&i.Comment,
			&i.SpotConfig,
			&i.LastRunUpid,
			&i.LastSuccessfulUpid,
			&i.LastRunStatus,
			&i.RetryCount,
			&i.Retry,
			&i.RetryInterval,
			&i.CreatedAt,
			&i.LastRunStarttime,
			&i.LastRunEndtime,
			&i.LastSuccessfulEndtime,
			&i.RunOnBackupComplete,
			&i.PendingSince,
			&i.TargetMode,
			&i.Recursive,
			&i.NotificationMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVerificationResultStatus = `-- name: MarkVerificationResultStatus :exec
UPDATE verification_results
SET status = ?, completed_at = ?
WHERE id = ?
`

type MarkVerificationResultStatusParams struct {
	Status      sql.NullString `json:"status"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
	ID          int64          `json:"id"`
}

func (q *Queries) MarkVerificationResultStatus(ctx context.Context, arg MarkVerificationResultStatusParams) error {
	_, err := q.db.ExecContext(ctx, markVerificationResultStatus, arg.Status, arg.CompletedAt, arg.ID)
	return err
}

const updateVerificationJob = `-- name: UpdateVerificationJob :exec
UPDATE verification_jobs
SET backup_job_id = ?, store = ?, namespace = ?, mode = ?, schedule = ?,
    comment = ?, spot_config = ?, last_run_upid = ?, last_successful_upid = ?,
    last_run_status = ?, retry_count = ?, retry = ?, retry_interval = ?,
    last_run_starttime = ?, last_run_endtime = ?, last_successful_endtime = ?,
    run_on_backup_complete = ?, pending_since = ?, notification_mode = ?
WHERE id = ?
`

type UpdateVerificationJobParams struct {
	BackupJobID           string         `json:"backup_job_id"`
	Store                 string         `json:"store"`
	Namespace             sql.NullString `json:"namespace"`
	Mode                  string         `json:"mode"`
	Schedule              sql.NullString `json:"schedule"`
	Comment               sql.NullString `json:"comment"`
	SpotConfig            sql.NullString `json:"spot_config"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	Retry                 sql.NullInt64  `json:"retry"`
	RetryInterval         sql.NullInt64  `json:"retry_interval"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	RunOnBackupComplete   sql.NullInt64  `json:"run_on_backup_complete"`
	PendingSince          sql.NullInt64  `json:"pending_since"`
	NotificationMode      sql.NullString `json:"notification_mode"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateVerificationJob(ctx context.Context, arg UpdateVerificationJobParams) error {
	_, err := q.db.ExecContext(ctx, updateVerificationJob,
		arg.BackupJobID,
		arg.Store,
		arg.Namespace,
		arg.Mode,
		arg.Schedule,
		arg.Comment,
		arg.SpotConfig,
		arg.LastRunUpid,
		arg.LastSuccessfulUpid,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.Retry,
		arg.RetryInterval,
		arg.LastRunStarttime,
		arg.LastRunEndtime,
		arg.LastSuccessfulEndtime,
		arg.RunOnBackupComplete,
		arg.PendingSince,
		arg.NotificationMode,
		arg.ID,
	)
	return err
}

const updateVerificationResult = `-- name: UpdateVerificationResult :exec
UPDATE verification_results
SET upid = ?, total_files = ?, verified_files = ?, failed_files = ?,
    skipped_files = ?, status = ?, completed_at = ?, details = ?,
    total_population = ?
WHERE id = ?
`

type UpdateVerificationResultParams struct {
	Upid            sql.NullString `json:"upid"`
	TotalFiles      sql.NullInt64  `json:"total_files"`
	VerifiedFiles   sql.NullInt64  `json:"verified_files"`
	FailedFiles     sql.NullInt64  `json:"failed_files"`
	SkippedFiles    sql.NullInt64  `json:"skipped_files"`
	Status          sql.NullString `json:"status"`
	CompletedAt     sql.NullInt64  `json:"completed_at"`
	Details         sql.NullString `json:"details"`
	TotalPopulation int64          `json:"total_population"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateVerificationResult(ctx context.Context, arg UpdateVerificationResultParams) error {
	_, err := q.db.ExecContext(ctx, updateVerificationResult,
		arg.Upid,
		arg.TotalFiles,
		arg.VerifiedFiles,
		arg.FailedFiles,
		arg.SkippedFiles,
		arg.Status,
		arg.CompletedAt,
		arg.Details,
		arg.TotalPopulation,
		arg.ID,
	)
	return err
}

const verificationJobExists = `-- name: VerificationJobExists :one
SELECT 1 FROM verification_jobs WHERE id = ? LIMIT 1
`

func (q *Queries) VerificationJobExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, verificationJobExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
