// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_engine.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cancelPendingWorkflowExecution = `-- name: CancelPendingWorkflowExecution :execrows
UPDATE job_executions
SET state = 'canceled', finished_at = ?, lease_owner = NULL, lease_until = NULL
WHERE id = ? AND state = 'pending' AND cancel_requested = 1
`

type CancelPendingWorkflowExecutionParams struct {
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) CancelPendingWorkflowExecution(ctx context.Context, arg CancelPendingWorkflowExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelPendingWorkflowExecution, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const checkpointWorkflowActivity = `-- name: CheckpointWorkflowActivity :execrows
UPDATE job_execution_activities
SET checkpoint = ?
WHERE execution_id = ? AND name = ? AND state = 'running'
`

type CheckpointWorkflowActivityParams struct {
	Checkpoint  sql.NullString `json:"checkpoint"`
	ExecutionID string         `json:"execution_id"`
	Name        string         `json:"name"`
}

func (q *Queries) CheckpointWorkflowActivity(ctx context.Context, arg CheckpointWorkflowActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, checkpointWorkflowActivity, arg.Checkpoint, arg.ExecutionID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimWorkflowExecution = `-- name: ClaimWorkflowExecution :execrows
UPDATE job_executions
SET state = 'running', attempt = attempt + 1, lease_owner = ?, lease_until = ?,
    started_at = COALESCE(started_at, ?)
WHERE id = ? AND state = 'pending' AND cancel_requested = 0 AND run_at <= ?
`

type ClaimWorkflowExecutionParams struct {
	LeaseOwner sql.NullString `json:"lease_owner"`
	LeaseUntil sql.NullInt64  `json:"lease_until"`
	StartedAt  sql.NullInt64  `json:"started_at"`
	ID         string         `json:"id"`
	RunAt      int64          `json:"run_at"`
}

func (q *Queries) ClaimWorkflowExecution(ctx context.Context, arg ClaimWorkflowExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimWorkflowExecution,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.StartedAt,
		arg.ID,
		arg.RunAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeWorkflowActivity = `-- name: CompleteWorkflowActivity :execrows
UPDATE job_execution_activities
SET state = 'completed', result = ?, completed_at = ?
WHERE execution_id = ? AND name = ? AND state = 'running'
`

type CompleteWorkflowActivityParams struct {
	Result      sql.NullString `json:"result"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
	ExecutionID string         `json:"execution_id"`
	Name        string         `json:"name"`
}

func (q *Queries) CompleteWorkflowActivity(ctx context.Context, arg CompleteWorkflowActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeWorkflowActivity,
		arg.Result,
		arg.CompletedAt,
		arg.ExecutionID,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createWorkflowActivity = `-- name: CreateWorkflowActivity :execrows
INSERT INTO job_execution_activities (
    execution_id, name, input_hash, state, created_at
) VALUES (?, ?, ?, 'pending', ?)
ON CONFLICT(execution_id, name) DO NOTHING
`

type CreateWorkflowActivityParams struct {
	ExecutionID string `json:"execution_id"`
	Name        string `json:"name"`
	InputHash   string `json:"input_hash"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateWorkflowActivity(ctx context.Context, arg CreateWorkflowActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createWorkflowActivity,
		arg.ExecutionID,
		arg.Name,
		arg.InputHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createWorkflowExecution = `-- name: CreateWorkflowExecution :exec
INSERT INTO job_executions (
    id, kind, definition_id, trigger, dedupe_key, payload, state, attempt,
    max_attempts, retry_initial_seconds, retry_max_seconds, run_at, created_at,
    parent_execution_id
) VALUES (?, ?, ?, ?, ?, ?, 'pending', 0, ?, ?, ?, ?, ?, ?)
`

type CreateWorkflowExecutionParams struct {
	ID                  string         `json:"id"`
	Kind                string         `json:"kind"`
	DefinitionID        string         `json:"definition_id"`
	Trigger             string         `json:"trigger"`
	DedupeKey           string         `json:"dedupe_key"`
	Payload             string         `json:"payload"`
	MaxAttempts         int64          `json:"max_attempts"`
	RetryInitialSeconds int64          `json:"retry_initial_seconds"`
	RetryMaxSeconds     int64          `json:"retry_max_seconds"`
	RunAt               int64          `json:"run_at"`
	CreatedAt           int64          `json:"created_at"`
	ParentExecutionID   sql.NullString `json:"parent_execution_id"`
}

func (q *Queries) CreateWorkflowExecution(ctx context.Context, arg CreateWorkflowExecutionParams) error {
	_, err := q.db.ExecContext(ctx, createWorkflowExecution,
		arg.ID,
		arg.Kind,
		arg.DefinitionID,
		arg.Trigger,
		arg.DedupeKey,
		arg.Payload,
		arg.MaxAttempts,
		arg.RetryInitialSeconds,
		arg.RetryMaxSeconds,
		arg.RunAt,
		arg.CreatedAt,
		arg.ParentExecutionID,
	)
	return err
}

const createWorkflowExecutionEvent = `-- name: CreateWorkflowExecutionEvent :exec
INSERT INTO job_execution_events (execution_id, event_type, data, created_at)
VALUES (?, ?, ?, ?)
`

type CreateWorkflowExecutionEventParams struct {
	ExecutionID string `json:"execution_id"`
	EventType   string `json:"event_type"`
	Data        string `json:"data"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateWorkflowExecutionEvent(ctx context.Context, arg CreateWorkflowExecutionEventParams) error {
	_, err := q.db.ExecContext(ctx, createWorkflowExecutionEvent,
		arg.ExecutionID,
		arg.EventType,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const createWorkflowExecutionResource = `-- name: CreateWorkflowExecutionResource :exec
INSERT INTO job_execution_resources (execution_id, resource_key) VALUES (?, ?)
`

type CreateWorkflowExecutionResourceParams struct {
	ExecutionID string `json:"execution_id"`
	ResourceKey string `json:"resource_key"`
}

func (q *Queries) CreateWorkflowExecutionResource(ctx context.Context, arg CreateWorkflowExecutionResourceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkflowExecutionResource, arg.ExecutionID, arg.ResourceKey)
	return err
}

const createWorkflowResourceLock = `-- name: CreateWorkflowResourceLock :execrows
INSERT INTO job_resource_locks (resource_key, execution_id, lease_until)
VALUES (?, ?, ?)
ON CONFLICT(resource_key) DO UPDATE SET
    execution_id = excluded.execution_id,
    lease_until = excluded.lease_until
WHERE job_resource_locks.execution_id = excluded.execution_id
`

type CreateWorkflowResourceLockParams struct {
	ResourceKey string `json:"resource_key"`
	ExecutionID string `json:"execution_id"`
	LeaseUntil  int64  `json:"lease_until"`
}

func (q *Queries) CreateWorkflowResourceLock(ctx context.Context, arg CreateWorkflowResourceLockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createWorkflowResourceLock, arg.ResourceKey, arg.ExecutionID, arg.LeaseUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const delayWorkflowExecution = `-- name: DelayWorkflowExecution :exec
UPDATE job_executions SET run_at = ? WHERE id = ? AND state = 'pending'
`

type DelayWorkflowExecutionParams struct {
	RunAt int64  `json:"run_at"`
	ID    string `json:"id"`
}

func (q *Queries) DelayWorkflowExecution(ctx context.Context, arg DelayWorkflowExecutionParams) error {
	_, err := q.db.ExecContext(ctx, delayWorkflowExecution, arg.RunAt, arg.ID)
	return err
}

const deleteExpiredWorkflowResourceLocks = `-- name: DeleteExpiredWorkflowResourceLocks :exec
DELETE FROM job_resource_locks WHERE lease_until < ?
`

func (q *Queries) DeleteExpiredWorkflowResourceLocks(ctx context.Context, leaseUntil int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredWorkflowResourceLocks, leaseUntil)
	return err
}

const deleteWorkflowResourceLocks = `-- name: DeleteWorkflowResourceLocks :exec
DELETE FROM job_resource_locks WHERE execution_id = ?
`

func (q *Queries) DeleteWorkflowResourceLocks(ctx context.Context, executionID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowResourceLocks, executionID)
	return err
}

const failWorkflowActivity = `-- name: FailWorkflowActivity :execrows
UPDATE job_execution_activities
SET state = 'pending', last_error = ?
WHERE execution_id = ? AND name = ? AND state = 'running'
`

type FailWorkflowActivityParams struct {
	LastError   sql.NullString `json:"last_error"`
	ExecutionID string         `json:"execution_id"`
	Name        string         `json:"name"`
}

func (q *Queries) FailWorkflowActivity(ctx context.Context, arg FailWorkflowActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failWorkflowActivity, arg.LastError, arg.ExecutionID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishWorkflowExecution = `-- name: FinishWorkflowExecution :execrows
UPDATE job_executions
SET state = ?, run_at = ?, lease_owner = NULL, lease_until = NULL,
    last_error = ?, finished_at = ?
WHERE id = ? AND state = 'running' AND lease_owner = ?
`

type FinishWorkflowExecutionParams struct {
	State      string         `json:"state"`
	RunAt      int64          `json:"run_at"`
	LastError  sql.NullString `json:"last_error"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
	ID         string         `json:"id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
}

func (q *Queries) FinishWorkflowExecution(ctx context.Context, arg FinishWorkflowExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishWorkflowExecution,
		arg.State,
		arg.RunAt,
		arg.LastError,
		arg.FinishedAt,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWorkflowActivity = `-- name: GetWorkflowActivity :one
SELECT execution_id, name, input_hash, state, attempt, result, checkpoint,
    last_error, created_at, started_at, completed_at
FROM job_execution_activities
WHERE execution_id = ? AND name = ?
`

type GetWorkflowActivityParams struct {
	ExecutionID string `json:"execution_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetWorkflowActivity(ctx context.Context, arg GetWorkflowActivityParams) (JobExecutionActivity, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowActivity, arg.ExecutionID, arg.Name)
	var i JobExecutionActivity
	err := row.Scan(
		&i.ExecutionID,
		&i.Name,
		&i.InputHash,
		&i.State,
		&i.Attempt,
		&i.Result,
		&i.Checkpoint,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkflowExecution = `-- name: GetWorkflowExecution :one
SELECT id, kind, definition_id, trigger, dedupe_key, payload, state, attempt,
    max_attempts, retry_initial_seconds, retry_max_seconds, run_at, lease_owner,
    lease_until, cancel_requested, last_error, parent_execution_id, created_at,
    started_at, finished_at
FROM job_executions
WHERE id = ?
`

func (q *Queries) GetWorkflowExecution(ctx context.Context, id string) (JobExecution, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowExecution, id)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DefinitionID,
		&i.Trigger,
		&i.DedupeKey,
		&i.Payload,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryInitialSeconds,
		&i.RetryMaxSeconds,
		&i.RunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CancelRequested,
		&i.LastError,
		&i.ParentExecutionID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getWorkflowExecutionByDedupeKey = `-- name: GetWorkflowExecutionByDedupeKey :one
SELECT id, kind, definition_id, trigger, dedupe_key, payload, state, attempt,
    max_attempts, retry_initial_seconds, retry_max_seconds, run_at, lease_owner,
    lease_until, cancel_requested, last_error, parent_execution_id, created_at,
    started_at, finished_at
FROM job_executions
WHERE dedupe_key = ?
`

func (q *Queries) GetWorkflowExecutionByDedupeKey(ctx context.Context, dedupeKey string) (JobExecution, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowExecutionByDedupeKey, dedupeKey)
	var i JobExecution
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DefinitionID,
		&i.Trigger,
		&i.DedupeKey,
		&i.Payload,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RetryInitialSeconds,
		&i.RetryMaxSeconds,
		&i.RunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CancelRequested,
		&i.LastError,
		&i.ParentExecutionID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listClaimableWorkflowExecutionIDs = `-- name: ListClaimableWorkflowExecutionIDs :many
SELECT id
FROM job_executions
WHERE state = 'pending' AND cancel_requested = 0 AND run_at <= ?
ORDER BY run_at, created_at
LIMIT 32
`

func (q *Queries) ListClaimableWorkflowExecutionIDs(ctx context.Context, runAt int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listClaimableWorkflowExecutionIDs, runAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowExecutionEvents = `-- name: ListWorkflowExecutionEvents :many
SELECT sequence, execution_id, event_type, data, created_at
FROM job_execution_events
WHERE execution_id = ?
ORDER BY sequence
`

func (q *Queries) ListWorkflowExecutionEvents(ctx context.Context, executionID string) ([]JobExecutionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowExecutionEvents, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobExecutionEvent{}
	for rows.Next() {
		var i JobExecutionEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.ExecutionID,
			&i.EventType,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowExecutionResources = `-- name: ListWorkflowExecutionResources :many
SELECT resource_key FROM job_execution_resources WHERE execution_id = ? ORDER BY resource_key
`

func (q *Queries) ListWorkflowExecutionResources(ctx context.Context, executionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowExecutionResources, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var resource_key string
		if err := rows.Scan(&resource_key); err != nil {
			return nil, err
		}
		items = append(items, resource_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseWorkflowExecutionClaim = `-- name: ReleaseWorkflowExecutionClaim :exec
UPDATE job_executions
SET state = 'pending', lease_owner = NULL, lease_until = NULL, run_at = ?
WHERE id = ? AND state = 'running' AND lease_owner = ?
`

type ReleaseWorkflowExecutionClaimParams struct {
	RunAt      int64          `json:"run_at"`
	ID         string         `json:"id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
}

func (q *Queries) ReleaseWorkflowExecutionClaim(ctx context.Context, arg ReleaseWorkflowExecutionClaimParams) error {
	_, err := q.db.ExecContext(ctx, releaseWorkflowExecutionClaim, arg.RunAt, arg.ID, arg.LeaseOwner)
	return err
}

const renewWorkflowExecutionLease = `-- name: RenewWorkflowExecutionLease :execrows
UPDATE job_executions SET lease_until = ?
WHERE id = ? AND state = 'running' AND lease_owner = ?
`

type RenewWorkflowExecutionLeaseParams struct {
	LeaseUntil sql.NullInt64  `json:"lease_until"`
	ID         string         `json:"id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
}

func (q *Queries) RenewWorkflowExecutionLease(ctx context.Context, arg RenewWorkflowExecutionLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewWorkflowExecutionLease, arg.LeaseUntil, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewWorkflowResourceLocks = `-- name: RenewWorkflowResourceLocks :exec
UPDATE job_resource_locks SET lease_until = ? WHERE execution_id = ?
`

type RenewWorkflowResourceLocksParams struct {
	LeaseUntil  int64  `json:"lease_until"`
	ExecutionID string `json:"execution_id"`
}

func (q *Queries) RenewWorkflowResourceLocks(ctx context.Context, arg RenewWorkflowResourceLocksParams) error {
	_, err := q.db.ExecContext(ctx, renewWorkflowResourceLocks, arg.LeaseUntil, arg.ExecutionID)
	return err
}

const requestWorkflowExecutionCancellation = `-- name: RequestWorkflowExecutionCancellation :execrows
UPDATE job_executions SET cancel_requested = 1
WHERE id = ? AND state IN ('pending', 'running')
`

func (q *Queries) RequestWorkflowExecutionCancellation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestWorkflowExecutionCancellation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueExpiredWorkflowExecutions = `-- name: RequeueExpiredWorkflowExecutions :exec
UPDATE job_executions
SET state = 'pending', lease_owner = NULL, lease_until = NULL, run_at = ?
WHERE state = 'running' AND lease_until < ? AND cancel_requested = 0
`

type RequeueExpiredWorkflowExecutionsParams struct {
	RunAt      int64         `json:"run_at"`
	LeaseUntil sql.NullInt64 `json:"lease_until"`
}

func (q *Queries) RequeueExpiredWorkflowExecutions(ctx context.Context, arg RequeueExpiredWorkflowExecutionsParams) error {
	_, err := q.db.ExecContext(ctx, requeueExpiredWorkflowExecutions, arg.RunAt, arg.LeaseUntil)
	return err
}

const startWorkflowActivity = `-- name: StartWorkflowActivity :execrows
UPDATE job_execution_activities
SET state = 'running', attempt = attempt + 1, started_at = ?, last_error = NULL
WHERE execution_id = ? AND name = ? AND state IN ('pending', 'running')
`

type StartWorkflowActivityParams struct {
	StartedAt   sql.NullInt64 `json:"started_at"`
	ExecutionID string        `json:"execution_id"`
	Name        string        `json:"name"`
}

func (q *Queries) StartWorkflowActivity(ctx context.Context, arg StartWorkflowActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startWorkflowActivity, arg.StartedAt, arg.ExecutionID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
