version: 2

project_name: pbs-plus

before:
  hooks:
    - go mod tidy

builds:
  # Server build (Linux)
  - id: server
    main: ./cmd/pbs_plus
    binary: pbs-plus
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X 'main.Version=dev-{{.ShortCommit}}'
    hooks:
      post:
        - upx "{{ .Path }}"

  # Linux Agent
  # - id: linux-agent
  #   main: ./cmd/linux_agent
  #   binary: pbs-plus-agent
  #   goos:
  #     - linux
  #   goarch:
  #     - amd64
  #   ldflags:
  #     - -X 'main.Version=dev-{{.ShortCommit}}'
  #   hooks:
  #     post:
  #       - upx "{{ .Path }}"

  # Windows Agent
  - id: windows-agent
    main: ./cmd/windows_agent
    binary: pbs-plus-agent
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -H=windowsgui
      - -X 'main.Version=dev-{{.ShortCommit}}'
    hooks:
      post:
        - upx "{{ .Path }}"

  # Windows Updater
  - id: windows-updater
    main: ./cmd/windows_updater
    binary: pbs-plus-updater
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -H=windowsgui
    hooks:
      post:
        - upx "{{ .Path }}"

archives:
  - id: server
    builds:
      - server
    name_template: "{{ .ProjectName }}_dev_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

  - id: windows-binaries
    builds:
      - windows-agent
      - windows-updater
    name_template: "{{ .ProjectName }}_dev_{{ .Os }}_{{ .Arch }}"
    format: zip

nfpms:
  - id: server-deb
    builds:
      - server
    package_name: "{{ .ProjectName }}"
    vendor: Son Roy Almerol
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    maintainer: Son Roy Almerol <github@snry.me>
    description: >
      PBS Plus is a project focused on extending Proxmox Backup Server (PBS) 
      with advanced features to create a more competitive backup solution (DEV BUILD)
    license: MIT
    formats:
      - deb
    dependencies:
      - proxmox-backup-server (>= 3.2)
      - proxmox-backup-client (>= 3.2.5)
      - fuse3
    contents:
      - src: ./build/package/server/debian/lib/systemd/system/pbs-plus.service
        dst: /lib/systemd/system/pbs-plus.service
        type: config
    scripts:
      postinstall: ./build/package/server/debian/DEBIAN/postinst
    overrides:
      deb:
        file_name_template: "{{ .PackageName }}_dev_{{ .Arch }}"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  name_template: "Dev Build - {{ .Date }}"
  draft: false
  prerelease: true
  mode: replace
  skip_upload: false

snapshot:
  name_template: "dev-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
