version: 2

project_name: pbs-plus

before:
  hooks:
    - go mod tidy
#    - |
#      # Generate UpgradeCode (should be consistent across versions)
#      if [ -z "$UPGRADE_CODE" ]; then
#        export UPGRADE_CODE=$(echo "pbs-plus-agent-upgrade" | sha256sum | cut -c1-32 | sed 's/\(........\)\(....\)\(....\)\(....\)\(............\)/\1-\2-\3-\4-\5/')
#      fi
#    - |
#      # Generate ProductCode (should be unique per version)
#      export PRODUCT_CODE=$(echo "pbs-plus-agent-{{.Version}}" | sha256sum | cut -c1-32 | sed 's/\(........\)\(....\)\(....\)\(....\)\(............\)/\1-\2-\3-\4-\5/')

#binary_signs:
#  - id: gpg-sign
#    cmd: gpg
#    args:
#      - "--batch"
#      - "--local-user"
#      - "{{ .Env.GPG_FINGERPRINT }}"
#      - "--output"
#      - "${signature}"
#      - "--detach-sign"
#      - "${artifact}"
#    artifacts: binary
#    signature: "${artifact}.sig"
#    output: true

builds:
  # Server build (Linux)
  - id: server
    main: ./cmd/pbs_plus
    binary: pbs-plus
    env:
      - GOEXPERIMENT=greenteagc
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X 'main.Version=v{{.Version}}'
    hooks:
      post:
        - upx "{{ .Path }}"

  # ESXi NFS Backup
  - id: esxi-nfs-backup
    main: ./cmd/esxi_nfs_backup
    binary: esxi-nfs-backup
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=greenteagc
    ldflags:
      - -X 'main.Version=v{{.Version}}'
      - -extld gcc
      - -extldflags "-static"
    flags:
      - -tags=netgo,osusergo
      - -installsuffix=netgo
    hooks:
      post:
        - upx "{{ .Path }}"

  # Linux Agent
  - id: linux-agent
    main: ./cmd/unix_agent
    binary: pbs-plus-agent
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=greenteagc
    ldflags:
      - -X 'main.Version=v{{.Version}}'
      - -extld gcc
      - -extldflags "-static"
    flags:
      - -tags=netgo,osusergo
      - -installsuffix=netgo
    hooks:
      post:
        - upx "{{ .Path }}"

  # Linux Updater
  - id: linux-updater
    main: ./cmd/unix_updater
    binary: pbs-plus-updater
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=greenteagc
    ldflags:
      - -extld gcc
      - -extldflags "-static"
    flags:
      - -tags=netgo,osusergo
      - -installsuffix=netgo
    hooks:
      post:
        - upx "{{ .Path }}"

  # BSD Agent
  - id: freebsd-agent
    main: ./cmd/unix_agent
    binary: pbs-plus-agent
    env:
      - GOEXPERIMENT=greenteagc
    goos:
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'main.Version=v{{.Version}}'

  # Windows Agent
  - id: windows-agent
    main: ./cmd/windows_agent
    binary: pbs-plus-agent
    env:
      - GOEXPERIMENT=greenteagc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -H=windowsgui
      - -X 'main.Version=v{{.Version}}'
    hooks:
      post:
        - upx "{{ .Path }}"

  # Windows Updater
  - id: windows-updater
    main: ./cmd/windows_updater
    binary: pbs-plus-updater
    env:
      - GOEXPERIMENT=greenteagc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -H=windowsgui
    hooks:
      post:
        - upx "{{ .Path }}"

archives:
  - id: server
    ids:
      - server
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

  - id: esxi-nfs-backup
    ids:
      - esxi-nfs-backup
    name_template: "esxi-nfs-backup-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

  - id: linux-agent
    ids:
      - linux-agent
    name_template: "{{ .ProjectName }}-agent-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

  - id: linux-updater
    ids:
      - linux-updater
    name_template: "{{ .ProjectName }}-updater-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

  - id: freebsd-agent
    ids:
      - freebsd-agent
    name_template: "{{ .ProjectName }}-agent-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

  - id: windows-agent
    ids:
      - windows-agent
    name_template: "{{ .ProjectName }}-agent-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

  - id: windows-updater
    ids:
      - windows-updater
    name_template: "{{ .ProjectName }}-updater-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

checksum:
  name_template: "{{ .ArtifactName }}.{{ .Algorithm }}"
  algorithm: md5
  split: true

#msi:
#  - id: windows-agent-msi
#    ids:
#      - windows-agent
#      - windows-updater
#    name: "PBS Plus Agent"
#    wxs: "./build/package/windows_agent/agent.wxs"
#    extra_files:
#      - source: "./build/package/windows_agent/install.ps1"
#        target: "install.ps1"
#      - source: "./build/package/windows_agent/uninstall.ps1"
#        target: "uninstall.ps1"

nfpms:
  - id: server-deb
    ids:
      - server
      - esxi-nfs-backup
    package_name: "{{ .ProjectName }}"
    vendor: Son Roy Almerol
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    maintainer: Son Roy Almerol <github@snry.me>
    description: >
      PBS Plus is a project focused on extending Proxmox Backup Server (PBS) 
      with advanced features to create a more competitive backup solution
    license: MIT
    formats:
      - deb
    dependencies:
      - proxmox-backup-server (>= 3.2)
      - proxmox-backup-client (>= 3.2.5)
      - fuse3
    contents:
      - src: ./build/package/server/pbs-plus.service
        dst: /lib/systemd/system/pbs-plus.service
        type: config
    scripts:
      postinstall: ./build/package/server/postinst
    overrides:
      deb:
        file_name_template: "{{ .PackageName }}-v{{ .Version }}-{{ .Arch }}"

  - id: linux-agent-deb
    ids:
      - linux-agent
      - linux-updater
    package_name: "{{ .ProjectName }}-agent"
    vendor: Son Roy Almerol
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    maintainer: Son Roy Almerol <github@snry.me>
    description: >
      PBS Plus Agent - Linux agent for PBS Plus backup solution
    license: MIT
    formats:
      - deb
    contents:
      - src: ./build/package/linux_agent/deb/pbs-plus-agent.service
        dst: /lib/systemd/system/pbs-plus-agent.service
        type: config
      - src: ./build/package/linux_agent/deb/pbs-plus-updater.service
        dst: /lib/systemd/system/pbs-plus-updater.service
        type: config
    scripts:
      postinstall: ./build/package/linux_agent/deb/postinst
    overrides:
      deb:
        file_name_template: "{{ .PackageName }}-v{{ .Version }}-{{ .Arch }}"

  - id: linux-agent-rpm
    ids:
      - linux-agent
      - linux-updater
    package_name: "{{ .ProjectName }}-agent"
    vendor: Son Roy Almerol
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    maintainer: Son Roy Almerol <github@snry.me>
    description: >
      PBS Plus Agent - Linux agent for PBS Plus backup solution
    license: MIT
    formats:
      - rpm
    contents:
      - src: ./build/package/linux_agent/rpm/pbs-plus-agent.service
        dst: /usr/lib/systemd/system/pbs-plus-agent.service
        type: config
      - src: ./build/package/linux_agent/rpm/pbs-plus-updater.service
        dst: /usr/lib/systemd/system/pbs-plus-updater.service
        type: config
    scripts:
      postinstall: ./build/package/linux_agent/rpm/postinst
    overrides:
      rpm:
        file_name_template: "{{ .PackageName }}-v{{ .Version }}-{{ .Arch }}"

  - id: linux-agent-apk
    ids:
      - linux-agent
      - linux-updater
    package_name: "{{ .ProjectName }}-agent"
    vendor: Son Roy Almerol
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY }}"
    maintainer: Son Roy Almerol <github@snry.me>
    description: >
      PBS Plus Agent - Linux agent for PBS Plus backup solution
    license: MIT
    formats:
      - apk
    contents:
      - src: ./build/package/linux_agent/apk/pbs-plus-agent
        dst: /etc/init.d/pbs-plus-agent
        type: config
        file_info:
          mode: 0755
      - src: ./build/package/linux_agent/apk/pbs-plus-updater
        dst: /etc/init.d/pbs-plus-updater
        type: config
        file_info:
          mode: 0755
    scripts:
      postinstall: ./build/package/linux_agent/apk/postinst
    overrides:
      apk:
        file_name_template: "{{ .PackageName }}-v{{ .Version }}-{{ .Arch }}"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  name_template: "PBS Plus {{ .Version }}"
  draft: false
  prerelease: auto
  mode: replace

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
