// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backups.sql

package corequery

import (
	"context"
	"database/sql"
)

const backupExists = `-- name: BackupExists :one
SELECT 1 FROM backups WHERE id = ? LIMIT 1
`

func (q *Queries) BackupExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, backupExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const backupGroupMigrationCompleted = `-- name: BackupGroupMigrationCompleted :one
SELECT EXISTS(
	SELECT 1 FROM backup_group_migrations WHERE backup_id = ?
)
`

func (q *Queries) BackupGroupMigrationCompleted(ctx context.Context, backupID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, backupGroupMigrationCompleted, backupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const completeBackupGroupMigration = `-- name: CompleteBackupGroupMigration :exec
INSERT INTO backup_group_migrations (backup_id)
VALUES (?)
ON CONFLICT(backup_id) DO NOTHING
`

func (q *Queries) CompleteBackupGroupMigration(ctx context.Context, backupID string) error {
	_, err := q.db.ExecContext(ctx, completeBackupGroupMigration, backupID)
	return err
}

const countBackups = `-- name: CountBackups :one
SELECT COUNT(*) FROM backups
`

func (q *Queries) CountBackups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBackups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBackup = `-- name: CreateBackup :exec
INSERT INTO backups (
    id, store, mode, source_mode, read_mode, target, subpath, schedule, comment,
    notification_mode, namespace, current_pid, last_run_upid, last_successful_upid,
    retry, retry_interval, max_dir_entries, pre_script, post_script,
    include_xattr, legacy_xattr, expand_archives, last_run_status, retry_count,
    last_run_state, last_run_starttime, last_run_endtime, last_successful_endtime, duration
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBackupParams struct {
	ID                    string         `json:"id"`
	Store                 string         `json:"store"`
	Mode                  interface{}    `json:"mode"`
	SourceMode            interface{}    `json:"source_mode"`
	ReadMode              interface{}    `json:"read_mode"`
	Target                string         `json:"target"`
	Subpath               sql.NullString `json:"subpath"`
	Schedule              sql.NullString `json:"schedule"`
	Comment               sql.NullString `json:"comment"`
	NotificationMode      sql.NullString `json:"notification_mode"`
	Namespace             sql.NullString `json:"namespace"`
	CurrentPid            sql.NullString `json:"current_pid"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	Retry                 sql.NullInt64  `json:"retry"`
	RetryInterval         sql.NullInt64  `json:"retry_interval"`
	MaxDirEntries         sql.NullInt64  `json:"max_dir_entries"`
	PreScript             string         `json:"pre_script"`
	PostScript            string         `json:"post_script"`
	IncludeXattr          sql.NullInt64  `json:"include_xattr"`
	LegacyXattr           sql.NullInt64  `json:"legacy_xattr"`
	ExpandArchives        sql.NullInt64  `json:"expand_archives"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	LastRunState          sql.NullString `json:"last_run_state"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	Duration              sql.NullInt64  `json:"duration"`
}

func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) error {
	_, err := q.db.ExecContext(ctx, createBackup,
		arg.ID,
		arg.Store,
		arg.Mode,
		arg.SourceMode,
		arg.ReadMode,
		arg.Target,
		arg.Subpath,
		arg.Schedule,
		arg.Comment,
		arg.NotificationMode,
		arg.Namespace,
		arg.CurrentPid,
		arg.LastRunUpid,
		arg.LastSuccessfulUpid,
		arg.Retry,
		arg.RetryInterval,
		arg.MaxDirEntries,
		arg.PreScript,
		arg.PostScript,
		arg.IncludeXattr,
		arg.LegacyXattr,
		arg.ExpandArchives,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.LastRunState,
		arg.LastRunStarttime,
		arg.LastRunEndtime,
		arg.LastSuccessfulEndtime,
		arg.Duration,
	)
	return err
}

const deleteBackup = `-- name: DeleteBackup :execrows
DELETE FROM backups WHERE id = ?
`

func (q *Queries) DeleteBackup(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBackup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBackupDatabaseOptions = `-- name: DeleteBackupDatabaseOptions :exec
DELETE FROM backup_database_options WHERE backup_id = ?
`

func (q *Queries) DeleteBackupDatabaseOptions(ctx context.Context, backupID string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupDatabaseOptions, backupID)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT
    j.id, j.store, j.mode, j.source_mode, j.read_mode, j.target, j.subpath,
    j.schedule, j.comment, j.notification_mode, j.namespace, j.current_pid,
    j.last_run_upid, j.last_successful_upid, j.retry, j.retry_interval,
    j.max_dir_entries, j.pre_script, j.post_script, j.include_xattr, j.legacy_xattr,
    j.expand_archives,
    j.last_run_status, j.retry_count,
    j.last_run_state, j.last_run_starttime, j.last_run_endtime,
    j.last_successful_endtime, j.duration,
    COALESCE(dbo.scope, '') AS database_scope,
    COALESCE(dbo.database_name, '') AS database_name,
    COALESCE(dbo.client_family, '') AS database_client_family,
    COALESCE(dbo.client_dir, '') AS database_client_dir,
    t.name, t.target_type, t.mount_script,
    COALESCE(f.access, '') AS filesystem_access,
    COALESCE(f.path, s.url, '') AS path,
    f.agent_host, f.volume_id, f.volume_type, f.volume_name,
    f.volume_fs, f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
    f.volume_total, f.volume_used, f.volume_free,
    COALESCE(p.host, m.host, '') AS database_host,
    COALESCE(p.port, m.port, 0) AS database_port,
    COALESCE(p.username, m.username, '') AS database_username,
    COALESCE(p.ssl_mode, m.tls_mode, '') AS database_tls_mode,
    COALESCE(p.ca_certificate, m.ca_certificate, '') AS database_ca_certificate,
    COALESCE(p.default_client_dir, m.default_client_dir, '') AS database_default_client_dir,
    COALESCE(m.variant, '') AS database_variant,
    COALESCE(m.default_client_family, '') AS database_default_client_family,
    ah.name as agent_name, ah.ip as agent_ip, ah.auth as agent_auth,
    ah.token_used as agent_token_used, ah.os as agent_os
FROM backups j
LEFT JOIN backup_database_options dbo ON dbo.backup_id = j.id
LEFT JOIN targets t ON j.target = t.name
LEFT JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN target_s3 s ON s.target_name = t.name
LEFT JOIN target_postgresql p ON p.target_name = t.name
LEFT JOIN target_mysql m ON m.target_name = t.name
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
WHERE j.id = ?
LIMIT 1
`

type GetBackupRow struct {
	ID                          string         `json:"id"`
	Store                       string         `json:"store"`
	Mode                        interface{}    `json:"mode"`
	SourceMode                  interface{}    `json:"source_mode"`
	ReadMode                    interface{}    `json:"read_mode"`
	Target                      string         `json:"target"`
	Subpath                     sql.NullString `json:"subpath"`
	Schedule                    sql.NullString `json:"schedule"`
	Comment                     sql.NullString `json:"comment"`
	NotificationMode            sql.NullString `json:"notification_mode"`
	Namespace                   sql.NullString `json:"namespace"`
	CurrentPid                  sql.NullString `json:"current_pid"`
	LastRunUpid                 sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid          sql.NullString `json:"last_successful_upid"`
	Retry                       sql.NullInt64  `json:"retry"`
	RetryInterval               sql.NullInt64  `json:"retry_interval"`
	MaxDirEntries               sql.NullInt64  `json:"max_dir_entries"`
	PreScript                   string         `json:"pre_script"`
	PostScript                  string         `json:"post_script"`
	IncludeXattr                sql.NullInt64  `json:"include_xattr"`
	LegacyXattr                 sql.NullInt64  `json:"legacy_xattr"`
	ExpandArchives              sql.NullInt64  `json:"expand_archives"`
	LastRunStatus               sql.NullInt64  `json:"last_run_status"`
	RetryCount                  sql.NullInt64  `json:"retry_count"`
	LastRunState                sql.NullString `json:"last_run_state"`
	LastRunStarttime            sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime              sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime       sql.NullInt64  `json:"last_successful_endtime"`
	Duration                    sql.NullInt64  `json:"duration"`
	DatabaseScope               string         `json:"database_scope"`
	DatabaseName                string         `json:"database_name"`
	DatabaseClientFamily        string         `json:"database_client_family"`
	DatabaseClientDir           string         `json:"database_client_dir"`
	Name                        sql.NullString `json:"name"`
	TargetType                  sql.NullString `json:"target_type"`
	MountScript                 sql.NullString `json:"mount_script"`
	FilesystemAccess            string         `json:"filesystem_access"`
	Path                        string         `json:"path"`
	AgentHost                   sql.NullString `json:"agent_host"`
	VolumeID                    sql.NullString `json:"volume_id"`
	VolumeType                  sql.NullString `json:"volume_type"`
	VolumeName                  sql.NullString `json:"volume_name"`
	VolumeFs                    sql.NullString `json:"volume_fs"`
	VolumeTotalBytes            sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes             sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes             sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal                 sql.NullString `json:"volume_total"`
	VolumeUsed                  sql.NullString `json:"volume_used"`
	VolumeFree                  sql.NullString `json:"volume_free"`
	DatabaseHost                string         `json:"database_host"`
	DatabasePort                int64          `json:"database_port"`
	DatabaseUsername            string         `json:"database_username"`
	DatabaseTlsMode             string         `json:"database_tls_mode"`
	DatabaseCaCertificate       string         `json:"database_ca_certificate"`
	DatabaseDefaultClientDir    string         `json:"database_default_client_dir"`
	DatabaseVariant             string         `json:"database_variant"`
	DatabaseDefaultClientFamily string         `json:"database_default_client_family"`
	AgentName                   sql.NullString `json:"agent_name"`
	AgentIp                     sql.NullString `json:"agent_ip"`
	AgentAuth                   sql.NullString `json:"agent_auth"`
	AgentTokenUsed              sql.NullString `json:"agent_token_used"`
	AgentOs                     sql.NullString `json:"agent_os"`
}

func (q *Queries) GetBackup(ctx context.Context, id string) (GetBackupRow, error) {
	row := q.db.QueryRowContext(ctx, getBackup, id)
	var i GetBackupRow
	err := row.Scan(
		&i.ID,
		&i.Store,
		&i.Mode,
		&i.SourceMode,
		&i.ReadMode,
		&i.Target,
		&i.Subpath,
		&i.Schedule,
		&i.Comment,
		&i.NotificationMode,
		&i.Namespace,
		&i.CurrentPid,
		&i.LastRunUpid,
		&i.LastSuccessfulUpid,
		&i.Retry,
		&i.RetryInterval,
		&i.MaxDirEntries,
		&i.PreScript,
		&i.PostScript,
		&i.IncludeXattr,
		&i.LegacyXattr,
		&i.ExpandArchives,
		&i.LastRunStatus,
		&i.RetryCount,
		&i.LastRunState,
		&i.LastRunStarttime,
		&i.LastRunEndtime,
		&i.LastSuccessfulEndtime,
		&i.Duration,
		&i.DatabaseScope,
		&i.DatabaseName,
		&i.DatabaseClientFamily,
		&i.DatabaseClientDir,
		&i.Name,
		&i.TargetType,
		&i.MountScript,
		&i.FilesystemAccess,
		&i.Path,
		&i.AgentHost,
		&i.VolumeID,
		&i.VolumeType,
		&i.VolumeName,
		&i.VolumeFs,
		&i.VolumeTotalBytes,
		&i.VolumeUsedBytes,
		&i.VolumeFreeBytes,
		&i.VolumeTotal,
		&i.VolumeUsed,
		&i.VolumeFree,
		&i.DatabaseHost,
		&i.DatabasePort,
		&i.DatabaseUsername,
		&i.DatabaseTlsMode,
		&i.DatabaseCaCertificate,
		&i.DatabaseDefaultClientDir,
		&i.DatabaseVariant,
		&i.DatabaseDefaultClientFamily,
		&i.AgentName,
		&i.AgentIp,
		&i.AgentAuth,
		&i.AgentTokenUsed,
		&i.AgentOs,
	)
	return i, err
}

const listAllBackups = `-- name: ListAllBackups :many
SELECT
    j.id, j.store, j.mode, j.source_mode, j.read_mode, j.target, j.subpath,
    j.schedule, j.comment, j.notification_mode, j.namespace, j.current_pid,
    j.last_run_upid, j.last_successful_upid, j.retry, j.retry_interval,
    j.max_dir_entries, j.pre_script, j.post_script, j.include_xattr, j.legacy_xattr,
    j.expand_archives,
    j.last_run_status, j.retry_count,
    j.last_run_state, j.last_run_starttime, j.last_run_endtime,
    j.last_successful_endtime, j.duration,
    COALESCE(dbo.scope, '') AS database_scope,
    COALESCE(dbo.database_name, '') AS database_name,
    COALESCE(dbo.client_family, '') AS database_client_family,
    COALESCE(dbo.client_dir, '') AS database_client_dir,
    t.name, t.target_type, t.mount_script,
    COALESCE(f.access, '') AS filesystem_access,
    COALESCE(f.path, s.url, '') AS path,
    f.agent_host, f.volume_id, f.volume_type, f.volume_name,
    f.volume_fs, f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
    f.volume_total, f.volume_used, f.volume_free,
    COALESCE(p.host, m.host, '') AS database_host,
    COALESCE(p.port, m.port, 0) AS database_port,
    COALESCE(p.username, m.username, '') AS database_username,
    COALESCE(p.ssl_mode, m.tls_mode, '') AS database_tls_mode,
    COALESCE(p.ca_certificate, m.ca_certificate, '') AS database_ca_certificate,
    COALESCE(p.default_client_dir, m.default_client_dir, '') AS database_default_client_dir,
    COALESCE(m.variant, '') AS database_variant,
    COALESCE(m.default_client_family, '') AS database_default_client_family,
    ah.name as agent_name, ah.ip as agent_ip, ah.auth as agent_auth,
    ah.token_used as agent_token_used, ah.os as agent_os
FROM backups j
LEFT JOIN backup_database_options dbo ON dbo.backup_id = j.id
LEFT JOIN targets t ON j.target = t.name
LEFT JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN target_s3 s ON s.target_name = t.name
LEFT JOIN target_postgresql p ON p.target_name = t.name
LEFT JOIN target_mysql m ON m.target_name = t.name
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
ORDER BY j.id
`

type ListAllBackupsRow struct {
	ID                          string         `json:"id"`
	Store                       string         `json:"store"`
	Mode                        interface{}    `json:"mode"`
	SourceMode                  interface{}    `json:"source_mode"`
	ReadMode                    interface{}    `json:"read_mode"`
	Target                      string         `json:"target"`
	Subpath                     sql.NullString `json:"subpath"`
	Schedule                    sql.NullString `json:"schedule"`
	Comment                     sql.NullString `json:"comment"`
	NotificationMode            sql.NullString `json:"notification_mode"`
	Namespace                   sql.NullString `json:"namespace"`
	CurrentPid                  sql.NullString `json:"current_pid"`
	LastRunUpid                 sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid          sql.NullString `json:"last_successful_upid"`
	Retry                       sql.NullInt64  `json:"retry"`
	RetryInterval               sql.NullInt64  `json:"retry_interval"`
	MaxDirEntries               sql.NullInt64  `json:"max_dir_entries"`
	PreScript                   string         `json:"pre_script"`
	PostScript                  string         `json:"post_script"`
	IncludeXattr                sql.NullInt64  `json:"include_xattr"`
	LegacyXattr                 sql.NullInt64  `json:"legacy_xattr"`
	ExpandArchives              sql.NullInt64  `json:"expand_archives"`
	LastRunStatus               sql.NullInt64  `json:"last_run_status"`
	RetryCount                  sql.NullInt64  `json:"retry_count"`
	LastRunState                sql.NullString `json:"last_run_state"`
	LastRunStarttime            sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime              sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime       sql.NullInt64  `json:"last_successful_endtime"`
	Duration                    sql.NullInt64  `json:"duration"`
	DatabaseScope               string         `json:"database_scope"`
	DatabaseName                string         `json:"database_name"`
	DatabaseClientFamily        string         `json:"database_client_family"`
	DatabaseClientDir           string         `json:"database_client_dir"`
	Name                        sql.NullString `json:"name"`
	TargetType                  sql.NullString `json:"target_type"`
	MountScript                 sql.NullString `json:"mount_script"`
	FilesystemAccess            string         `json:"filesystem_access"`
	Path                        string         `json:"path"`
	AgentHost                   sql.NullString `json:"agent_host"`
	VolumeID                    sql.NullString `json:"volume_id"`
	VolumeType                  sql.NullString `json:"volume_type"`
	VolumeName                  sql.NullString `json:"volume_name"`
	VolumeFs                    sql.NullString `json:"volume_fs"`
	VolumeTotalBytes            sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes             sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes             sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal                 sql.NullString `json:"volume_total"`
	VolumeUsed                  sql.NullString `json:"volume_used"`
	VolumeFree                  sql.NullString `json:"volume_free"`
	DatabaseHost                string         `json:"database_host"`
	DatabasePort                int64          `json:"database_port"`
	DatabaseUsername            string         `json:"database_username"`
	DatabaseTlsMode             string         `json:"database_tls_mode"`
	DatabaseCaCertificate       string         `json:"database_ca_certificate"`
	DatabaseDefaultClientDir    string         `json:"database_default_client_dir"`
	DatabaseVariant             string         `json:"database_variant"`
	DatabaseDefaultClientFamily string         `json:"database_default_client_family"`
	AgentName                   sql.NullString `json:"agent_name"`
	AgentIp                     sql.NullString `json:"agent_ip"`
	AgentAuth                   sql.NullString `json:"agent_auth"`
	AgentTokenUsed              sql.NullString `json:"agent_token_used"`
	AgentOs                     sql.NullString `json:"agent_os"`
}

func (q *Queries) ListAllBackups(ctx context.Context) ([]ListAllBackupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBackupsRow{}
	for rows.Next() {
		var i ListAllBackupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Store,
			&i.Mode,
			&i.SourceMode,
			&i.ReadMode,
			&i.Target,
			&i.Subpath,
			&i.Schedule,
			&i.Comment,
			&i.NotificationMode,
			&i.Namespace,
			&i.CurrentPid,
			&i.LastRunUpid,
			&i.LastSuccessfulUpid,
			&i.Retry,
			&i.RetryInterval,
			&i.MaxDirEntries,
			&i.PreScript,
			&i.PostScript,
			&i.IncludeXattr,
			&i.LegacyXattr,
			&i.ExpandArchives,
			&i.LastRunStatus,
			&i.RetryCount,
			&i.LastRunState,
			&i.LastRunStarttime,
			&i.LastRunEndtime,
			&i.LastSuccessfulEndtime,
			&i.Duration,
			&i.DatabaseScope,
			&i.DatabaseName,
			&i.DatabaseClientFamily,
			&i.DatabaseClientDir,
			&i.Name,
			&i.TargetType,
			&i.MountScript,
			&i.FilesystemAccess,
			&i.Path,
			&i.AgentHost,
			&i.VolumeID,
			&i.VolumeType,
			&i.VolumeName,
			&i.VolumeFs,
			&i.VolumeTotalBytes,
			&i.VolumeUsedBytes,
			&i.VolumeFreeBytes,
			&i.VolumeTotal,
			&i.VolumeUsed,
			&i.VolumeFree,
			&i.DatabaseHost,
			&i.DatabasePort,
			&i.DatabaseUsername,
			&i.DatabaseTlsMode,
			&i.DatabaseCaCertificate,
			&i.DatabaseDefaultClientDir,
			&i.DatabaseVariant,
			&i.DatabaseDefaultClientFamily,
			&i.AgentName,
			&i.AgentIp,
			&i.AgentAuth,
			&i.AgentTokenUsed,
			&i.AgentOs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBackup = `-- name: UpdateBackup :exec
UPDATE backups
SET store = ?, mode = ?, source_mode = ?, read_mode = ?, target = ?,
    subpath = ?, schedule = ?, comment = ?, notification_mode = ?,
    namespace = ?, current_pid = ?, last_run_upid = ?, retry = ?,
    retry_interval = ?, last_successful_upid = ?, pre_script = ?,
    post_script = ?, max_dir_entries = ?, include_xattr = ?, legacy_xattr = ?,
    expand_archives = ?,
    last_run_status = ?, retry_count = ?,
    last_run_state = ?, last_run_starttime = ?, last_run_endtime = ?,
    last_successful_endtime = ?, duration = ?
WHERE id = ?
`

type UpdateBackupParams struct {
	Store                 string         `json:"store"`
	Mode                  interface{}    `json:"mode"`
	SourceMode            interface{}    `json:"source_mode"`
	ReadMode              interface{}    `json:"read_mode"`
	Target                string         `json:"target"`
	Subpath               sql.NullString `json:"subpath"`
	Schedule              sql.NullString `json:"schedule"`
	Comment               sql.NullString `json:"comment"`
	NotificationMode      sql.NullString `json:"notification_mode"`
	Namespace             sql.NullString `json:"namespace"`
	CurrentPid            sql.NullString `json:"current_pid"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	Retry                 sql.NullInt64  `json:"retry"`
	RetryInterval         sql.NullInt64  `json:"retry_interval"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	PreScript             string         `json:"pre_script"`
	PostScript            string         `json:"post_script"`
	MaxDirEntries         sql.NullInt64  `json:"max_dir_entries"`
	IncludeXattr          sql.NullInt64  `json:"include_xattr"`
	LegacyXattr           sql.NullInt64  `json:"legacy_xattr"`
	ExpandArchives        sql.NullInt64  `json:"expand_archives"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	LastRunState          sql.NullString `json:"last_run_state"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	Duration              sql.NullInt64  `json:"duration"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateBackup(ctx context.Context, arg UpdateBackupParams) error {
	_, err := q.db.ExecContext(ctx, updateBackup,
		arg.Store,
		arg.Mode,
		arg.SourceMode,
		arg.ReadMode,
		arg.Target,
		arg.Subpath,
		arg.Schedule,
		arg.Comment,
		arg.NotificationMode,
		arg.Namespace,
		arg.CurrentPid,
		arg.LastRunUpid,
		arg.Retry,
		arg.RetryInterval,
		arg.LastSuccessfulUpid,
		arg.PreScript,
		arg.PostScript,
		arg.MaxDirEntries,
		arg.IncludeXattr,
		arg.LegacyXattr,
		arg.ExpandArchives,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.LastRunState,
		arg.LastRunStarttime,
		arg.LastRunEndtime,
		arg.LastSuccessfulEndtime,
		arg.Duration,
		arg.ID,
	)
	return err
}

const updateBackupHistory = `-- name: UpdateBackupHistory :exec
UPDATE backups
SET current_pid = ?, last_run_upid = ?, last_successful_upid = ?,
    last_run_status = ?, retry_count = ?, last_run_state = ?,
    last_run_starttime = ?, last_run_endtime = ?,
    last_successful_endtime = ?, duration = ?
WHERE id = ?
`

type UpdateBackupHistoryParams struct {
	CurrentPid            sql.NullString `json:"current_pid"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	LastRunState          sql.NullString `json:"last_run_state"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	Duration              sql.NullInt64  `json:"duration"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateBackupHistory(ctx context.Context, arg UpdateBackupHistoryParams) error {
	_, err := q.db.ExecContext(ctx, updateBackupHistory,
		arg.CurrentPid,
		arg.LastRunUpid,
		arg.LastSuccessfulUpid,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.LastRunState,
		arg.LastRunStarttime,
		arg.LastRunEndtime,
		arg.LastSuccessfulEndtime,
		arg.Duration,
		arg.ID,
	)
	return err
}

const updateBackupNamespace = `-- name: UpdateBackupNamespace :exec
UPDATE backups SET namespace = ? WHERE id = ?
`

type UpdateBackupNamespaceParams struct {
	Namespace sql.NullString `json:"namespace"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateBackupNamespace(ctx context.Context, arg UpdateBackupNamespaceParams) error {
	_, err := q.db.ExecContext(ctx, updateBackupNamespace, arg.Namespace, arg.ID)
	return err
}

const upsertBackupDatabaseOptions = `-- name: UpsertBackupDatabaseOptions :exec
INSERT INTO backup_database_options (
    backup_id, scope, database_name, client_family, client_dir
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(backup_id) DO UPDATE SET
    scope = excluded.scope,
    database_name = excluded.database_name,
    client_family = excluded.client_family,
    client_dir = excluded.client_dir
`

type UpsertBackupDatabaseOptionsParams struct {
	BackupID     string `json:"backup_id"`
	Scope        string `json:"scope"`
	DatabaseName string `json:"database_name"`
	ClientFamily string `json:"client_family"`
	ClientDir    string `json:"client_dir"`
}

func (q *Queries) UpsertBackupDatabaseOptions(ctx context.Context, arg UpsertBackupDatabaseOptionsParams) error {
	_, err := q.db.ExecContext(ctx, upsertBackupDatabaseOptions,
		arg.BackupID,
		arg.Scope,
		arg.DatabaseName,
		arg.ClientFamily,
		arg.ClientDir,
	)
	return err
}
