// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_targets.sql

package corequery

import (
	"context"
)

const archivePluginTargetConfig = `-- name: ArchivePluginTargetConfig :exec
INSERT INTO plugin_target_config_history (
    target_name, plugin_id, plugin_version, schema_version, config, migrated_at
)
SELECT target_name, plugin_id, plugin_version, schema_version, config, ?1
FROM plugin_target_configs AS config
WHERE config.target_name = ?2
`

type ArchivePluginTargetConfigParams struct {
	MigratedAt int64  `json:"migrated_at"`
	TargetName string `json:"target_name"`
}

func (q *Queries) ArchivePluginTargetConfig(ctx context.Context, arg ArchivePluginTargetConfigParams) error {
	_, err := q.db.ExecContext(ctx, archivePluginTargetConfig, arg.MigratedAt, arg.TargetName)
	return err
}

const createPluginTargetConfig = `-- name: CreatePluginTargetConfig :exec
INSERT INTO plugin_target_configs (
    target_name, plugin_id, plugin_version, target_type, schema_version, config, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePluginTargetConfigParams struct {
	TargetName    string `json:"target_name"`
	PluginID      string `json:"plugin_id"`
	PluginVersion string `json:"plugin_version"`
	TargetType    string `json:"target_type"`
	SchemaVersion int64  `json:"schema_version"`
	Config        []byte `json:"config"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) CreatePluginTargetConfig(ctx context.Context, arg CreatePluginTargetConfigParams) error {
	_, err := q.db.ExecContext(ctx, createPluginTargetConfig,
		arg.TargetName,
		arg.PluginID,
		arg.PluginVersion,
		arg.TargetType,
		arg.SchemaVersion,
		arg.Config,
		arg.UpdatedAt,
	)
	return err
}

const deletePluginTargetSecret = `-- name: DeletePluginTargetSecret :execrows
DELETE FROM plugin_target_secrets
WHERE target_name = ?1 AND field_key = ?2
`

type DeletePluginTargetSecretParams struct {
	TargetName string `json:"target_name"`
	FieldKey   string `json:"field_key"`
}

func (q *Queries) DeletePluginTargetSecret(ctx context.Context, arg DeletePluginTargetSecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePluginTargetSecret, arg.TargetName, arg.FieldKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPluginTargetConfig = `-- name: GetPluginTargetConfig :one
SELECT target_name, plugin_id, plugin_version, target_type, schema_version, config, updated_at
FROM plugin_target_configs
WHERE target_name = ?
`

func (q *Queries) GetPluginTargetConfig(ctx context.Context, targetName string) (PluginTargetConfig, error) {
	row := q.db.QueryRowContext(ctx, getPluginTargetConfig, targetName)
	var i PluginTargetConfig
	err := row.Scan(
		&i.TargetName,
		&i.PluginID,
		&i.PluginVersion,
		&i.TargetType,
		&i.SchemaVersion,
		&i.Config,
		&i.UpdatedAt,
	)
	return i, err
}

const listPluginTargetConfigHistory = `-- name: ListPluginTargetConfigHistory :many
SELECT id, target_name, plugin_id, plugin_version, schema_version, config, migrated_at
FROM plugin_target_config_history
WHERE target_name = ?
ORDER BY migrated_at DESC, id DESC
`

func (q *Queries) ListPluginTargetConfigHistory(ctx context.Context, targetName string) ([]PluginTargetConfigHistory, error) {
	rows, err := q.db.QueryContext(ctx, listPluginTargetConfigHistory, targetName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginTargetConfigHistory{}
	for rows.Next() {
		var i PluginTargetConfigHistory
		if err := rows.Scan(
			&i.ID,
			&i.TargetName,
			&i.PluginID,
			&i.PluginVersion,
			&i.SchemaVersion,
			&i.Config,
			&i.MigratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginTargetConfigsByPlugin = `-- name: ListPluginTargetConfigsByPlugin :many
SELECT target_name, plugin_id, plugin_version, target_type, schema_version, config, updated_at
FROM plugin_target_configs
WHERE plugin_id = ?
ORDER BY target_name
`

func (q *Queries) ListPluginTargetConfigsByPlugin(ctx context.Context, pluginID string) ([]PluginTargetConfig, error) {
	rows, err := q.db.QueryContext(ctx, listPluginTargetConfigsByPlugin, pluginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginTargetConfig{}
	for rows.Next() {
		var i PluginTargetConfig
		if err := rows.Scan(
			&i.TargetName,
			&i.PluginID,
			&i.PluginVersion,
			&i.TargetType,
			&i.SchemaVersion,
			&i.Config,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginTargetSecrets = `-- name: ListPluginTargetSecrets :many
SELECT field_key, encrypted_value
FROM plugin_target_secrets
WHERE target_name = ?
ORDER BY field_key
`

type ListPluginTargetSecretsRow struct {
	FieldKey       string `json:"field_key"`
	EncryptedValue string `json:"encrypted_value"`
}

func (q *Queries) ListPluginTargetSecrets(ctx context.Context, targetName string) ([]ListPluginTargetSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPluginTargetSecrets, targetName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPluginTargetSecretsRow{}
	for rows.Next() {
		var i ListPluginTargetSecretsRow
		if err := rows.Scan(&i.FieldKey, &i.EncryptedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migratePluginTargetConfig = `-- name: MigratePluginTargetConfig :execrows
UPDATE plugin_target_configs
SET plugin_version = ?1,
    schema_version = ?2,
    config = ?3,
    updated_at = ?4
WHERE target_name = ?5
  AND plugin_id = ?6
  AND plugin_version = ?7
  AND schema_version = ?8
  AND config = ?9
  AND updated_at = ?10
`

type MigratePluginTargetConfigParams struct {
	ToPluginVersion   string `json:"to_plugin_version"`
	ToSchemaVersion   int64  `json:"to_schema_version"`
	ToConfig          []byte `json:"to_config"`
	ToUpdatedAt       int64  `json:"to_updated_at"`
	TargetName        string `json:"target_name"`
	PluginID          string `json:"plugin_id"`
	FromPluginVersion string `json:"from_plugin_version"`
	FromSchemaVersion int64  `json:"from_schema_version"`
	FromConfig        []byte `json:"from_config"`
	FromUpdatedAt     int64  `json:"from_updated_at"`
}

func (q *Queries) MigratePluginTargetConfig(ctx context.Context, arg MigratePluginTargetConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, migratePluginTargetConfig,
		arg.ToPluginVersion,
		arg.ToSchemaVersion,
		arg.ToConfig,
		arg.ToUpdatedAt,
		arg.TargetName,
		arg.PluginID,
		arg.FromPluginVersion,
		arg.FromSchemaVersion,
		arg.FromConfig,
		arg.FromUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginTargetConfig = `-- name: UpdatePluginTargetConfig :execrows
UPDATE plugin_target_configs
SET plugin_version = ?1,
    target_type = ?2,
    schema_version = ?3,
    config = ?4,
    updated_at = ?5
WHERE target_name = ?6
  AND plugin_id = ?7
`

type UpdatePluginTargetConfigParams struct {
	PluginVersion string `json:"plugin_version"`
	TargetType    string `json:"target_type"`
	SchemaVersion int64  `json:"schema_version"`
	Config        []byte `json:"config"`
	UpdatedAt     int64  `json:"updated_at"`
	TargetName    string `json:"target_name"`
	PluginID      string `json:"plugin_id"`
}

func (q *Queries) UpdatePluginTargetConfig(ctx context.Context, arg UpdatePluginTargetConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginTargetConfig,
		arg.PluginVersion,
		arg.TargetType,
		arg.SchemaVersion,
		arg.Config,
		arg.UpdatedAt,
		arg.TargetName,
		arg.PluginID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPluginTargetSecret = `-- name: UpsertPluginTargetSecret :exec
INSERT INTO plugin_target_secrets (target_name, field_key, encrypted_value)
VALUES (?, ?, ?)
ON CONFLICT(target_name, field_key) DO UPDATE SET encrypted_value = excluded.encrypted_value
`

type UpsertPluginTargetSecretParams struct {
	TargetName     string `json:"target_name"`
	FieldKey       string `json:"field_key"`
	EncryptedValue string `json:"encrypted_value"`
}

func (q *Queries) UpsertPluginTargetSecret(ctx context.Context, arg UpsertPluginTargetSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertPluginTargetSecret, arg.TargetName, arg.FieldKey, arg.EncryptedValue)
	return err
}
