// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_job_options.sql

package corequery

import (
	"context"
)

const archiveBackupPluginOptions = `-- name: ArchiveBackupPluginOptions :exec
INSERT INTO backup_plugin_option_history (
    backup_id, plugin_id, plugin_version, schema_version, options, migrated_at
)
SELECT backup_id, plugin_id, plugin_version, schema_version, options, ?1
FROM backup_plugin_options AS option
WHERE option.backup_id = ?2
`

type ArchiveBackupPluginOptionsParams struct {
	MigratedAt int64  `json:"migrated_at"`
	BackupID   string `json:"backup_id"`
}

func (q *Queries) ArchiveBackupPluginOptions(ctx context.Context, arg ArchiveBackupPluginOptionsParams) error {
	_, err := q.db.ExecContext(ctx, archiveBackupPluginOptions, arg.MigratedAt, arg.BackupID)
	return err
}

const archiveRestorePluginOptions = `-- name: ArchiveRestorePluginOptions :exec
INSERT INTO restore_plugin_option_history (
    restore_id, plugin_id, plugin_version, schema_version, options, migrated_at
)
SELECT restore_id, plugin_id, plugin_version, schema_version, options, ?1
FROM restore_plugin_options AS option
WHERE option.restore_id = ?2
`

type ArchiveRestorePluginOptionsParams struct {
	MigratedAt int64  `json:"migrated_at"`
	RestoreID  string `json:"restore_id"`
}

func (q *Queries) ArchiveRestorePluginOptions(ctx context.Context, arg ArchiveRestorePluginOptionsParams) error {
	_, err := q.db.ExecContext(ctx, archiveRestorePluginOptions, arg.MigratedAt, arg.RestoreID)
	return err
}

const deleteBackupPluginOptions = `-- name: DeleteBackupPluginOptions :exec
DELETE FROM backup_plugin_options
WHERE backup_id = ?
`

func (q *Queries) DeleteBackupPluginOptions(ctx context.Context, backupID string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupPluginOptions, backupID)
	return err
}

const deleteRestorePluginOptions = `-- name: DeleteRestorePluginOptions :exec
DELETE FROM restore_plugin_options
WHERE restore_id = ?
`

func (q *Queries) DeleteRestorePluginOptions(ctx context.Context, restoreID string) error {
	_, err := q.db.ExecContext(ctx, deleteRestorePluginOptions, restoreID)
	return err
}

const getBackupPluginOptions = `-- name: GetBackupPluginOptions :one
SELECT backup_id, plugin_id, plugin_version, schema_version, options, updated_at
FROM backup_plugin_options
WHERE backup_id = ?
`

func (q *Queries) GetBackupPluginOptions(ctx context.Context, backupID string) (BackupPluginOption, error) {
	row := q.db.QueryRowContext(ctx, getBackupPluginOptions, backupID)
	var i BackupPluginOption
	err := row.Scan(
		&i.BackupID,
		&i.PluginID,
		&i.PluginVersion,
		&i.SchemaVersion,
		&i.Options,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestorePluginOptions = `-- name: GetRestorePluginOptions :one
SELECT restore_id, plugin_id, plugin_version, schema_version, options, updated_at
FROM restore_plugin_options
WHERE restore_id = ?
`

func (q *Queries) GetRestorePluginOptions(ctx context.Context, restoreID string) (RestorePluginOption, error) {
	row := q.db.QueryRowContext(ctx, getRestorePluginOptions, restoreID)
	var i RestorePluginOption
	err := row.Scan(
		&i.RestoreID,
		&i.PluginID,
		&i.PluginVersion,
		&i.SchemaVersion,
		&i.Options,
		&i.UpdatedAt,
	)
	return i, err
}

const listBackupPluginOptionHistory = `-- name: ListBackupPluginOptionHistory :many
SELECT id, backup_id, plugin_id, plugin_version, schema_version, options, migrated_at
FROM backup_plugin_option_history
WHERE backup_id = ?
ORDER BY migrated_at DESC, id DESC
`

func (q *Queries) ListBackupPluginOptionHistory(ctx context.Context, backupID string) ([]BackupPluginOptionHistory, error) {
	rows, err := q.db.QueryContext(ctx, listBackupPluginOptionHistory, backupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupPluginOptionHistory{}
	for rows.Next() {
		var i BackupPluginOptionHistory
		if err := rows.Scan(
			&i.ID,
			&i.BackupID,
			&i.PluginID,
			&i.PluginVersion,
			&i.SchemaVersion,
			&i.Options,
			&i.MigratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupPluginOptionsByPluginVersion = `-- name: ListBackupPluginOptionsByPluginVersion :many
SELECT backup_id, plugin_id, plugin_version, schema_version, options, updated_at
FROM backup_plugin_options
WHERE plugin_id = ?1 AND plugin_version = ?2
ORDER BY backup_id
`

type ListBackupPluginOptionsByPluginVersionParams struct {
	PluginID      string `json:"plugin_id"`
	PluginVersion string `json:"plugin_version"`
}

func (q *Queries) ListBackupPluginOptionsByPluginVersion(ctx context.Context, arg ListBackupPluginOptionsByPluginVersionParams) ([]BackupPluginOption, error) {
	rows, err := q.db.QueryContext(ctx, listBackupPluginOptionsByPluginVersion, arg.PluginID, arg.PluginVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupPluginOption{}
	for rows.Next() {
		var i BackupPluginOption
		if err := rows.Scan(
			&i.BackupID,
			&i.PluginID,
			&i.PluginVersion,
			&i.SchemaVersion,
			&i.Options,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestorePluginOptionHistory = `-- name: ListRestorePluginOptionHistory :many
SELECT id, restore_id, plugin_id, plugin_version, schema_version, options, migrated_at
FROM restore_plugin_option_history
WHERE restore_id = ?
ORDER BY migrated_at DESC, id DESC
`

func (q *Queries) ListRestorePluginOptionHistory(ctx context.Context, restoreID string) ([]RestorePluginOptionHistory, error) {
	rows, err := q.db.QueryContext(ctx, listRestorePluginOptionHistory, restoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RestorePluginOptionHistory{}
	for rows.Next() {
		var i RestorePluginOptionHistory
		if err := rows.Scan(
			&i.ID,
			&i.RestoreID,
			&i.PluginID,
			&i.PluginVersion,
			&i.SchemaVersion,
			&i.Options,
			&i.MigratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestorePluginOptionsByPluginVersion = `-- name: ListRestorePluginOptionsByPluginVersion :many
SELECT restore_id, plugin_id, plugin_version, schema_version, options, updated_at
FROM restore_plugin_options
WHERE plugin_id = ?1 AND plugin_version = ?2
ORDER BY restore_id
`

type ListRestorePluginOptionsByPluginVersionParams struct {
	PluginID      string `json:"plugin_id"`
	PluginVersion string `json:"plugin_version"`
}

func (q *Queries) ListRestorePluginOptionsByPluginVersion(ctx context.Context, arg ListRestorePluginOptionsByPluginVersionParams) ([]RestorePluginOption, error) {
	rows, err := q.db.QueryContext(ctx, listRestorePluginOptionsByPluginVersion, arg.PluginID, arg.PluginVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RestorePluginOption{}
	for rows.Next() {
		var i RestorePluginOption
		if err := rows.Scan(
			&i.RestoreID,
			&i.PluginID,
			&i.PluginVersion,
			&i.SchemaVersion,
			&i.Options,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBackupPluginOptions = `-- name: UpsertBackupPluginOptions :exec
INSERT INTO backup_plugin_options (
    backup_id, plugin_id, plugin_version, schema_version, options, updated_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(backup_id) DO UPDATE SET
    plugin_id = excluded.plugin_id,
    plugin_version = excluded.plugin_version,
    schema_version = excluded.schema_version,
    options = excluded.options,
    updated_at = excluded.updated_at
`

type UpsertBackupPluginOptionsParams struct {
	BackupID      string `json:"backup_id"`
	PluginID      string `json:"plugin_id"`
	PluginVersion string `json:"plugin_version"`
	SchemaVersion int64  `json:"schema_version"`
	Options       []byte `json:"options"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) UpsertBackupPluginOptions(ctx context.Context, arg UpsertBackupPluginOptionsParams) error {
	_, err := q.db.ExecContext(ctx, upsertBackupPluginOptions,
		arg.BackupID,
		arg.PluginID,
		arg.PluginVersion,
		arg.SchemaVersion,
		arg.Options,
		arg.UpdatedAt,
	)
	return err
}

const upsertRestorePluginOptions = `-- name: UpsertRestorePluginOptions :exec
INSERT INTO restore_plugin_options (
    restore_id, plugin_id, plugin_version, schema_version, options, updated_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(restore_id) DO UPDATE SET
    plugin_id = excluded.plugin_id,
    plugin_version = excluded.plugin_version,
    schema_version = excluded.schema_version,
    options = excluded.options,
    updated_at = excluded.updated_at
`

type UpsertRestorePluginOptionsParams struct {
	RestoreID     string `json:"restore_id"`
	PluginID      string `json:"plugin_id"`
	PluginVersion string `json:"plugin_version"`
	SchemaVersion int64  `json:"schema_version"`
	Options       []byte `json:"options"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) UpsertRestorePluginOptions(ctx context.Context, arg UpsertRestorePluginOptionsParams) error {
	_, err := q.db.ExecContext(ctx, upsertRestorePluginOptions,
		arg.RestoreID,
		arg.PluginID,
		arg.PluginVersion,
		arg.SchemaVersion,
		arg.Options,
		arg.UpdatedAt,
	)
	return err
}
