// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package corequery

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddJobToBatch(ctx context.Context, arg AddJobToBatchParams) error
	AgentHostExists(ctx context.Context, name string) (int64, error)
	BackupExists(ctx context.Context, id string) (int64, error)
	BackupGroupMigrationCompleted(ctx context.Context, backupID string) (int64, error)
	CompleteBackupGroupMigration(ctx context.Context, backupID string) error
	CountBackups(ctx context.Context) (int64, error)
	CountRestores(ctx context.Context) (int64, error)
	CreateAgentHost(ctx context.Context, arg CreateAgentHostParams) error
	CreateAlertExclusion(ctx context.Context, arg CreateAlertExclusionParams) error
	CreateBackup(ctx context.Context, arg CreateBackupParams) error
	CreateExclusion(ctx context.Context, arg CreateExclusionParams) error
	CreateNotificationBatch(ctx context.Context, arg CreateNotificationBatchParams) error
	CreateRestore(ctx context.Context, arg CreateRestoreParams) error
	CreateScript(ctx context.Context, arg CreateScriptParams) error
	CreateTarget(ctx context.Context, arg CreateTargetParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	CreateVerificationJob(ctx context.Context, arg CreateVerificationJobParams) error
	CreateVerificationResult(ctx context.Context, arg CreateVerificationResultParams) (sql.Result, error)
	DeleteAgentHost(ctx context.Context, name string) (int64, error)
	DeleteAlertExclusion(ctx context.Context, id int64) error
	DeleteAlertExclusionsByType(ctx context.Context, alertType string) error
	DeleteAlertSetting(ctx context.Context, name string) error
	DeleteBackup(ctx context.Context, id string) (int64, error)
	DeleteBackupDatabaseOptions(ctx context.Context, backupID string) error
	DeleteBackupExclusions(ctx context.Context, jobID string) error
	DeleteBatchResults(ctx context.Context, batchName string) error
	DeleteExclusion(ctx context.Context, arg DeleteExclusionParams) error
	DeleteNotificationBatch(ctx context.Context, name string) error
	DeleteRestore(ctx context.Context, id string) (int64, error)
	DeleteRestoreDatabaseOptions(ctx context.Context, restoreID string) error
	DeleteScript(ctx context.Context, path string) (int64, error)
	DeleteTarget(ctx context.Context, name string) (int64, error)
	DeleteTargetFilesystem(ctx context.Context, targetName string) error
	DeleteTargetMySQL(ctx context.Context, targetName string) error
	DeleteTargetPostgreSQL(ctx context.Context, targetName string) error
	DeleteTargetS3(ctx context.Context, targetName string) error
	DeleteToken(ctx context.Context, token string) error
	DeleteVerificationJob(ctx context.Context, id string) (int64, error)
	DeleteVerificationResults(ctx context.Context, verificationJobID string) (int64, error)
	GetAgentHost(ctx context.Context, name string) (AgentHost, error)
	GetAgentHostAuth(ctx context.Context, name string) (sql.NullString, error)
	GetAlertExclusion(ctx context.Context, id int64) (AlertExclusion, error)
	GetAlertExclusionsByType(ctx context.Context, arg GetAlertExclusionsByTypeParams) ([]AlertExclusion, error)
	GetAlertSetting(ctx context.Context, name string) (AlertSetting, error)
	GetBackup(ctx context.Context, id string) (GetBackupRow, error)
	GetBackupExclusions(ctx context.Context, jobID string) ([]Exclusion, error)
	GetBatchForJob(ctx context.Context, arg GetBatchForJobParams) (NotificationBatch, error)
	GetBatchJobsByBatch(ctx context.Context, batchName string) ([]NotificationBatchJob, error)
	GetBatchJobsByJobType(ctx context.Context, jobType string) ([]NotificationBatchJob, error)
	GetBatchResults(ctx context.Context, batchName string) ([]NotificationBatchResult, error)
	GetExclusion(ctx context.Context, arg GetExclusionParams) (Exclusion, error)
	GetLatestVerificationResult(ctx context.Context, verificationJobID string) (VerificationResult, error)
	GetNotificationBatch(ctx context.Context, name string) (NotificationBatch, error)
	GetRestore(ctx context.Context, id string) (GetRestoreRow, error)
	GetScript(ctx context.Context, path string) (GetScriptRow, error)
	GetTarget(ctx context.Context, name string) (GetTargetRow, error)
	GetTargetMySQLPassword(ctx context.Context, targetName string) (string, error)
	GetTargetPostgreSQLPassword(ctx context.Context, targetName string) (string, error)
	GetTargetS3Secret(ctx context.Context, targetName string) (string, error)
	GetToken(ctx context.Context, token string) (Token, error)
	GetVerificationJob(ctx context.Context, id string) (VerificationJob, error)
	GetVerificationResults(ctx context.Context, verificationJobID string) ([]VerificationResult, error)
	ListAlertExclusions(ctx context.Context, alertType string) ([]AlertExclusion, error)
	ListAlertSettings(ctx context.Context) ([]AlertSetting, error)
	ListAllAgentHosts(ctx context.Context) ([]AgentHost, error)
	ListAllAlertExclusions(ctx context.Context) ([]AlertExclusion, error)
	ListAllBackupExclusions(ctx context.Context) ([]ListAllBackupExclusionsRow, error)
	ListAllBackups(ctx context.Context) ([]ListAllBackupsRow, error)
	ListAllRestores(ctx context.Context) ([]ListAllRestoresRow, error)
	ListAllScripts(ctx context.Context) ([]ListAllScriptsRow, error)
	ListAllTargets(ctx context.Context) ([]ListAllTargetsRow, error)
	ListAllTokens(ctx context.Context) ([]Token, error)
	ListAllTokensWithDetails(ctx context.Context) ([]ListAllTokensWithDetailsRow, error)
	ListAllVerificationJobs(ctx context.Context) ([]VerificationJob, error)
	ListBatchJobs(ctx context.Context) ([]NotificationBatchJob, error)
	ListBatchesWithResults(ctx context.Context) ([]string, error)
	ListGlobalExclusions(ctx context.Context) ([]ListGlobalExclusionsRow, error)
	ListNonRevokedTokens(ctx context.Context) ([]Token, error)
	ListNotificationBatches(ctx context.Context) ([]NotificationBatch, error)
	ListTargetsByAgentHost(ctx context.Context, agentHost sql.NullString) ([]ListTargetsByAgentHostRow, error)
	MarkVerificationResultStatus(ctx context.Context, arg MarkVerificationResultStatusParams) error
	RemoveJobFromAllBatches(ctx context.Context, arg RemoveJobFromAllBatchesParams) error
	RemoveJobFromBatch(ctx context.Context, arg RemoveJobFromBatchParams) error
	RemoveJobsByBatch(ctx context.Context, batchName string) error
	RestoreExists(ctx context.Context, id string) (int64, error)
	RevokeToken(ctx context.Context, token string) error
	ScriptExists(ctx context.Context, path string) (int64, error)
	TargetExists(ctx context.Context, name string) (int64, error)
	UpdateAgentHost(ctx context.Context, arg UpdateAgentHostParams) error
	UpdateAlertLastSent(ctx context.Context, arg UpdateAlertLastSentParams) error
	UpdateBackup(ctx context.Context, arg UpdateBackupParams) error
	UpdateBackupHistory(ctx context.Context, arg UpdateBackupHistoryParams) error
	UpdateBackupNamespace(ctx context.Context, arg UpdateBackupNamespaceParams) error
	UpdateExclusion(ctx context.Context, arg UpdateExclusionParams) (int64, error)
	UpdateNotificationBatch(ctx context.Context, arg UpdateNotificationBatchParams) error
	UpdateRestore(ctx context.Context, arg UpdateRestoreParams) error
	UpdateScript(ctx context.Context, arg UpdateScriptParams) error
	UpdateTarget(ctx context.Context, arg UpdateTargetParams) error
	UpdateTargetMySQLPassword(ctx context.Context, arg UpdateTargetMySQLPasswordParams) (int64, error)
	UpdateTargetPostgreSQLPassword(ctx context.Context, arg UpdateTargetPostgreSQLPasswordParams) (int64, error)
	UpdateTargetS3Secret(ctx context.Context, arg UpdateTargetS3SecretParams) (int64, error)
	UpdateVerificationJob(ctx context.Context, arg UpdateVerificationJobParams) error
	UpdateVerificationResult(ctx context.Context, arg UpdateVerificationResultParams) error
	UpsertAlertSetting(ctx context.Context, arg UpsertAlertSettingParams) error
	UpsertBackupDatabaseOptions(ctx context.Context, arg UpsertBackupDatabaseOptionsParams) error
	UpsertBatchResult(ctx context.Context, arg UpsertBatchResultParams) error
	UpsertRestoreDatabaseOptions(ctx context.Context, arg UpsertRestoreDatabaseOptionsParams) error
	UpsertTarget(ctx context.Context, arg UpsertTargetParams) error
	UpsertTargetFilesystem(ctx context.Context, arg UpsertTargetFilesystemParams) error
	UpsertTargetMySQL(ctx context.Context, arg UpsertTargetMySQLParams) error
	UpsertTargetPostgreSQL(ctx context.Context, arg UpsertTargetPostgreSQLParams) error
	UpsertTargetS3(ctx context.Context, arg UpsertTargetS3Params) error
	VerificationJobExists(ctx context.Context, id string) (int64, error)
}

var _ Querier = (*Queries)(nil)
