// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restores.sql

package corequery

import (
	"context"
	"database/sql"
)

const countRestores = `-- name: CountRestores :one
SELECT COUNT(*) FROM restores
`

func (q *Queries) CountRestores(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRestores)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRestore = `-- name: CreateRestore :exec
INSERT INTO restores (
    id, store, namespace, snapshot, src_path, dest_target, dest_subpath,
    comment, current_pid, last_run_upid, last_successful_upid, retry,
    retry_interval, pre_script, post_script, restore_mode, last_run_status, retry_count,
    notification_mode
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRestoreParams struct {
	ID                 string         `json:"id"`
	Store              string         `json:"store"`
	Namespace          sql.NullString `json:"namespace"`
	Snapshot           string         `json:"snapshot"`
	SrcPath            string         `json:"src_path"`
	DestTarget         string         `json:"dest_target"`
	DestSubpath        sql.NullString `json:"dest_subpath"`
	Comment            sql.NullString `json:"comment"`
	CurrentPid         sql.NullString `json:"current_pid"`
	LastRunUpid        sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid sql.NullString `json:"last_successful_upid"`
	Retry              sql.NullInt64  `json:"retry"`
	RetryInterval      sql.NullInt64  `json:"retry_interval"`
	PreScript          string         `json:"pre_script"`
	PostScript         string         `json:"post_script"`
	RestoreMode        int64          `json:"restore_mode"`
	LastRunStatus      sql.NullInt64  `json:"last_run_status"`
	RetryCount         sql.NullInt64  `json:"retry_count"`
	NotificationMode   sql.NullString `json:"notification_mode"`
}

func (q *Queries) CreateRestore(ctx context.Context, arg CreateRestoreParams) error {
	_, err := q.db.ExecContext(ctx, createRestore,
		arg.ID,
		arg.Store,
		arg.Namespace,
		arg.Snapshot,
		arg.SrcPath,
		arg.DestTarget,
		arg.DestSubpath,
		arg.Comment,
		arg.CurrentPid,
		arg.LastRunUpid,
		arg.LastSuccessfulUpid,
		arg.Retry,
		arg.RetryInterval,
		arg.PreScript,
		arg.PostScript,
		arg.RestoreMode,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.NotificationMode,
	)
	return err
}

const deleteRestore = `-- name: DeleteRestore :execrows
DELETE FROM restores WHERE id = ?
`

func (q *Queries) DeleteRestore(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRestore, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRestoreDatabaseOptions = `-- name: DeleteRestoreDatabaseOptions :exec
DELETE FROM restore_database_options WHERE restore_id = ?
`

func (q *Queries) DeleteRestoreDatabaseOptions(ctx context.Context, restoreID string) error {
	_, err := q.db.ExecContext(ctx, deleteRestoreDatabaseOptions, restoreID)
	return err
}

const getRestore = `-- name: GetRestore :one
SELECT
    j.id, j.store, j.namespace, j.snapshot, j.src_path, j.dest_target,
    j.dest_subpath, j.comment, j.current_pid, j.last_run_upid,
    j.last_successful_upid, j.retry, j.retry_interval, j.pre_script, j.post_script,
    j.restore_mode, j.last_run_status, j.retry_count, j.notification_mode,
    COALESCE(dro.source_database, '') AS source_database,
    COALESCE(dro.destination_database, '') AS destination_database,
    COALESCE(dro.replace_existing, 0) AS replace_existing,
    COALESCE(dro.client_family, '') AS database_client_family,
    COALESCE(dro.client_dir, '') AS database_client_dir,
    t.name, t.target_type, t.mount_script,
    COALESCE(f.access, '') AS filesystem_access,
    COALESCE(f.path, s.url, '') AS path,
    f.agent_host, f.volume_id, f.volume_type, f.volume_name,
    f.volume_fs, f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
    f.volume_total, f.volume_used, f.volume_free,
    COALESCE(p.host, m.host, l.host, '') AS database_host,
    COALESCE(p.port, m.port, l.port, 0) AS database_port,
    COALESCE(p.username, m.username, l.username, '') AS database_username,
    COALESCE(p.ssl_mode, m.tls_mode, l.tls_mode, '') AS database_tls_mode,
    COALESCE(p.ca_certificate, m.ca_certificate, l.ca_certificate, '') AS database_ca_certificate,
    COALESCE(p.default_client_dir, m.default_client_dir, l.default_client_dir, '') AS database_default_client_dir,
    COALESCE(m.variant, '') AS database_variant,
    COALESCE(m.default_client_family, '') AS database_default_client_family,
    COALESCE(l.base_dn, '') AS ldap_base_dn,
    ah.name as agent_name, ah.ip as agent_ip, ah.auth as agent_auth,
    ah.token_used as agent_token_used, ah.os as agent_os
FROM restores j
LEFT JOIN restore_database_options dro ON dro.restore_id = j.id
LEFT JOIN targets t ON j.dest_target = t.name
LEFT JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN target_s3 s ON s.target_name = t.name
LEFT JOIN target_postgresql p ON p.target_name = t.name
LEFT JOIN target_mysql m ON m.target_name = t.name
LEFT JOIN target_ldap l ON l.target_name = t.name
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
WHERE j.id = ?
LIMIT 1
`

type GetRestoreRow struct {
	ID                          string         `json:"id"`
	Store                       string         `json:"store"`
	Namespace                   sql.NullString `json:"namespace"`
	Snapshot                    string         `json:"snapshot"`
	SrcPath                     string         `json:"src_path"`
	DestTarget                  string         `json:"dest_target"`
	DestSubpath                 sql.NullString `json:"dest_subpath"`
	Comment                     sql.NullString `json:"comment"`
	CurrentPid                  sql.NullString `json:"current_pid"`
	LastRunUpid                 sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid          sql.NullString `json:"last_successful_upid"`
	Retry                       sql.NullInt64  `json:"retry"`
	RetryInterval               sql.NullInt64  `json:"retry_interval"`
	PreScript                   string         `json:"pre_script"`
	PostScript                  string         `json:"post_script"`
	RestoreMode                 int64          `json:"restore_mode"`
	LastRunStatus               sql.NullInt64  `json:"last_run_status"`
	RetryCount                  sql.NullInt64  `json:"retry_count"`
	NotificationMode            sql.NullString `json:"notification_mode"`
	SourceDatabase              string         `json:"source_database"`
	DestinationDatabase         string         `json:"destination_database"`
	ReplaceExisting             int64          `json:"replace_existing"`
	DatabaseClientFamily        string         `json:"database_client_family"`
	DatabaseClientDir           string         `json:"database_client_dir"`
	Name                        sql.NullString `json:"name"`
	TargetType                  sql.NullString `json:"target_type"`
	MountScript                 sql.NullString `json:"mount_script"`
	FilesystemAccess            string         `json:"filesystem_access"`
	Path                        string         `json:"path"`
	AgentHost                   sql.NullString `json:"agent_host"`
	VolumeID                    sql.NullString `json:"volume_id"`
	VolumeType                  sql.NullString `json:"volume_type"`
	VolumeName                  sql.NullString `json:"volume_name"`
	VolumeFs                    sql.NullString `json:"volume_fs"`
	VolumeTotalBytes            sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes             sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes             sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal                 sql.NullString `json:"volume_total"`
	VolumeUsed                  sql.NullString `json:"volume_used"`
	VolumeFree                  sql.NullString `json:"volume_free"`
	DatabaseHost                string         `json:"database_host"`
	DatabasePort                int64          `json:"database_port"`
	DatabaseUsername            string         `json:"database_username"`
	DatabaseTlsMode             string         `json:"database_tls_mode"`
	DatabaseCaCertificate       string         `json:"database_ca_certificate"`
	DatabaseDefaultClientDir    string         `json:"database_default_client_dir"`
	DatabaseVariant             string         `json:"database_variant"`
	DatabaseDefaultClientFamily string         `json:"database_default_client_family"`
	LdapBaseDn                  string         `json:"ldap_base_dn"`
	AgentName                   sql.NullString `json:"agent_name"`
	AgentIp                     sql.NullString `json:"agent_ip"`
	AgentAuth                   sql.NullString `json:"agent_auth"`
	AgentTokenUsed              sql.NullString `json:"agent_token_used"`
	AgentOs                     sql.NullString `json:"agent_os"`
}

func (q *Queries) GetRestore(ctx context.Context, id string) (GetRestoreRow, error) {
	row := q.db.QueryRowContext(ctx, getRestore, id)
	var i GetRestoreRow
	err := row.Scan(
		&i.ID,
		&i.Store,
		&i.Namespace,
		&i.Snapshot,
		&i.SrcPath,
		&i.DestTarget,
		&i.DestSubpath,
		&i.Comment,
		&i.CurrentPid,
		&i.LastRunUpid,
		&i.LastSuccessfulUpid,
		&i.Retry,
		&i.RetryInterval,
		&i.PreScript,
		&i.PostScript,
		&i.RestoreMode,
		&i.LastRunStatus,
		&i.RetryCount,
		&i.NotificationMode,
		&i.SourceDatabase,
		&i.DestinationDatabase,
		&i.ReplaceExisting,
		&i.DatabaseClientFamily,
		&i.DatabaseClientDir,
		&i.Name,
		&i.TargetType,
		&i.MountScript,
		&i.FilesystemAccess,
		&i.Path,
		&i.AgentHost,
		&i.VolumeID,
		&i.VolumeType,
		&i.VolumeName,
		&i.VolumeFs,
		&i.VolumeTotalBytes,
		&i.VolumeUsedBytes,
		&i.VolumeFreeBytes,
		&i.VolumeTotal,
		&i.VolumeUsed,
		&i.VolumeFree,
		&i.DatabaseHost,
		&i.DatabasePort,
		&i.DatabaseUsername,
		&i.DatabaseTlsMode,
		&i.DatabaseCaCertificate,
		&i.DatabaseDefaultClientDir,
		&i.DatabaseVariant,
		&i.DatabaseDefaultClientFamily,
		&i.LdapBaseDn,
		&i.AgentName,
		&i.AgentIp,
		&i.AgentAuth,
		&i.AgentTokenUsed,
		&i.AgentOs,
	)
	return i, err
}

const listAllRestores = `-- name: ListAllRestores :many
SELECT
    j.id, j.store, j.namespace, j.snapshot, j.src_path, j.dest_target,
    j.dest_subpath, j.comment, j.current_pid, j.last_run_upid,
    j.last_successful_upid, j.retry, j.retry_interval, j.pre_script, j.post_script,
    j.restore_mode, j.last_run_status, j.retry_count, j.notification_mode,
    COALESCE(dro.source_database, '') AS source_database,
    COALESCE(dro.destination_database, '') AS destination_database,
    COALESCE(dro.replace_existing, 0) AS replace_existing,
    COALESCE(dro.client_family, '') AS database_client_family,
    COALESCE(dro.client_dir, '') AS database_client_dir,
    t.name, t.target_type, t.mount_script,
    COALESCE(f.access, '') AS filesystem_access,
    COALESCE(f.path, s.url, '') AS path,
    f.agent_host, f.volume_id, f.volume_type, f.volume_name,
    f.volume_fs, f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
    f.volume_total, f.volume_used, f.volume_free,
    COALESCE(p.host, m.host, l.host, '') AS database_host,
    COALESCE(p.port, m.port, l.port, 0) AS database_port,
    COALESCE(p.username, m.username, l.username, '') AS database_username,
    COALESCE(p.ssl_mode, m.tls_mode, l.tls_mode, '') AS database_tls_mode,
    COALESCE(p.ca_certificate, m.ca_certificate, l.ca_certificate, '') AS database_ca_certificate,
    COALESCE(p.default_client_dir, m.default_client_dir, l.default_client_dir, '') AS database_default_client_dir,
    COALESCE(m.variant, '') AS database_variant,
    COALESCE(m.default_client_family, '') AS database_default_client_family,
    COALESCE(l.base_dn, '') AS ldap_base_dn,
    ah.name as agent_name, ah.ip as agent_ip, ah.auth as agent_auth,
    ah.token_used as agent_token_used, ah.os as agent_os
FROM restores j
LEFT JOIN restore_database_options dro ON dro.restore_id = j.id
LEFT JOIN targets t ON j.dest_target = t.name
LEFT JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN target_s3 s ON s.target_name = t.name
LEFT JOIN target_postgresql p ON p.target_name = t.name
LEFT JOIN target_mysql m ON m.target_name = t.name
LEFT JOIN target_ldap l ON l.target_name = t.name
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
ORDER BY j.id
`

type ListAllRestoresRow struct {
	ID                          string         `json:"id"`
	Store                       string         `json:"store"`
	Namespace                   sql.NullString `json:"namespace"`
	Snapshot                    string         `json:"snapshot"`
	SrcPath                     string         `json:"src_path"`
	DestTarget                  string         `json:"dest_target"`
	DestSubpath                 sql.NullString `json:"dest_subpath"`
	Comment                     sql.NullString `json:"comment"`
	CurrentPid                  sql.NullString `json:"current_pid"`
	LastRunUpid                 sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid          sql.NullString `json:"last_successful_upid"`
	Retry                       sql.NullInt64  `json:"retry"`
	RetryInterval               sql.NullInt64  `json:"retry_interval"`
	PreScript                   string         `json:"pre_script"`
	PostScript                  string         `json:"post_script"`
	RestoreMode                 int64          `json:"restore_mode"`
	LastRunStatus               sql.NullInt64  `json:"last_run_status"`
	RetryCount                  sql.NullInt64  `json:"retry_count"`
	NotificationMode            sql.NullString `json:"notification_mode"`
	SourceDatabase              string         `json:"source_database"`
	DestinationDatabase         string         `json:"destination_database"`
	ReplaceExisting             int64          `json:"replace_existing"`
	DatabaseClientFamily        string         `json:"database_client_family"`
	DatabaseClientDir           string         `json:"database_client_dir"`
	Name                        sql.NullString `json:"name"`
	TargetType                  sql.NullString `json:"target_type"`
	MountScript                 sql.NullString `json:"mount_script"`
	FilesystemAccess            string         `json:"filesystem_access"`
	Path                        string         `json:"path"`
	AgentHost                   sql.NullString `json:"agent_host"`
	VolumeID                    sql.NullString `json:"volume_id"`
	VolumeType                  sql.NullString `json:"volume_type"`
	VolumeName                  sql.NullString `json:"volume_name"`
	VolumeFs                    sql.NullString `json:"volume_fs"`
	VolumeTotalBytes            sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes             sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes             sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal                 sql.NullString `json:"volume_total"`
	VolumeUsed                  sql.NullString `json:"volume_used"`
	VolumeFree                  sql.NullString `json:"volume_free"`
	DatabaseHost                string         `json:"database_host"`
	DatabasePort                int64          `json:"database_port"`
	DatabaseUsername            string         `json:"database_username"`
	DatabaseTlsMode             string         `json:"database_tls_mode"`
	DatabaseCaCertificate       string         `json:"database_ca_certificate"`
	DatabaseDefaultClientDir    string         `json:"database_default_client_dir"`
	DatabaseVariant             string         `json:"database_variant"`
	DatabaseDefaultClientFamily string         `json:"database_default_client_family"`
	LdapBaseDn                  string         `json:"ldap_base_dn"`
	AgentName                   sql.NullString `json:"agent_name"`
	AgentIp                     sql.NullString `json:"agent_ip"`
	AgentAuth                   sql.NullString `json:"agent_auth"`
	AgentTokenUsed              sql.NullString `json:"agent_token_used"`
	AgentOs                     sql.NullString `json:"agent_os"`
}

func (q *Queries) ListAllRestores(ctx context.Context) ([]ListAllRestoresRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRestores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRestoresRow{}
	for rows.Next() {
		var i ListAllRestoresRow
		if err := rows.Scan(
			&i.ID,
			&i.Store,
			&i.Namespace,
			&i.Snapshot,
			&i.SrcPath,
			&i.DestTarget,
			&i.DestSubpath,
			&i.Comment,
			&i.CurrentPid,
			&i.LastRunUpid,
			&i.LastSuccessfulUpid,
			&i.Retry,
			&i.RetryInterval,
			&i.PreScript,
			&i.PostScript,
			&i.RestoreMode,
			&i.LastRunStatus,
			&i.RetryCount,
			&i.NotificationMode,
			&i.SourceDatabase,
			&i.DestinationDatabase,
			&i.ReplaceExisting,
			&i.DatabaseClientFamily,
			&i.DatabaseClientDir,
			&i.Name,
			&i.TargetType,
			&i.MountScript,
			&i.FilesystemAccess,
			&i.Path,
			&i.AgentHost,
			&i.VolumeID,
			&i.VolumeType,
			&i.VolumeName,
			&i.VolumeFs,
			&i.VolumeTotalBytes,
			&i.VolumeUsedBytes,
			&i.VolumeFreeBytes,
			&i.VolumeTotal,
			&i.VolumeUsed,
			&i.VolumeFree,
			&i.DatabaseHost,
			&i.DatabasePort,
			&i.DatabaseUsername,
			&i.DatabaseTlsMode,
			&i.DatabaseCaCertificate,
			&i.DatabaseDefaultClientDir,
			&i.DatabaseVariant,
			&i.DatabaseDefaultClientFamily,
			&i.LdapBaseDn,
			&i.AgentName,
			&i.AgentIp,
			&i.AgentAuth,
			&i.AgentTokenUsed,
			&i.AgentOs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreExists = `-- name: RestoreExists :one
SELECT 1 FROM restores WHERE id = ? LIMIT 1
`

func (q *Queries) RestoreExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, restoreExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateRestore = `-- name: UpdateRestore :exec
UPDATE restores
SET store = ?, namespace = ?, snapshot = ?, src_path = ?, dest_target = ?,
    dest_subpath = ?, comment = ?, current_pid = ?, last_run_upid = ?,
    retry = ?, retry_interval = ?, last_successful_upid = ?,
    pre_script = ?, post_script = ?, restore_mode = ?, last_run_status = ?, retry_count = ?,
    notification_mode = ?
WHERE id = ?
`

type UpdateRestoreParams struct {
	Store              string         `json:"store"`
	Namespace          sql.NullString `json:"namespace"`
	Snapshot           string         `json:"snapshot"`
	SrcPath            string         `json:"src_path"`
	DestTarget         string         `json:"dest_target"`
	DestSubpath        sql.NullString `json:"dest_subpath"`
	Comment            sql.NullString `json:"comment"`
	CurrentPid         sql.NullString `json:"current_pid"`
	LastRunUpid        sql.NullString `json:"last_run_upid"`
	Retry              sql.NullInt64  `json:"retry"`
	RetryInterval      sql.NullInt64  `json:"retry_interval"`
	LastSuccessfulUpid sql.NullString `json:"last_successful_upid"`
	PreScript          string         `json:"pre_script"`
	PostScript         string         `json:"post_script"`
	RestoreMode        int64          `json:"restore_mode"`
	LastRunStatus      sql.NullInt64  `json:"last_run_status"`
	RetryCount         sql.NullInt64  `json:"retry_count"`
	NotificationMode   sql.NullString `json:"notification_mode"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateRestore(ctx context.Context, arg UpdateRestoreParams) error {
	_, err := q.db.ExecContext(ctx, updateRestore,
		arg.Store,
		arg.Namespace,
		arg.Snapshot,
		arg.SrcPath,
		arg.DestTarget,
		arg.DestSubpath,
		arg.Comment,
		arg.CurrentPid,
		arg.LastRunUpid,
		arg.Retry,
		arg.RetryInterval,
		arg.LastSuccessfulUpid,
		arg.PreScript,
		arg.PostScript,
		arg.RestoreMode,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.NotificationMode,
		arg.ID,
	)
	return err
}

const upsertRestoreDatabaseOptions = `-- name: UpsertRestoreDatabaseOptions :exec
INSERT INTO restore_database_options (
    restore_id, source_database, destination_database, replace_existing, client_family, client_dir
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(restore_id) DO UPDATE SET
    source_database = excluded.source_database,
    destination_database = excluded.destination_database,
    replace_existing = excluded.replace_existing,
    client_family = excluded.client_family,
    client_dir = excluded.client_dir
`

type UpsertRestoreDatabaseOptionsParams struct {
	RestoreID           string `json:"restore_id"`
	SourceDatabase      string `json:"source_database"`
	DestinationDatabase string `json:"destination_database"`
	ReplaceExisting     int64  `json:"replace_existing"`
	ClientFamily        string `json:"client_family"`
	ClientDir           string `json:"client_dir"`
}

func (q *Queries) UpsertRestoreDatabaseOptions(ctx context.Context, arg UpsertRestoreDatabaseOptionsParams) error {
	_, err := q.db.ExecContext(ctx, upsertRestoreDatabaseOptions,
		arg.RestoreID,
		arg.SourceDatabase,
		arg.DestinationDatabase,
		arg.ReplaceExisting,
		arg.ClientFamily,
		arg.ClientDir,
	)
	return err
}
