// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: targets.sql

package corequery

import (
	"context"
	"database/sql"
)

const createTarget = `-- name: CreateTarget :exec
INSERT INTO targets (name, target_type, mount_script)
VALUES (?, ?, ?)
`

type CreateTargetParams struct {
	Name        string `json:"name"`
	TargetType  string `json:"target_type"`
	MountScript string `json:"mount_script"`
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) error {
	_, err := q.db.ExecContext(ctx, createTarget, arg.Name, arg.TargetType, arg.MountScript)
	return err
}

const deleteTarget = `-- name: DeleteTarget :execrows
DELETE FROM targets WHERE name = ?
`

func (q *Queries) DeleteTarget(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTarget, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTargetFilesystem = `-- name: DeleteTargetFilesystem :exec
DELETE FROM target_filesystems WHERE target_name = ?
`

func (q *Queries) DeleteTargetFilesystem(ctx context.Context, targetName string) error {
	_, err := q.db.ExecContext(ctx, deleteTargetFilesystem, targetName)
	return err
}

const deleteTargetLdap = `-- name: DeleteTargetLdap :exec
DELETE FROM target_ldap WHERE target_name = ?
`

func (q *Queries) DeleteTargetLdap(ctx context.Context, targetName string) error {
	_, err := q.db.ExecContext(ctx, deleteTargetLdap, targetName)
	return err
}

const deleteTargetMySQL = `-- name: DeleteTargetMySQL :exec
DELETE FROM target_mysql WHERE target_name = ?
`

func (q *Queries) DeleteTargetMySQL(ctx context.Context, targetName string) error {
	_, err := q.db.ExecContext(ctx, deleteTargetMySQL, targetName)
	return err
}

const deleteTargetPostgreSQL = `-- name: DeleteTargetPostgreSQL :exec
DELETE FROM target_postgresql WHERE target_name = ?
`

func (q *Queries) DeleteTargetPostgreSQL(ctx context.Context, targetName string) error {
	_, err := q.db.ExecContext(ctx, deleteTargetPostgreSQL, targetName)
	return err
}

const deleteTargetS3 = `-- name: DeleteTargetS3 :exec
DELETE FROM target_s3 WHERE target_name = ?
`

func (q *Queries) DeleteTargetS3(ctx context.Context, targetName string) error {
	_, err := q.db.ExecContext(ctx, deleteTargetS3, targetName)
	return err
}

const getTarget = `-- name: GetTarget :one
SELECT
    t.name, t.target_type, t.mount_script,
    COALESCE(f.access, '') AS filesystem_access,
    COALESCE(f.path, s.url, '') AS path,
    f.agent_host, f.volume_id, f.volume_type, f.volume_name,
    f.volume_fs, f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
    f.volume_total, f.volume_used, f.volume_free,
    COALESCE(p.host, m.host, l.host, '') AS database_host,
    COALESCE(p.port, m.port, l.port, 0) AS database_port,
    COALESCE(p.username, m.username, l.username, '') AS database_username,
    COALESCE(p.ssl_mode, m.tls_mode, l.tls_mode, '') AS database_tls_mode,
    COALESCE(p.ca_certificate, m.ca_certificate, l.ca_certificate, '') AS database_ca_certificate,
    COALESCE(p.default_client_dir, m.default_client_dir, l.default_client_dir, '') AS database_default_client_dir,
    COALESCE(m.variant, '') AS database_variant,
    COALESCE(m.default_client_family, '') AS database_default_client_family,
    COALESCE(l.base_dn, '') AS ldap_base_dn,
    COUNT(j.id) AS job_count,
    ah.name AS agent_name, ah.ip AS agent_ip, ah.auth AS agent_auth,
    ah.token_used AS agent_token_used, ah.os AS agent_os
FROM targets t
LEFT JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN target_s3 s ON s.target_name = t.name
LEFT JOIN target_postgresql p ON p.target_name = t.name
LEFT JOIN target_mysql m ON m.target_name = t.name
LEFT JOIN target_ldap l ON l.target_name = t.name
LEFT JOIN backups j ON t.name = j.target
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
WHERE t.name = ?
GROUP BY t.name
`

type GetTargetRow struct {
	Name                        string         `json:"name"`
	TargetType                  string         `json:"target_type"`
	MountScript                 string         `json:"mount_script"`
	FilesystemAccess            string         `json:"filesystem_access"`
	Path                        string         `json:"path"`
	AgentHost                   sql.NullString `json:"agent_host"`
	VolumeID                    sql.NullString `json:"volume_id"`
	VolumeType                  sql.NullString `json:"volume_type"`
	VolumeName                  sql.NullString `json:"volume_name"`
	VolumeFs                    sql.NullString `json:"volume_fs"`
	VolumeTotalBytes            sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes             sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes             sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal                 sql.NullString `json:"volume_total"`
	VolumeUsed                  sql.NullString `json:"volume_used"`
	VolumeFree                  sql.NullString `json:"volume_free"`
	DatabaseHost                string         `json:"database_host"`
	DatabasePort                int64          `json:"database_port"`
	DatabaseUsername            string         `json:"database_username"`
	DatabaseTlsMode             string         `json:"database_tls_mode"`
	DatabaseCaCertificate       string         `json:"database_ca_certificate"`
	DatabaseDefaultClientDir    string         `json:"database_default_client_dir"`
	DatabaseVariant             string         `json:"database_variant"`
	DatabaseDefaultClientFamily string         `json:"database_default_client_family"`
	LdapBaseDn                  string         `json:"ldap_base_dn"`
	JobCount                    int64          `json:"job_count"`
	AgentName                   sql.NullString `json:"agent_name"`
	AgentIp                     sql.NullString `json:"agent_ip"`
	AgentAuth                   sql.NullString `json:"agent_auth"`
	AgentTokenUsed              sql.NullString `json:"agent_token_used"`
	AgentOs                     sql.NullString `json:"agent_os"`
}

func (q *Queries) GetTarget(ctx context.Context, name string) (GetTargetRow, error) {
	row := q.db.QueryRowContext(ctx, getTarget, name)
	var i GetTargetRow
	err := row.Scan(
		&i.Name,
		&i.TargetType,
		&i.MountScript,
		&i.FilesystemAccess,
		&i.Path,
		&i.AgentHost,
		&i.VolumeID,
		&i.VolumeType,
		&i.VolumeName,
		&i.VolumeFs,
		&i.VolumeTotalBytes,
		&i.VolumeUsedBytes,
		&i.VolumeFreeBytes,
		&i.VolumeTotal,
		&i.VolumeUsed,
		&i.VolumeFree,
		&i.DatabaseHost,
		&i.DatabasePort,
		&i.DatabaseUsername,
		&i.DatabaseTlsMode,
		&i.DatabaseCaCertificate,
		&i.DatabaseDefaultClientDir,
		&i.DatabaseVariant,
		&i.DatabaseDefaultClientFamily,
		&i.LdapBaseDn,
		&i.JobCount,
		&i.AgentName,
		&i.AgentIp,
		&i.AgentAuth,
		&i.AgentTokenUsed,
		&i.AgentOs,
	)
	return i, err
}

const getTargetLdapPassword = `-- name: GetTargetLdapPassword :one
SELECT password FROM target_ldap WHERE target_name = ?
`

func (q *Queries) GetTargetLdapPassword(ctx context.Context, targetName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTargetLdapPassword, targetName)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getTargetMySQLPassword = `-- name: GetTargetMySQLPassword :one
SELECT password FROM target_mysql WHERE target_name = ?
`

func (q *Queries) GetTargetMySQLPassword(ctx context.Context, targetName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTargetMySQLPassword, targetName)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getTargetPostgreSQLPassword = `-- name: GetTargetPostgreSQLPassword :one
SELECT password FROM target_postgresql WHERE target_name = ?
`

func (q *Queries) GetTargetPostgreSQLPassword(ctx context.Context, targetName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTargetPostgreSQLPassword, targetName)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getTargetS3Secret = `-- name: GetTargetS3Secret :one
SELECT secret FROM target_s3 WHERE target_name = ?
`

func (q *Queries) GetTargetS3Secret(ctx context.Context, targetName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTargetS3Secret, targetName)
	var secret string
	err := row.Scan(&secret)
	return secret, err
}

const listAllTargets = `-- name: ListAllTargets :many
SELECT
    t.name, t.target_type, t.mount_script,
    COALESCE(f.access, '') AS filesystem_access,
    COALESCE(f.path, s.url, '') AS path,
    f.agent_host, f.volume_id, f.volume_type, f.volume_name,
    f.volume_fs, f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
    f.volume_total, f.volume_used, f.volume_free,
    COALESCE(p.host, m.host, l.host, '') AS database_host,
    COALESCE(p.port, m.port, l.port, 0) AS database_port,
    COALESCE(p.username, m.username, l.username, '') AS database_username,
    COALESCE(p.ssl_mode, m.tls_mode, l.tls_mode, '') AS database_tls_mode,
    COALESCE(p.ca_certificate, m.ca_certificate, l.ca_certificate, '') AS database_ca_certificate,
    COALESCE(p.default_client_dir, m.default_client_dir, l.default_client_dir, '') AS database_default_client_dir,
    COALESCE(m.variant, '') AS database_variant,
    COALESCE(m.default_client_family, '') AS database_default_client_family,
    COALESCE(l.base_dn, '') AS ldap_base_dn,
    COUNT(j.id) AS job_count,
    ah.name AS agent_name, ah.ip AS agent_ip, ah.auth AS agent_auth,
    ah.token_used AS agent_token_used, ah.os AS agent_os
FROM targets t
LEFT JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN target_s3 s ON s.target_name = t.name
LEFT JOIN target_postgresql p ON p.target_name = t.name
LEFT JOIN target_mysql m ON m.target_name = t.name
LEFT JOIN target_ldap l ON l.target_name = t.name
LEFT JOIN backups j ON t.name = j.target
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
GROUP BY t.name, t.target_type, t.mount_script, f.access, f.path, s.url,
         f.agent_host, f.volume_id, f.volume_type, f.volume_name, f.volume_fs,
         f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
         f.volume_total, f.volume_used, f.volume_free,
         p.host, m.host, l.host, p.port, m.port, l.port,
         p.username, m.username, l.username,
         p.ssl_mode, m.tls_mode, l.tls_mode,
         p.ca_certificate, m.ca_certificate, l.ca_certificate,
         p.default_client_dir, m.default_client_dir, l.default_client_dir,
         m.variant, m.default_client_family, l.base_dn,
         ah.name, ah.ip, ah.auth, ah.token_used, ah.os
ORDER BY t.name
`

type ListAllTargetsRow struct {
	Name                        string         `json:"name"`
	TargetType                  string         `json:"target_type"`
	MountScript                 string         `json:"mount_script"`
	FilesystemAccess            string         `json:"filesystem_access"`
	Path                        string         `json:"path"`
	AgentHost                   sql.NullString `json:"agent_host"`
	VolumeID                    sql.NullString `json:"volume_id"`
	VolumeType                  sql.NullString `json:"volume_type"`
	VolumeName                  sql.NullString `json:"volume_name"`
	VolumeFs                    sql.NullString `json:"volume_fs"`
	VolumeTotalBytes            sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes             sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes             sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal                 sql.NullString `json:"volume_total"`
	VolumeUsed                  sql.NullString `json:"volume_used"`
	VolumeFree                  sql.NullString `json:"volume_free"`
	DatabaseHost                string         `json:"database_host"`
	DatabasePort                int64          `json:"database_port"`
	DatabaseUsername            string         `json:"database_username"`
	DatabaseTlsMode             string         `json:"database_tls_mode"`
	DatabaseCaCertificate       string         `json:"database_ca_certificate"`
	DatabaseDefaultClientDir    string         `json:"database_default_client_dir"`
	DatabaseVariant             string         `json:"database_variant"`
	DatabaseDefaultClientFamily string         `json:"database_default_client_family"`
	LdapBaseDn                  string         `json:"ldap_base_dn"`
	JobCount                    int64          `json:"job_count"`
	AgentName                   sql.NullString `json:"agent_name"`
	AgentIp                     sql.NullString `json:"agent_ip"`
	AgentAuth                   sql.NullString `json:"agent_auth"`
	AgentTokenUsed              sql.NullString `json:"agent_token_used"`
	AgentOs                     sql.NullString `json:"agent_os"`
}

func (q *Queries) ListAllTargets(ctx context.Context) ([]ListAllTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTargetsRow{}
	for rows.Next() {
		var i ListAllTargetsRow
		if err := rows.Scan(
			&i.Name,
			&i.TargetType,
			&i.MountScript,
			&i.FilesystemAccess,
			&i.Path,
			&i.AgentHost,
			&i.VolumeID,
			&i.VolumeType,
			&i.VolumeName,
			&i.VolumeFs,
			&i.VolumeTotalBytes,
			&i.VolumeUsedBytes,
			&i.VolumeFreeBytes,
			&i.VolumeTotal,
			&i.VolumeUsed,
			&i.VolumeFree,
			&i.DatabaseHost,
			&i.DatabasePort,
			&i.DatabaseUsername,
			&i.DatabaseTlsMode,
			&i.DatabaseCaCertificate,
			&i.DatabaseDefaultClientDir,
			&i.DatabaseVariant,
			&i.DatabaseDefaultClientFamily,
			&i.LdapBaseDn,
			&i.JobCount,
			&i.AgentName,
			&i.AgentIp,
			&i.AgentAuth,
			&i.AgentTokenUsed,
			&i.AgentOs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsByAgentHost = `-- name: ListTargetsByAgentHost :many
SELECT
    t.name, t.target_type, t.mount_script,
    f.access AS filesystem_access, f.path, f.agent_host, f.volume_id,
    f.volume_type, f.volume_name, f.volume_fs, f.volume_total_bytes,
    f.volume_used_bytes, f.volume_free_bytes, f.volume_total, f.volume_used,
    f.volume_free,
    ah.name AS agent_name, ah.ip AS agent_ip, ah.auth AS agent_auth,
    ah.token_used AS agent_token_used, ah.os AS agent_os
FROM targets t
JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
WHERE f.agent_host = ?
ORDER BY t.name
`

type ListTargetsByAgentHostRow struct {
	Name             string         `json:"name"`
	TargetType       string         `json:"target_type"`
	MountScript      string         `json:"mount_script"`
	FilesystemAccess string         `json:"filesystem_access"`
	Path             string         `json:"path"`
	AgentHost        sql.NullString `json:"agent_host"`
	VolumeID         sql.NullString `json:"volume_id"`
	VolumeType       sql.NullString `json:"volume_type"`
	VolumeName       sql.NullString `json:"volume_name"`
	VolumeFs         sql.NullString `json:"volume_fs"`
	VolumeTotalBytes sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes  sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes  sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal      sql.NullString `json:"volume_total"`
	VolumeUsed       sql.NullString `json:"volume_used"`
	VolumeFree       sql.NullString `json:"volume_free"`
	AgentName        sql.NullString `json:"agent_name"`
	AgentIp          sql.NullString `json:"agent_ip"`
	AgentAuth        sql.NullString `json:"agent_auth"`
	AgentTokenUsed   sql.NullString `json:"agent_token_used"`
	AgentOs          sql.NullString `json:"agent_os"`
}

func (q *Queries) ListTargetsByAgentHost(ctx context.Context, agentHost sql.NullString) ([]ListTargetsByAgentHostRow, error) {
	rows, err := q.db.QueryContext(ctx, listTargetsByAgentHost, agentHost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTargetsByAgentHostRow{}
	for rows.Next() {
		var i ListTargetsByAgentHostRow
		if err := rows.Scan(
			&i.Name,
			&i.TargetType,
			&i.MountScript,
			&i.FilesystemAccess,
			&i.Path,
			&i.AgentHost,
			&i.VolumeID,
			&i.VolumeType,
			&i.VolumeName,
			&i.VolumeFs,
			&i.VolumeTotalBytes,
			&i.VolumeUsedBytes,
			&i.VolumeFreeBytes,
			&i.VolumeTotal,
			&i.VolumeUsed,
			&i.VolumeFree,
			&i.AgentName,
			&i.AgentIp,
			&i.AgentAuth,
			&i.AgentTokenUsed,
			&i.AgentOs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const targetExists = `-- name: TargetExists :one
SELECT 1 FROM targets WHERE name = ? LIMIT 1
`

func (q *Queries) TargetExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, targetExists, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateTarget = `-- name: UpdateTarget :exec
UPDATE targets
SET target_type = ?, mount_script = ?
WHERE name = ?
`

type UpdateTargetParams struct {
	TargetType  string `json:"target_type"`
	MountScript string `json:"mount_script"`
	Name        string `json:"name"`
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateTarget, arg.TargetType, arg.MountScript, arg.Name)
	return err
}

const updateTargetLdapPassword = `-- name: UpdateTargetLdapPassword :execrows
UPDATE target_ldap SET password = ? WHERE target_name = ?
`

type UpdateTargetLdapPasswordParams struct {
	Password   string `json:"password"`
	TargetName string `json:"target_name"`
}

func (q *Queries) UpdateTargetLdapPassword(ctx context.Context, arg UpdateTargetLdapPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTargetLdapPassword, arg.Password, arg.TargetName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTargetMySQLPassword = `-- name: UpdateTargetMySQLPassword :execrows
UPDATE target_mysql SET password = ? WHERE target_name = ?
`

type UpdateTargetMySQLPasswordParams struct {
	Password   string `json:"password"`
	TargetName string `json:"target_name"`
}

func (q *Queries) UpdateTargetMySQLPassword(ctx context.Context, arg UpdateTargetMySQLPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTargetMySQLPassword, arg.Password, arg.TargetName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTargetPostgreSQLPassword = `-- name: UpdateTargetPostgreSQLPassword :execrows
UPDATE target_postgresql SET password = ? WHERE target_name = ?
`

type UpdateTargetPostgreSQLPasswordParams struct {
	Password   string `json:"password"`
	TargetName string `json:"target_name"`
}

func (q *Queries) UpdateTargetPostgreSQLPassword(ctx context.Context, arg UpdateTargetPostgreSQLPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTargetPostgreSQLPassword, arg.Password, arg.TargetName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTargetS3Secret = `-- name: UpdateTargetS3Secret :execrows
UPDATE target_s3 SET secret = ? WHERE target_name = ?
`

type UpdateTargetS3SecretParams struct {
	Secret     string `json:"secret"`
	TargetName string `json:"target_name"`
}

func (q *Queries) UpdateTargetS3Secret(ctx context.Context, arg UpdateTargetS3SecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTargetS3Secret, arg.Secret, arg.TargetName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertTarget = `-- name: UpsertTarget :exec
INSERT INTO targets (name, target_type, mount_script)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    target_type = excluded.target_type,
    mount_script = excluded.mount_script
`

type UpsertTargetParams struct {
	Name        string `json:"name"`
	TargetType  string `json:"target_type"`
	MountScript string `json:"mount_script"`
}

func (q *Queries) UpsertTarget(ctx context.Context, arg UpsertTargetParams) error {
	_, err := q.db.ExecContext(ctx, upsertTarget, arg.Name, arg.TargetType, arg.MountScript)
	return err
}

const upsertTargetFilesystem = `-- name: UpsertTargetFilesystem :exec
INSERT INTO target_filesystems (
    target_name, access, path, agent_host, volume_id, volume_type, volume_name,
    volume_fs, volume_total_bytes, volume_used_bytes, volume_free_bytes,
    volume_total, volume_used, volume_free
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_name) DO UPDATE SET
    access = excluded.access,
    path = excluded.path,
    agent_host = excluded.agent_host,
    volume_id = excluded.volume_id,
    volume_type = excluded.volume_type,
    volume_name = excluded.volume_name,
    volume_fs = excluded.volume_fs,
    volume_total_bytes = excluded.volume_total_bytes,
    volume_used_bytes = excluded.volume_used_bytes,
    volume_free_bytes = excluded.volume_free_bytes,
    volume_total = excluded.volume_total,
    volume_used = excluded.volume_used,
    volume_free = excluded.volume_free
`

type UpsertTargetFilesystemParams struct {
	TargetName       string         `json:"target_name"`
	Access           string         `json:"access"`
	Path             string         `json:"path"`
	AgentHost        sql.NullString `json:"agent_host"`
	VolumeID         sql.NullString `json:"volume_id"`
	VolumeType       sql.NullString `json:"volume_type"`
	VolumeName       sql.NullString `json:"volume_name"`
	VolumeFs         sql.NullString `json:"volume_fs"`
	VolumeTotalBytes sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes  sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes  sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal      sql.NullString `json:"volume_total"`
	VolumeUsed       sql.NullString `json:"volume_used"`
	VolumeFree       sql.NullString `json:"volume_free"`
}

func (q *Queries) UpsertTargetFilesystem(ctx context.Context, arg UpsertTargetFilesystemParams) error {
	_, err := q.db.ExecContext(ctx, upsertTargetFilesystem,
		arg.TargetName,
		arg.Access,
		arg.Path,
		arg.AgentHost,
		arg.VolumeID,
		arg.VolumeType,
		arg.VolumeName,
		arg.VolumeFs,
		arg.VolumeTotalBytes,
		arg.VolumeUsedBytes,
		arg.VolumeFreeBytes,
		arg.VolumeTotal,
		arg.VolumeUsed,
		arg.VolumeFree,
	)
	return err
}

const upsertTargetLdap = `-- name: UpsertTargetLdap :exec
INSERT INTO target_ldap (
    target_name, host, port, username, tls_mode, ca_certificate, base_dn,
    default_client_dir
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_name) DO UPDATE SET
    host = excluded.host,
    port = excluded.port,
    username = excluded.username,
    tls_mode = excluded.tls_mode,
    ca_certificate = excluded.ca_certificate,
    base_dn = excluded.base_dn,
    default_client_dir = excluded.default_client_dir
`

type UpsertTargetLdapParams struct {
	TargetName       string `json:"target_name"`
	Host             string `json:"host"`
	Port             int64  `json:"port"`
	Username         string `json:"username"`
	TlsMode          string `json:"tls_mode"`
	CaCertificate    string `json:"ca_certificate"`
	BaseDn           string `json:"base_dn"`
	DefaultClientDir string `json:"default_client_dir"`
}

func (q *Queries) UpsertTargetLdap(ctx context.Context, arg UpsertTargetLdapParams) error {
	_, err := q.db.ExecContext(ctx, upsertTargetLdap,
		arg.TargetName,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.TlsMode,
		arg.CaCertificate,
		arg.BaseDn,
		arg.DefaultClientDir,
	)
	return err
}

const upsertTargetMySQL = `-- name: UpsertTargetMySQL :exec
INSERT INTO target_mysql (
    target_name, variant, host, port, username, tls_mode, ca_certificate,
    default_client_family, default_client_dir
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_name) DO UPDATE SET
    variant = excluded.variant,
    host = excluded.host,
    port = excluded.port,
    username = excluded.username,
    tls_mode = excluded.tls_mode,
    ca_certificate = excluded.ca_certificate,
    default_client_family = excluded.default_client_family,
    default_client_dir = excluded.default_client_dir
`

type UpsertTargetMySQLParams struct {
	TargetName          string `json:"target_name"`
	Variant             string `json:"variant"`
	Host                string `json:"host"`
	Port                int64  `json:"port"`
	Username            string `json:"username"`
	TlsMode             string `json:"tls_mode"`
	CaCertificate       string `json:"ca_certificate"`
	DefaultClientFamily string `json:"default_client_family"`
	DefaultClientDir    string `json:"default_client_dir"`
}

func (q *Queries) UpsertTargetMySQL(ctx context.Context, arg UpsertTargetMySQLParams) error {
	_, err := q.db.ExecContext(ctx, upsertTargetMySQL,
		arg.TargetName,
		arg.Variant,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.TlsMode,
		arg.CaCertificate,
		arg.DefaultClientFamily,
		arg.DefaultClientDir,
	)
	return err
}

const upsertTargetPostgreSQL = `-- name: UpsertTargetPostgreSQL :exec
INSERT INTO target_postgresql (
    target_name, host, port, username, ssl_mode, ca_certificate, default_client_dir
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_name) DO UPDATE SET
    host = excluded.host,
    port = excluded.port,
    username = excluded.username,
    ssl_mode = excluded.ssl_mode,
    ca_certificate = excluded.ca_certificate,
    default_client_dir = excluded.default_client_dir
`

type UpsertTargetPostgreSQLParams struct {
	TargetName       string `json:"target_name"`
	Host             string `json:"host"`
	Port             int64  `json:"port"`
	Username         string `json:"username"`
	SslMode          string `json:"ssl_mode"`
	CaCertificate    string `json:"ca_certificate"`
	DefaultClientDir string `json:"default_client_dir"`
}

func (q *Queries) UpsertTargetPostgreSQL(ctx context.Context, arg UpsertTargetPostgreSQLParams) error {
	_, err := q.db.ExecContext(ctx, upsertTargetPostgreSQL,
		arg.TargetName,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.SslMode,
		arg.CaCertificate,
		arg.DefaultClientDir,
	)
	return err
}

const upsertTargetS3 = `-- name: UpsertTargetS3 :exec
INSERT INTO target_s3 (target_name, url)
VALUES (?, ?)
ON CONFLICT(target_name) DO UPDATE SET url = excluded.url
`

type UpsertTargetS3Params struct {
	TargetName string `json:"target_name"`
	Url        string `json:"url"`
}

func (q *Queries) UpsertTargetS3(ctx context.Context, arg UpsertTargetS3Params) error {
	_, err := q.db.ExecContext(ctx, upsertTargetS3, arg.TargetName, arg.Url)
	return err
}
