// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: target_plugins.sql

package corequery

import (
	"context"
	"database/sql"
)

const activateTargetPluginVersion = `-- name: ActivateTargetPluginVersion :execrows
UPDATE target_plugins
SET active_version = ?1
WHERE target_plugins.plugin_id = ?2
  AND EXISTS (
    SELECT 1
    FROM target_plugin_versions
    WHERE target_plugin_versions.plugin_id = target_plugins.plugin_id
      AND target_plugin_versions.version = ?1
  )
`

type ActivateTargetPluginVersionParams struct {
	Version  string `json:"version"`
	PluginID string `json:"plugin_id"`
}

func (q *Queries) ActivateTargetPluginVersion(ctx context.Context, arg ActivateTargetPluginVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateTargetPluginVersion, arg.Version, arg.PluginID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const activateTargetPluginVersionFrom = `-- name: ActivateTargetPluginVersionFrom :execrows
UPDATE target_plugins
SET active_version = ?1
WHERE target_plugins.plugin_id = ?2
  AND active_version = ?3
  AND EXISTS (
    SELECT 1
    FROM target_plugin_versions
    WHERE target_plugin_versions.plugin_id = target_plugins.plugin_id
      AND target_plugin_versions.version = ?1
  )
`

type ActivateTargetPluginVersionFromParams struct {
	ToVersion   string `json:"to_version"`
	PluginID    string `json:"plugin_id"`
	FromVersion string `json:"from_version"`
}

func (q *Queries) ActivateTargetPluginVersionFrom(ctx context.Context, arg ActivateTargetPluginVersionFromParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateTargetPluginVersionFrom, arg.ToVersion, arg.PluginID, arg.FromVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearTargetPluginActivation = `-- name: ClearTargetPluginActivation :execrows
UPDATE target_plugins
SET active_version = ''
WHERE plugin_id = ?
`

func (q *Queries) ClearTargetPluginActivation(ctx context.Context, pluginID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearTargetPluginActivation, pluginID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createTargetPluginRepository = `-- name: CreateTargetPluginRepository :exec
INSERT INTO target_plugin_repositories (id, name, url, public_key, enabled)
VALUES (?, ?, ?, ?, ?)
`

type CreateTargetPluginRepositoryParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Url       string `json:"url"`
	PublicKey []byte `json:"public_key"`
	Enabled   int64  `json:"enabled"`
}

func (q *Queries) CreateTargetPluginRepository(ctx context.Context, arg CreateTargetPluginRepositoryParams) error {
	_, err := q.db.ExecContext(ctx, createTargetPluginRepository,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.PublicKey,
		arg.Enabled,
	)
	return err
}

const createTargetPluginVersion = `-- name: CreateTargetPluginVersion :exec
INSERT INTO target_plugin_versions (
    plugin_id, version, platform, install_path, manifest, artifact_sha256,
    installed_at, health_state, health_message, health_checked_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTargetPluginVersionParams struct {
	PluginID        string        `json:"plugin_id"`
	Version         string        `json:"version"`
	Platform        string        `json:"platform"`
	InstallPath     string        `json:"install_path"`
	Manifest        []byte        `json:"manifest"`
	ArtifactSha256  string        `json:"artifact_sha256"`
	InstalledAt     int64         `json:"installed_at"`
	HealthState     string        `json:"health_state"`
	HealthMessage   string        `json:"health_message"`
	HealthCheckedAt sql.NullInt64 `json:"health_checked_at"`
}

func (q *Queries) CreateTargetPluginVersion(ctx context.Context, arg CreateTargetPluginVersionParams) error {
	_, err := q.db.ExecContext(ctx, createTargetPluginVersion,
		arg.PluginID,
		arg.Version,
		arg.Platform,
		arg.InstallPath,
		arg.Manifest,
		arg.ArtifactSha256,
		arg.InstalledAt,
		arg.HealthState,
		arg.HealthMessage,
		arg.HealthCheckedAt,
	)
	return err
}

const deleteEmptyTargetPlugin = `-- name: DeleteEmptyTargetPlugin :execrows
DELETE FROM target_plugins
WHERE plugin_id = ?
  AND NOT EXISTS (
    SELECT 1
    FROM target_plugin_versions
    WHERE target_plugin_versions.plugin_id = target_plugins.plugin_id
  )
`

func (q *Queries) DeleteEmptyTargetPlugin(ctx context.Context, pluginID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEmptyTargetPlugin, pluginID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteInactiveTargetPluginVersion = `-- name: DeleteInactiveTargetPluginVersion :execrows
DELETE FROM target_plugin_versions
WHERE target_plugin_versions.plugin_id = ?1
  AND target_plugin_versions.version = ?2
  AND NOT EXISTS (
    SELECT 1
    FROM target_plugins
    WHERE target_plugins.plugin_id = target_plugin_versions.plugin_id
      AND target_plugins.active_version = target_plugin_versions.version
  )
`

type DeleteInactiveTargetPluginVersionParams struct {
	PluginID string `json:"plugin_id"`
	Version  string `json:"version"`
}

func (q *Queries) DeleteInactiveTargetPluginVersion(ctx context.Context, arg DeleteInactiveTargetPluginVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInactiveTargetPluginVersion, arg.PluginID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTargetPluginRepository = `-- name: DeleteTargetPluginRepository :execrows
DELETE FROM target_plugin_repositories WHERE id = ?
`

func (q *Queries) DeleteTargetPluginRepository(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTargetPluginRepository, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureTargetPlugin = `-- name: EnsureTargetPlugin :exec
INSERT INTO target_plugins (plugin_id, repository_id, active_version, enabled)
VALUES (?, ?, '', ?)
ON CONFLICT(plugin_id) DO NOTHING
`

type EnsureTargetPluginParams struct {
	PluginID     string `json:"plugin_id"`
	RepositoryID string `json:"repository_id"`
	Enabled      int64  `json:"enabled"`
}

func (q *Queries) EnsureTargetPlugin(ctx context.Context, arg EnsureTargetPluginParams) error {
	_, err := q.db.ExecContext(ctx, ensureTargetPlugin, arg.PluginID, arg.RepositoryID, arg.Enabled)
	return err
}

const getTargetPlugin = `-- name: GetTargetPlugin :one
SELECT plugin_id, repository_id, active_version, enabled
FROM target_plugins
WHERE plugin_id = ?
`

func (q *Queries) GetTargetPlugin(ctx context.Context, pluginID string) (TargetPlugin, error) {
	row := q.db.QueryRowContext(ctx, getTargetPlugin, pluginID)
	var i TargetPlugin
	err := row.Scan(
		&i.PluginID,
		&i.RepositoryID,
		&i.ActiveVersion,
		&i.Enabled,
	)
	return i, err
}

const getTargetPluginRepository = `-- name: GetTargetPluginRepository :one
SELECT id, name, url, public_key, enabled, etag, last_modified, last_refreshed_at, last_error
FROM target_plugin_repositories
WHERE id = ?
`

func (q *Queries) GetTargetPluginRepository(ctx context.Context, id string) (TargetPluginRepository, error) {
	row := q.db.QueryRowContext(ctx, getTargetPluginRepository, id)
	var i TargetPluginRepository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.PublicKey,
		&i.Enabled,
		&i.Etag,
		&i.LastModified,
		&i.LastRefreshedAt,
		&i.LastError,
	)
	return i, err
}

const getTargetPluginVersion = `-- name: GetTargetPluginVersion :one
SELECT plugin_id, version, platform, install_path, manifest, artifact_sha256,
       installed_at, health_state, health_message, health_checked_at
FROM target_plugin_versions
WHERE plugin_id = ?1 AND version = ?2
`

type GetTargetPluginVersionParams struct {
	PluginID string `json:"plugin_id"`
	Version  string `json:"version"`
}

func (q *Queries) GetTargetPluginVersion(ctx context.Context, arg GetTargetPluginVersionParams) (TargetPluginVersion, error) {
	row := q.db.QueryRowContext(ctx, getTargetPluginVersion, arg.PluginID, arg.Version)
	var i TargetPluginVersion
	err := row.Scan(
		&i.PluginID,
		&i.Version,
		&i.Platform,
		&i.InstallPath,
		&i.Manifest,
		&i.ArtifactSha256,
		&i.InstalledAt,
		&i.HealthState,
		&i.HealthMessage,
		&i.HealthCheckedAt,
	)
	return i, err
}

const listTargetPluginRepositories = `-- name: ListTargetPluginRepositories :many
SELECT id, name, url, public_key, enabled, etag, last_modified, last_refreshed_at, last_error
FROM target_plugin_repositories
ORDER BY name, id
`

func (q *Queries) ListTargetPluginRepositories(ctx context.Context) ([]TargetPluginRepository, error) {
	rows, err := q.db.QueryContext(ctx, listTargetPluginRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TargetPluginRepository{}
	for rows.Next() {
		var i TargetPluginRepository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.PublicKey,
			&i.Enabled,
			&i.Etag,
			&i.LastModified,
			&i.LastRefreshedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetPluginVersions = `-- name: ListTargetPluginVersions :many
SELECT plugin_id, version, platform, install_path, manifest, artifact_sha256,
       installed_at, health_state, health_message, health_checked_at
FROM target_plugin_versions
WHERE plugin_id = ?
ORDER BY installed_at DESC, version DESC
`

func (q *Queries) ListTargetPluginVersions(ctx context.Context, pluginID string) ([]TargetPluginVersion, error) {
	rows, err := q.db.QueryContext(ctx, listTargetPluginVersions, pluginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TargetPluginVersion{}
	for rows.Next() {
		var i TargetPluginVersion
		if err := rows.Scan(
			&i.PluginID,
			&i.Version,
			&i.Platform,
			&i.InstallPath,
			&i.Manifest,
			&i.ArtifactSha256,
			&i.InstalledAt,
			&i.HealthState,
			&i.HealthMessage,
			&i.HealthCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetPlugins = `-- name: ListTargetPlugins :many
SELECT plugin_id, repository_id, active_version, enabled
FROM target_plugins
ORDER BY plugin_id
`

func (q *Queries) ListTargetPlugins(ctx context.Context) ([]TargetPlugin, error) {
	rows, err := q.db.QueryContext(ctx, listTargetPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TargetPlugin{}
	for rows.Next() {
		var i TargetPlugin
		if err := rows.Scan(
			&i.PluginID,
			&i.RepositoryID,
			&i.ActiveVersion,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTargetPluginEnabled = `-- name: SetTargetPluginEnabled :execrows
UPDATE target_plugins
SET enabled = ?1
WHERE plugin_id = ?2
`

type SetTargetPluginEnabledParams struct {
	Enabled  int64  `json:"enabled"`
	PluginID string `json:"plugin_id"`
}

func (q *Queries) SetTargetPluginEnabled(ctx context.Context, arg SetTargetPluginEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTargetPluginEnabled, arg.Enabled, arg.PluginID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTargetPluginRepositoryEnabled = `-- name: SetTargetPluginRepositoryEnabled :execrows
UPDATE target_plugin_repositories
SET enabled = ?1
WHERE id = ?2
`

type SetTargetPluginRepositoryEnabledParams struct {
	Enabled int64  `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) SetTargetPluginRepositoryEnabled(ctx context.Context, arg SetTargetPluginRepositoryEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTargetPluginRepositoryEnabled, arg.Enabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTargetPluginRepository = `-- name: UpdateTargetPluginRepository :execrows
UPDATE target_plugin_repositories
SET name = ?1, url = ?2
WHERE id = ?3
`

type UpdateTargetPluginRepositoryParams struct {
	Name string `json:"name"`
	Url  string `json:"url"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateTargetPluginRepository(ctx context.Context, arg UpdateTargetPluginRepositoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTargetPluginRepository, arg.Name, arg.Url, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTargetPluginRepositoryRefresh = `-- name: UpdateTargetPluginRepositoryRefresh :execrows
UPDATE target_plugin_repositories
SET etag = ?1,
    last_modified = ?2,
    last_refreshed_at = ?3,
    last_error = ?4
WHERE id = ?5
`

type UpdateTargetPluginRepositoryRefreshParams struct {
	Etag            string        `json:"etag"`
	LastModified    string        `json:"last_modified"`
	LastRefreshedAt sql.NullInt64 `json:"last_refreshed_at"`
	LastError       string        `json:"last_error"`
	ID              string        `json:"id"`
}

func (q *Queries) UpdateTargetPluginRepositoryRefresh(ctx context.Context, arg UpdateTargetPluginRepositoryRefreshParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTargetPluginRepositoryRefresh,
		arg.Etag,
		arg.LastModified,
		arg.LastRefreshedAt,
		arg.LastError,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTargetPluginVersionHealth = `-- name: UpdateTargetPluginVersionHealth :execrows
UPDATE target_plugin_versions
SET health_state = ?1,
    health_message = ?2,
    health_checked_at = ?3
WHERE plugin_id = ?4 AND version = ?5
`

type UpdateTargetPluginVersionHealthParams struct {
	HealthState     string        `json:"health_state"`
	HealthMessage   string        `json:"health_message"`
	HealthCheckedAt sql.NullInt64 `json:"health_checked_at"`
	PluginID        string        `json:"plugin_id"`
	Version         string        `json:"version"`
}

func (q *Queries) UpdateTargetPluginVersionHealth(ctx context.Context, arg UpdateTargetPluginVersionHealthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTargetPluginVersionHealth,
		arg.HealthState,
		arg.HealthMessage,
		arg.HealthCheckedAt,
		arg.PluginID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
