// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: targets.sql

package corequery

import (
	"context"
	"database/sql"
)

const createTarget = `-- name: CreateTarget :exec
INSERT INTO targets (name, target_type, mount_script)
VALUES (?, ?, ?)
`

type CreateTargetParams struct {
	Name        string `json:"name"`
	TargetType  string `json:"target_type"`
	MountScript string `json:"mount_script"`
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) error {
	_, err := q.db.ExecContext(ctx, createTarget, arg.Name, arg.TargetType, arg.MountScript)
	return err
}

const deleteTarget = `-- name: DeleteTarget :execrows
DELETE FROM targets WHERE name = ?
`

func (q *Queries) DeleteTarget(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTarget, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTargetFilesystem = `-- name: DeleteTargetFilesystem :exec
DELETE FROM target_filesystems WHERE target_name = ?
`

func (q *Queries) DeleteTargetFilesystem(ctx context.Context, targetName string) error {
	_, err := q.db.ExecContext(ctx, deleteTargetFilesystem, targetName)
	return err
}

const deleteTargetS3 = `-- name: DeleteTargetS3 :exec
DELETE FROM target_s3 WHERE target_name = ?
`

func (q *Queries) DeleteTargetS3(ctx context.Context, targetName string) error {
	_, err := q.db.ExecContext(ctx, deleteTargetS3, targetName)
	return err
}

const getTarget = `-- name: GetTarget :one
SELECT
    t.name, t.target_type, t.mount_script,
    COALESCE(f.access, '') AS filesystem_access,
    COALESCE(f.path, s.url, '') AS path,
    f.agent_host, f.volume_id, f.volume_type, f.volume_name,
    f.volume_fs, f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
    f.volume_total, f.volume_used, f.volume_free,
    COUNT(j.id) AS job_count,
    ah.name AS agent_name, ah.ip AS agent_ip, ah.auth AS agent_auth,
    ah.token_used AS agent_token_used, ah.os AS agent_os
FROM targets t
LEFT JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN target_s3 s ON s.target_name = t.name
LEFT JOIN backups j ON t.name = j.target
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
WHERE t.name = ?
GROUP BY t.name
`

type GetTargetRow struct {
	Name             string         `json:"name"`
	TargetType       string         `json:"target_type"`
	MountScript      string         `json:"mount_script"`
	FilesystemAccess string         `json:"filesystem_access"`
	Path             string         `json:"path"`
	AgentHost        sql.NullString `json:"agent_host"`
	VolumeID         sql.NullString `json:"volume_id"`
	VolumeType       sql.NullString `json:"volume_type"`
	VolumeName       sql.NullString `json:"volume_name"`
	VolumeFs         sql.NullString `json:"volume_fs"`
	VolumeTotalBytes sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes  sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes  sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal      sql.NullString `json:"volume_total"`
	VolumeUsed       sql.NullString `json:"volume_used"`
	VolumeFree       sql.NullString `json:"volume_free"`
	JobCount         int64          `json:"job_count"`
	AgentName        sql.NullString `json:"agent_name"`
	AgentIp          sql.NullString `json:"agent_ip"`
	AgentAuth        sql.NullString `json:"agent_auth"`
	AgentTokenUsed   sql.NullString `json:"agent_token_used"`
	AgentOs          sql.NullString `json:"agent_os"`
}

func (q *Queries) GetTarget(ctx context.Context, name string) (GetTargetRow, error) {
	row := q.db.QueryRowContext(ctx, getTarget, name)
	var i GetTargetRow
	err := row.Scan(
		&i.Name,
		&i.TargetType,
		&i.MountScript,
		&i.FilesystemAccess,
		&i.Path,
		&i.AgentHost,
		&i.VolumeID,
		&i.VolumeType,
		&i.VolumeName,
		&i.VolumeFs,
		&i.VolumeTotalBytes,
		&i.VolumeUsedBytes,
		&i.VolumeFreeBytes,
		&i.VolumeTotal,
		&i.VolumeUsed,
		&i.VolumeFree,
		&i.JobCount,
		&i.AgentName,
		&i.AgentIp,
		&i.AgentAuth,
		&i.AgentTokenUsed,
		&i.AgentOs,
	)
	return i, err
}

const getTargetS3Secret = `-- name: GetTargetS3Secret :one
SELECT secret FROM target_s3 WHERE target_name = ?
`

func (q *Queries) GetTargetS3Secret(ctx context.Context, targetName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTargetS3Secret, targetName)
	var secret string
	err := row.Scan(&secret)
	return secret, err
}

const listAllTargets = `-- name: ListAllTargets :many
SELECT
    t.name, t.target_type, t.mount_script,
    COALESCE(f.access, '') AS filesystem_access,
    COALESCE(f.path, s.url, '') AS path,
    f.agent_host, f.volume_id, f.volume_type, f.volume_name,
    f.volume_fs, f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
    f.volume_total, f.volume_used, f.volume_free,
    COUNT(j.id) AS job_count,
    ah.name AS agent_name, ah.ip AS agent_ip, ah.auth AS agent_auth,
    ah.token_used AS agent_token_used, ah.os AS agent_os
FROM targets t
LEFT JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN target_s3 s ON s.target_name = t.name
LEFT JOIN backups j ON t.name = j.target
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
GROUP BY t.name, t.target_type, t.mount_script, f.access, f.path, s.url,
         f.agent_host, f.volume_id, f.volume_type, f.volume_name, f.volume_fs,
         f.volume_total_bytes, f.volume_used_bytes, f.volume_free_bytes,
         f.volume_total, f.volume_used, f.volume_free,
         ah.name, ah.ip, ah.auth, ah.token_used, ah.os
ORDER BY t.name
`

type ListAllTargetsRow struct {
	Name             string         `json:"name"`
	TargetType       string         `json:"target_type"`
	MountScript      string         `json:"mount_script"`
	FilesystemAccess string         `json:"filesystem_access"`
	Path             string         `json:"path"`
	AgentHost        sql.NullString `json:"agent_host"`
	VolumeID         sql.NullString `json:"volume_id"`
	VolumeType       sql.NullString `json:"volume_type"`
	VolumeName       sql.NullString `json:"volume_name"`
	VolumeFs         sql.NullString `json:"volume_fs"`
	VolumeTotalBytes sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes  sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes  sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal      sql.NullString `json:"volume_total"`
	VolumeUsed       sql.NullString `json:"volume_used"`
	VolumeFree       sql.NullString `json:"volume_free"`
	JobCount         int64          `json:"job_count"`
	AgentName        sql.NullString `json:"agent_name"`
	AgentIp          sql.NullString `json:"agent_ip"`
	AgentAuth        sql.NullString `json:"agent_auth"`
	AgentTokenUsed   sql.NullString `json:"agent_token_used"`
	AgentOs          sql.NullString `json:"agent_os"`
}

func (q *Queries) ListAllTargets(ctx context.Context) ([]ListAllTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTargetsRow{}
	for rows.Next() {
		var i ListAllTargetsRow
		if err := rows.Scan(
			&i.Name,
			&i.TargetType,
			&i.MountScript,
			&i.FilesystemAccess,
			&i.Path,
			&i.AgentHost,
			&i.VolumeID,
			&i.VolumeType,
			&i.VolumeName,
			&i.VolumeFs,
			&i.VolumeTotalBytes,
			&i.VolumeUsedBytes,
			&i.VolumeFreeBytes,
			&i.VolumeTotal,
			&i.VolumeUsed,
			&i.VolumeFree,
			&i.JobCount,
			&i.AgentName,
			&i.AgentIp,
			&i.AgentAuth,
			&i.AgentTokenUsed,
			&i.AgentOs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsByAgentHost = `-- name: ListTargetsByAgentHost :many
SELECT
    t.name, t.target_type, t.mount_script,
    f.access AS filesystem_access, f.path, f.agent_host, f.volume_id,
    f.volume_type, f.volume_name, f.volume_fs, f.volume_total_bytes,
    f.volume_used_bytes, f.volume_free_bytes, f.volume_total, f.volume_used,
    f.volume_free,
    ah.name AS agent_name, ah.ip AS agent_ip, ah.auth AS agent_auth,
    ah.token_used AS agent_token_used, ah.os AS agent_os
FROM targets t
JOIN target_filesystems f ON f.target_name = t.name
LEFT JOIN agent_hosts ah ON f.agent_host = ah.name
WHERE f.agent_host = ?
ORDER BY t.name
`

type ListTargetsByAgentHostRow struct {
	Name             string         `json:"name"`
	TargetType       string         `json:"target_type"`
	MountScript      string         `json:"mount_script"`
	FilesystemAccess string         `json:"filesystem_access"`
	Path             string         `json:"path"`
	AgentHost        sql.NullString `json:"agent_host"`
	VolumeID         sql.NullString `json:"volume_id"`
	VolumeType       sql.NullString `json:"volume_type"`
	VolumeName       sql.NullString `json:"volume_name"`
	VolumeFs         sql.NullString `json:"volume_fs"`
	VolumeTotalBytes sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes  sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes  sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal      sql.NullString `json:"volume_total"`
	VolumeUsed       sql.NullString `json:"volume_used"`
	VolumeFree       sql.NullString `json:"volume_free"`
	AgentName        sql.NullString `json:"agent_name"`
	AgentIp          sql.NullString `json:"agent_ip"`
	AgentAuth        sql.NullString `json:"agent_auth"`
	AgentTokenUsed   sql.NullString `json:"agent_token_used"`
	AgentOs          sql.NullString `json:"agent_os"`
}

func (q *Queries) ListTargetsByAgentHost(ctx context.Context, agentHost sql.NullString) ([]ListTargetsByAgentHostRow, error) {
	rows, err := q.db.QueryContext(ctx, listTargetsByAgentHost, agentHost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTargetsByAgentHostRow{}
	for rows.Next() {
		var i ListTargetsByAgentHostRow
		if err := rows.Scan(
			&i.Name,
			&i.TargetType,
			&i.MountScript,
			&i.FilesystemAccess,
			&i.Path,
			&i.AgentHost,
			&i.VolumeID,
			&i.VolumeType,
			&i.VolumeName,
			&i.VolumeFs,
			&i.VolumeTotalBytes,
			&i.VolumeUsedBytes,
			&i.VolumeFreeBytes,
			&i.VolumeTotal,
			&i.VolumeUsed,
			&i.VolumeFree,
			&i.AgentName,
			&i.AgentIp,
			&i.AgentAuth,
			&i.AgentTokenUsed,
			&i.AgentOs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const targetExists = `-- name: TargetExists :one
SELECT 1 FROM targets WHERE name = ? LIMIT 1
`

func (q *Queries) TargetExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, targetExists, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateTarget = `-- name: UpdateTarget :exec
UPDATE targets
SET target_type = ?, mount_script = ?
WHERE name = ?
`

type UpdateTargetParams struct {
	TargetType  string `json:"target_type"`
	MountScript string `json:"mount_script"`
	Name        string `json:"name"`
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateTarget, arg.TargetType, arg.MountScript, arg.Name)
	return err
}

const updateTargetS3Secret = `-- name: UpdateTargetS3Secret :execrows
UPDATE target_s3 SET secret = ? WHERE target_name = ?
`

type UpdateTargetS3SecretParams struct {
	Secret     string `json:"secret"`
	TargetName string `json:"target_name"`
}

func (q *Queries) UpdateTargetS3Secret(ctx context.Context, arg UpdateTargetS3SecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTargetS3Secret, arg.Secret, arg.TargetName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertTarget = `-- name: UpsertTarget :exec
INSERT INTO targets (name, target_type, mount_script)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    target_type = excluded.target_type,
    mount_script = excluded.mount_script
`

type UpsertTargetParams struct {
	Name        string `json:"name"`
	TargetType  string `json:"target_type"`
	MountScript string `json:"mount_script"`
}

func (q *Queries) UpsertTarget(ctx context.Context, arg UpsertTargetParams) error {
	_, err := q.db.ExecContext(ctx, upsertTarget, arg.Name, arg.TargetType, arg.MountScript)
	return err
}

const upsertTargetFilesystem = `-- name: UpsertTargetFilesystem :exec
INSERT INTO target_filesystems (
    target_name, access, path, agent_host, volume_id, volume_type, volume_name,
    volume_fs, volume_total_bytes, volume_used_bytes, volume_free_bytes,
    volume_total, volume_used, volume_free
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_name) DO UPDATE SET
    access = excluded.access,
    path = excluded.path,
    agent_host = excluded.agent_host,
    volume_id = excluded.volume_id,
    volume_type = excluded.volume_type,
    volume_name = excluded.volume_name,
    volume_fs = excluded.volume_fs,
    volume_total_bytes = excluded.volume_total_bytes,
    volume_used_bytes = excluded.volume_used_bytes,
    volume_free_bytes = excluded.volume_free_bytes,
    volume_total = excluded.volume_total,
    volume_used = excluded.volume_used,
    volume_free = excluded.volume_free
`

type UpsertTargetFilesystemParams struct {
	TargetName       string         `json:"target_name"`
	Access           string         `json:"access"`
	Path             string         `json:"path"`
	AgentHost        sql.NullString `json:"agent_host"`
	VolumeID         sql.NullString `json:"volume_id"`
	VolumeType       sql.NullString `json:"volume_type"`
	VolumeName       sql.NullString `json:"volume_name"`
	VolumeFs         sql.NullString `json:"volume_fs"`
	VolumeTotalBytes sql.NullInt64  `json:"volume_total_bytes"`
	VolumeUsedBytes  sql.NullInt64  `json:"volume_used_bytes"`
	VolumeFreeBytes  sql.NullInt64  `json:"volume_free_bytes"`
	VolumeTotal      sql.NullString `json:"volume_total"`
	VolumeUsed       sql.NullString `json:"volume_used"`
	VolumeFree       sql.NullString `json:"volume_free"`
}

func (q *Queries) UpsertTargetFilesystem(ctx context.Context, arg UpsertTargetFilesystemParams) error {
	_, err := q.db.ExecContext(ctx, upsertTargetFilesystem,
		arg.TargetName,
		arg.Access,
		arg.Path,
		arg.AgentHost,
		arg.VolumeID,
		arg.VolumeType,
		arg.VolumeName,
		arg.VolumeFs,
		arg.VolumeTotalBytes,
		arg.VolumeUsedBytes,
		arg.VolumeFreeBytes,
		arg.VolumeTotal,
		arg.VolumeUsed,
		arg.VolumeFree,
	)
	return err
}

const upsertTargetS3 = `-- name: UpsertTargetS3 :exec
INSERT INTO target_s3 (target_name, url)
VALUES (?, ?)
ON CONFLICT(target_name) DO UPDATE SET url = excluded.url
`

type UpsertTargetS3Params struct {
	TargetName string `json:"target_name"`
	Url        string `json:"url"`
}

func (q *Queries) UpsertTargetS3(ctx context.Context, arg UpsertTargetS3Params) error {
	_, err := q.db.ExecContext(ctx, upsertTargetS3, arg.TargetName, arg.Url)
	return err
}
