name: Initialize PBS Plus
description: Create datastore and backup job, generate token

outputs:
  plus-token:
    description: PBS Plus authentication token
    value: ${{ steps.get-token.outputs.token }}

runs:
  using: composite
  steps:
    - name: Create datastore and backup job
      shell: bash
      run: |
        docker exec pbs-plus-test proxmox-backup-manager datastore create test /mnt/test
        docker exec pbs-plus-test curl -k -X POST "https://localhost:8017/api2/extjs/config/disk-backup" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "id=test-backup-job" \
          -d "target=test-host - Root" \
          -d "subpath=/test-backup" \
          -d "store=test" \
          -d "ns=test" \
          -d "schedule=" \
          -d "retry=" \
          -d "retry-interval=" \
          -d "max-dir-entries=" \
          -d "mode=" \
          -d "sourcemode=" \
          -d "readmode=" \
          -d "include-xattr=" \
          -d "comment=" \
          -d "rawexclusions=" \
          -d "pre_script=" \
          -d "post_script="

    - name: Generate token
      shell: bash
      run: |
        docker exec pbs-plus-test curl -k -X POST "https://localhost:8017/api2/extjs/config/d2d-token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "comment=test-backup"

    - name: Get token
      id: get-token
      shell: bash
      run: |
        # Run curl inside docker and capture the output
        PLUS_TOKEN=$(docker exec pbs-plus-test curl -k -s "https://localhost:8017/api2/json/d2d/token" -H "Accept: application/json" | jq -r '.data[0].token')

        if [ -z "$PLUS_TOKEN" ] || [ "$PLUS_TOKEN" = "null" ]; then
          echo "PLUS_TOKEN is empty or null; failing the job."
          exit 1
        fi

        echo "token=${PLUS_TOKEN}" >> "$GITHUB_OUTPUT"
