// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: changers_drives.sql

package mtfquery

import (
	"context"
	"database/sql"
)

const createChanger = `-- name: CreateChanger :exec
INSERT INTO mtf_changers (name, device, comment) VALUES (?, ?, ?)
`

type CreateChangerParams struct {
	Name    string         `json:"name"`
	Device  string         `json:"device"`
	Comment sql.NullString `json:"comment"`
}

func (q *Queries) CreateChanger(ctx context.Context, arg CreateChangerParams) error {
	_, err := q.db.ExecContext(ctx, createChanger, arg.Name, arg.Device, arg.Comment)
	return err
}

const createDrive = `-- name: CreateDrive :exec
INSERT INTO mtf_drives (name, device, changer, drive_index, comment)
VALUES (?, ?, ?, ?, ?)
`

type CreateDriveParams struct {
	Name       string         `json:"name"`
	Device     string         `json:"device"`
	Changer    sql.NullString `json:"changer"`
	DriveIndex sql.NullInt64  `json:"drive_index"`
	Comment    sql.NullString `json:"comment"`
}

func (q *Queries) CreateDrive(ctx context.Context, arg CreateDriveParams) error {
	_, err := q.db.ExecContext(ctx, createDrive,
		arg.Name,
		arg.Device,
		arg.Changer,
		arg.DriveIndex,
		arg.Comment,
	)
	return err
}

const deleteChanger = `-- name: DeleteChanger :execrows
DELETE FROM mtf_changers WHERE name = ?
`

func (q *Queries) DeleteChanger(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChanger, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDrive = `-- name: DeleteDrive :execrows
DELETE FROM mtf_drives WHERE name = ?
`

func (q *Queries) DeleteDrive(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDrive, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChanger = `-- name: GetChanger :one
SELECT name, device, comment, created_at FROM mtf_changers WHERE name = ? LIMIT 1
`

func (q *Queries) GetChanger(ctx context.Context, name string) (MtfChanger, error) {
	row := q.db.QueryRowContext(ctx, getChanger, name)
	var i MtfChanger
	err := row.Scan(
		&i.Name,
		&i.Device,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getDrive = `-- name: GetDrive :one
SELECT name, device, changer, drive_index, comment, created_at FROM mtf_drives WHERE name = ? LIMIT 1
`

func (q *Queries) GetDrive(ctx context.Context, name string) (MtfDrife, error) {
	row := q.db.QueryRowContext(ctx, getDrive, name)
	var i MtfDrife
	err := row.Scan(
		&i.Name,
		&i.Device,
		&i.Changer,
		&i.DriveIndex,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listChangers = `-- name: ListChangers :many
SELECT name, device, comment, created_at FROM mtf_changers ORDER BY name
`

func (q *Queries) ListChangers(ctx context.Context) ([]MtfChanger, error) {
	rows, err := q.db.QueryContext(ctx, listChangers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MtfChanger{}
	for rows.Next() {
		var i MtfChanger
		if err := rows.Scan(
			&i.Name,
			&i.Device,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrives = `-- name: ListDrives :many
SELECT name, device, changer, drive_index, comment, created_at FROM mtf_drives ORDER BY name
`

func (q *Queries) ListDrives(ctx context.Context) ([]MtfDrife, error) {
	rows, err := q.db.QueryContext(ctx, listDrives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MtfDrife{}
	for rows.Next() {
		var i MtfDrife
		if err := rows.Scan(
			&i.Name,
			&i.Device,
			&i.Changer,
			&i.DriveIndex,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChanger = `-- name: UpdateChanger :exec
UPDATE mtf_changers SET device = ?, comment = ? WHERE name = ?
`

type UpdateChangerParams struct {
	Device  string         `json:"device"`
	Comment sql.NullString `json:"comment"`
	Name    string         `json:"name"`
}

func (q *Queries) UpdateChanger(ctx context.Context, arg UpdateChangerParams) error {
	_, err := q.db.ExecContext(ctx, updateChanger, arg.Device, arg.Comment, arg.Name)
	return err
}

const updateDrive = `-- name: UpdateDrive :exec
UPDATE mtf_drives SET device = ?, changer = ?, drive_index = ?, comment = ?
WHERE name = ?
`

type UpdateDriveParams struct {
	Device     string         `json:"device"`
	Changer    sql.NullString `json:"changer"`
	DriveIndex sql.NullInt64  `json:"drive_index"`
	Comment    sql.NullString `json:"comment"`
	Name       string         `json:"name"`
}

func (q *Queries) UpdateDrive(ctx context.Context, arg UpdateDriveParams) error {
	_, err := q.db.ExecContext(ctx, updateDrive,
		arg.Device,
		arg.Changer,
		arg.DriveIndex,
		arg.Comment,
		arg.Name,
	)
	return err
}
