// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mtfquery

import (
	"database/sql"
)

type DataSet struct {
	ID             int64          `json:"id"`
	MediaFamilyID  int64          `json:"media_family_id"`
	SetNumber      sql.NullInt64  `json:"set_number"`
	Name           sql.NullString `json:"name"`
	Description    sql.NullString `json:"description"`
	Owner          sql.NullString `json:"owner"`
	MachineName    sql.NullString `json:"machine_name"`
	WriteTime      sql.NullInt64  `json:"write_time"`
	NumDirectories sql.NullInt64  `json:"num_directories"`
	NumFiles       sql.NullInt64  `json:"num_files"`
	NumCorrupt     sql.NullInt64  `json:"num_corrupt"`
	Size           sql.NullInt64  `json:"size"`
	FirstMediaSeq  sql.NullInt64  `json:"first_media_seq"`
}

type DataSetVolume struct {
	ID              int64          `json:"id"`
	DataSetID       int64          `json:"data_set_id"`
	Device          sql.NullString `json:"device"`
	VolumeLabel     sql.NullString `json:"volume_label"`
	MachineName     sql.NullString `json:"machine_name"`
	MappedNamespace sql.NullString `json:"mapped_namespace"`
}

type MediaFamily struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	TotalTapes  sql.NullInt64  `json:"total_tapes"`
	HasCatalog  sql.NullInt64  `json:"has_catalog"`
	LastScanned sql.NullInt64  `json:"last_scanned"`
	CreatedAt   sql.NullInt64  `json:"created_at"`
}

type MtfCartridge struct {
	Barcode         string         `json:"barcode"`
	Label           sql.NullString `json:"label"`
	MediaFamilyID   int64          `json:"media_family_id"`
	Sequence        sql.NullInt64  `json:"sequence"`
	Role            sql.NullString `json:"role"`
	CatalogType     sql.NullInt64  `json:"catalog_type"`
	IsBkfFile       sql.NullInt64  `json:"is_bkf_file"`
	SourcePath      sql.NullString `json:"source_path"`
	Volumes         sql.NullInt64  `json:"volumes"`
	Directories     sql.NullInt64  `json:"directories"`
	Files           sql.NullInt64  `json:"files"`
	EmptyFiles      sql.NullInt64  `json:"empty_files"`
	FileBytes       sql.NullInt64  `json:"file_bytes"`
	SparseFiles     sql.NullInt64  `json:"sparse_files"`
	CompressedFiles sql.NullInt64  `json:"compressed_files"`
	EncryptedFiles  sql.NullInt64  `json:"encrypted_files"`
	HasCatalog      sql.NullInt64  `json:"has_catalog"`
	CatalogBytes    sql.NullInt64  `json:"catalog_bytes"`
	SetsClosed      sql.NullInt64  `json:"sets_closed"`
	Status          sql.NullString `json:"status"`
	LastScanned     sql.NullInt64  `json:"last_scanned"`
	CreatedAt       sql.NullInt64  `json:"created_at"`
}

type MtfChanger struct {
	Name      string         `json:"name"`
	Device    string         `json:"device"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt sql.NullInt64  `json:"created_at"`
}

type MtfDrife struct {
	Name       string         `json:"name"`
	Device     string         `json:"device"`
	Changer    sql.NullString `json:"changer"`
	DriveIndex sql.NullInt64  `json:"drive_index"`
	Comment    sql.NullString `json:"comment"`
	CreatedAt  sql.NullInt64  `json:"created_at"`
}

type MtfInventoryRun struct {
	ID          int64          `json:"id"`
	Changer     sql.NullString `json:"changer"`
	StartedAt   sql.NullInt64  `json:"started_at"`
	CompletedAt sql.NullInt64  `json:"completed_at"`
	Status      sql.NullString `json:"status"`
	Cartridges  sql.NullInt64  `json:"cartridges"`
	Message     sql.NullString `json:"message"`
}

type MtfJob struct {
	ID                    string         `json:"id"`
	SourceKind            string         `json:"source_kind"`
	SourceRef             string         `json:"source_ref"`
	Datastore             string         `json:"datastore"`
	Namespace             sql.NullString `json:"namespace"`
	Schedule              sql.NullString `json:"schedule"`
	Comment               sql.NullString `json:"comment"`
	NotificationMode      sql.NullString `json:"notification_mode"`
	Spanning              sql.NullInt64  `json:"spanning"`
	OverwriteMappings     sql.NullInt64  `json:"overwrite_mappings"`
	Changer               sql.NullString `json:"changer"`
	Drive                 sql.NullString `json:"drive"`
	CurrentPid            sql.NullString `json:"current_pid"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	Retry                 sql.NullInt64  `json:"retry"`
	RetryInterval         sql.NullInt64  `json:"retry_interval"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	Duration              sql.NullInt64  `json:"duration"`
	CreatedAt             sql.NullInt64  `json:"created_at"`
}

type NamespaceMapping struct {
	ID         int64          `json:"id"`
	Name       sql.NullString `json:"name"`
	Priority   sql.NullInt64  `json:"priority"`
	MatchRegex sql.NullString `json:"match_regex"`
	Template   string         `json:"template"`
	IsDefault  sql.NullInt64  `json:"is_default"`
	Enabled    sql.NullInt64  `json:"enabled"`
	Comment    sql.NullString `json:"comment"`
	CreatedAt  sql.NullInt64  `json:"created_at"`
}
