// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cartridges_inventory.sql

package mtfquery

import (
	"context"
	"database/sql"
)

const cartridgeExists = `-- name: CartridgeExists :one
SELECT 1 FROM mtf_cartridges WHERE barcode = ? LIMIT 1
`

func (q *Queries) CartridgeExists(ctx context.Context, barcode string) (int64, error) {
	row := q.db.QueryRowContext(ctx, cartridgeExists, barcode)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const completeInventoryRun = `-- name: CompleteInventoryRun :exec
UPDATE mtf_inventory_runs
SET completed_at = ?, status = ?, cartridges = ?, message = ?
WHERE id = ?
`

type CompleteInventoryRunParams struct {
	CompletedAt sql.NullInt64  `json:"completed_at"`
	Status      sql.NullString `json:"status"`
	Cartridges  sql.NullInt64  `json:"cartridges"`
	Message     sql.NullString `json:"message"`
	ID          int64          `json:"id"`
}

func (q *Queries) CompleteInventoryRun(ctx context.Context, arg CompleteInventoryRunParams) error {
	_, err := q.db.ExecContext(ctx, completeInventoryRun,
		arg.CompletedAt,
		arg.Status,
		arg.Cartridges,
		arg.Message,
		arg.ID,
	)
	return err
}

const createInventoryRun = `-- name: CreateInventoryRun :execlastid
INSERT INTO mtf_inventory_runs (changer, started_at, status) VALUES (?, ?, 'running')
`

type CreateInventoryRunParams struct {
	Changer   sql.NullString `json:"changer"`
	StartedAt sql.NullInt64  `json:"started_at"`
}

func (q *Queries) CreateInventoryRun(ctx context.Context, arg CreateInventoryRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createInventoryRun, arg.Changer, arg.StartedAt)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteCartridge = `-- name: DeleteCartridge :execrows
DELETE FROM mtf_cartridges WHERE barcode = ?
`

func (q *Queries) DeleteCartridge(ctx context.Context, barcode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCartridge, barcode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCartridge = `-- name: GetCartridge :one
SELECT barcode, label, media_family_id, sequence, role, catalog_type, is_bkf_file, source_path, volumes, directories, files, empty_files, file_bytes, sparse_files, compressed_files, encrypted_files, has_catalog, catalog_bytes, sets_closed, status, last_scanned, created_at FROM mtf_cartridges WHERE barcode = ? LIMIT 1
`

func (q *Queries) GetCartridge(ctx context.Context, barcode string) (MtfCartridge, error) {
	row := q.db.QueryRowContext(ctx, getCartridge, barcode)
	var i MtfCartridge
	err := row.Scan(
		&i.Barcode,
		&i.Label,
		&i.MediaFamilyID,
		&i.Sequence,
		&i.Role,
		&i.CatalogType,
		&i.IsBkfFile,
		&i.SourcePath,
		&i.Volumes,
		&i.Directories,
		&i.Files,
		&i.EmptyFiles,
		&i.FileBytes,
		&i.SparseFiles,
		&i.CompressedFiles,
		&i.EncryptedFiles,
		&i.HasCatalog,
		&i.CatalogBytes,
		&i.SetsClosed,
		&i.Status,
		&i.LastScanned,
		&i.CreatedAt,
	)
	return i, err
}

const getInventoryRun = `-- name: GetInventoryRun :one
SELECT id, changer, started_at, completed_at, status, cartridges, message FROM mtf_inventory_runs WHERE id = ? LIMIT 1
`

func (q *Queries) GetInventoryRun(ctx context.Context, id int64) (MtfInventoryRun, error) {
	row := q.db.QueryRowContext(ctx, getInventoryRun, id)
	var i MtfInventoryRun
	err := row.Scan(
		&i.ID,
		&i.Changer,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.Cartridges,
		&i.Message,
	)
	return i, err
}

const listCartridges = `-- name: ListCartridges :many
SELECT barcode, label, media_family_id, sequence, role, catalog_type, is_bkf_file, source_path, volumes, directories, files, empty_files, file_bytes, sparse_files, compressed_files, encrypted_files, has_catalog, catalog_bytes, sets_closed, status, last_scanned, created_at FROM mtf_cartridges ORDER BY media_family_id, sequence
`

func (q *Queries) ListCartridges(ctx context.Context) ([]MtfCartridge, error) {
	rows, err := q.db.QueryContext(ctx, listCartridges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MtfCartridge{}
	for rows.Next() {
		var i MtfCartridge
		if err := rows.Scan(
			&i.Barcode,
			&i.Label,
			&i.MediaFamilyID,
			&i.Sequence,
			&i.Role,
			&i.CatalogType,
			&i.IsBkfFile,
			&i.SourcePath,
			&i.Volumes,
			&i.Directories,
			&i.Files,
			&i.EmptyFiles,
			&i.FileBytes,
			&i.SparseFiles,
			&i.CompressedFiles,
			&i.EncryptedFiles,
			&i.HasCatalog,
			&i.CatalogBytes,
			&i.SetsClosed,
			&i.Status,
			&i.LastScanned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartridgesByFamily = `-- name: ListCartridgesByFamily :many
SELECT barcode, label, media_family_id, sequence, role, catalog_type, is_bkf_file, source_path, volumes, directories, files, empty_files, file_bytes, sparse_files, compressed_files, encrypted_files, has_catalog, catalog_bytes, sets_closed, status, last_scanned, created_at FROM mtf_cartridges WHERE media_family_id = ? ORDER BY sequence
`

func (q *Queries) ListCartridgesByFamily(ctx context.Context, mediaFamilyID int64) ([]MtfCartridge, error) {
	rows, err := q.db.QueryContext(ctx, listCartridgesByFamily, mediaFamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MtfCartridge{}
	for rows.Next() {
		var i MtfCartridge
		if err := rows.Scan(
			&i.Barcode,
			&i.Label,
			&i.MediaFamilyID,
			&i.Sequence,
			&i.Role,
			&i.CatalogType,
			&i.IsBkfFile,
			&i.SourcePath,
			&i.Volumes,
			&i.Directories,
			&i.Files,
			&i.EmptyFiles,
			&i.FileBytes,
			&i.SparseFiles,
			&i.CompressedFiles,
			&i.EncryptedFiles,
			&i.HasCatalog,
			&i.CatalogBytes,
			&i.SetsClosed,
			&i.Status,
			&i.LastScanned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryRuns = `-- name: ListInventoryRuns :many
SELECT id, changer, started_at, completed_at, status, cartridges, message FROM mtf_inventory_runs ORDER BY started_at DESC LIMIT ?
`

func (q *Queries) ListInventoryRuns(ctx context.Context, limit int64) ([]MtfInventoryRun, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MtfInventoryRun{}
	for rows.Next() {
		var i MtfInventoryRun
		if err := rows.Scan(
			&i.ID,
			&i.Changer,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.Cartridges,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCartridge = `-- name: UpsertCartridge :exec
INSERT INTO mtf_cartridges (
    barcode, label, media_family_id, sequence, role, catalog_type,
    is_bkf_file, source_path,
    volumes, directories, files, empty_files, file_bytes,
    sparse_files, compressed_files, encrypted_files,
    has_catalog, catalog_bytes, sets_closed,
    status, last_scanned
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
ON CONFLICT(barcode) DO UPDATE SET
    label = excluded.label,
    media_family_id = excluded.media_family_id,
    sequence = excluded.sequence,
    role = excluded.role,
    catalog_type = excluded.catalog_type,
    is_bkf_file = excluded.is_bkf_file,
    source_path = excluded.source_path,
    volumes = excluded.volumes,
    directories = excluded.directories,
    files = excluded.files,
    empty_files = excluded.empty_files,
    file_bytes = excluded.file_bytes,
    sparse_files = excluded.sparse_files,
    compressed_files = excluded.compressed_files,
    encrypted_files = excluded.encrypted_files,
    has_catalog = excluded.has_catalog,
    catalog_bytes = excluded.catalog_bytes,
    sets_closed = excluded.sets_closed,
    status = excluded.status,
    last_scanned = excluded.last_scanned
`

type UpsertCartridgeParams struct {
	Barcode         string         `json:"barcode"`
	Label           sql.NullString `json:"label"`
	MediaFamilyID   int64          `json:"media_family_id"`
	Sequence        sql.NullInt64  `json:"sequence"`
	Role            sql.NullString `json:"role"`
	CatalogType     sql.NullInt64  `json:"catalog_type"`
	IsBkfFile       sql.NullInt64  `json:"is_bkf_file"`
	SourcePath      sql.NullString `json:"source_path"`
	Volumes         sql.NullInt64  `json:"volumes"`
	Directories     sql.NullInt64  `json:"directories"`
	Files           sql.NullInt64  `json:"files"`
	EmptyFiles      sql.NullInt64  `json:"empty_files"`
	FileBytes       sql.NullInt64  `json:"file_bytes"`
	SparseFiles     sql.NullInt64  `json:"sparse_files"`
	CompressedFiles sql.NullInt64  `json:"compressed_files"`
	EncryptedFiles  sql.NullInt64  `json:"encrypted_files"`
	HasCatalog      sql.NullInt64  `json:"has_catalog"`
	CatalogBytes    sql.NullInt64  `json:"catalog_bytes"`
	SetsClosed      sql.NullInt64  `json:"sets_closed"`
	Status          sql.NullString `json:"status"`
	LastScanned     sql.NullInt64  `json:"last_scanned"`
}

func (q *Queries) UpsertCartridge(ctx context.Context, arg UpsertCartridgeParams) error {
	_, err := q.db.ExecContext(ctx, upsertCartridge,
		arg.Barcode,
		arg.Label,
		arg.MediaFamilyID,
		arg.Sequence,
		arg.Role,
		arg.CatalogType,
		arg.IsBkfFile,
		arg.SourcePath,
		arg.Volumes,
		arg.Directories,
		arg.Files,
		arg.EmptyFiles,
		arg.FileBytes,
		arg.SparseFiles,
		arg.CompressedFiles,
		arg.EncryptedFiles,
		arg.HasCatalog,
		arg.CatalogBytes,
		arg.SetsClosed,
		arg.Status,
		arg.LastScanned,
	)
	return err
}
