// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mappings.sql

package mtfquery

import (
	"context"
	"database/sql"
)

const countMappings = `-- name: CountMappings :one
SELECT COUNT(*) FROM namespace_mappings
`

func (q *Queries) CountMappings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMappings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMapping = `-- name: CreateMapping :execlastid
INSERT INTO namespace_mappings (
    name, priority, match_regex, template, is_default, enabled, comment
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMappingParams struct {
	Name       sql.NullString `json:"name"`
	Priority   sql.NullInt64  `json:"priority"`
	MatchRegex sql.NullString `json:"match_regex"`
	Template   string         `json:"template"`
	IsDefault  sql.NullInt64  `json:"is_default"`
	Enabled    sql.NullInt64  `json:"enabled"`
	Comment    sql.NullString `json:"comment"`
}

func (q *Queries) CreateMapping(ctx context.Context, arg CreateMappingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMapping,
		arg.Name,
		arg.Priority,
		arg.MatchRegex,
		arg.Template,
		arg.IsDefault,
		arg.Enabled,
		arg.Comment,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteMapping = `-- name: DeleteMapping :execrows
DELETE FROM namespace_mappings WHERE id = ?
`

func (q *Queries) DeleteMapping(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMapping, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMapping = `-- name: GetMapping :one
SELECT id, name, priority, match_regex, template, is_default, enabled, comment, created_at FROM namespace_mappings WHERE id = ? LIMIT 1
`

func (q *Queries) GetMapping(ctx context.Context, id int64) (NamespaceMapping, error) {
	row := q.db.QueryRowContext(ctx, getMapping, id)
	var i NamespaceMapping
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.MatchRegex,
		&i.Template,
		&i.IsDefault,
		&i.Enabled,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledMappings = `-- name: ListEnabledMappings :many
SELECT id, name, priority, match_regex, template, is_default, enabled, comment, created_at FROM namespace_mappings WHERE enabled = 1 ORDER BY priority ASC, id ASC
`

func (q *Queries) ListEnabledMappings(ctx context.Context) ([]NamespaceMapping, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NamespaceMapping{}
	for rows.Next() {
		var i NamespaceMapping
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.MatchRegex,
			&i.Template,
			&i.IsDefault,
			&i.Enabled,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMappings = `-- name: ListMappings :many
SELECT id, name, priority, match_regex, template, is_default, enabled, comment, created_at FROM namespace_mappings ORDER BY priority ASC, id ASC
`

func (q *Queries) ListMappings(ctx context.Context) ([]NamespaceMapping, error) {
	rows, err := q.db.QueryContext(ctx, listMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NamespaceMapping{}
	for rows.Next() {
		var i NamespaceMapping
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.MatchRegex,
			&i.Template,
			&i.IsDefault,
			&i.Enabled,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mappingExists = `-- name: MappingExists :one
SELECT 1 FROM namespace_mappings WHERE id = ? LIMIT 1
`

func (q *Queries) MappingExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, mappingExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateMapping = `-- name: UpdateMapping :exec
UPDATE namespace_mappings
SET name = ?, priority = ?, match_regex = ?, template = ?,
    is_default = ?, enabled = ?, comment = ?
WHERE id = ?
`

type UpdateMappingParams struct {
	Name       sql.NullString `json:"name"`
	Priority   sql.NullInt64  `json:"priority"`
	MatchRegex sql.NullString `json:"match_regex"`
	Template   string         `json:"template"`
	IsDefault  sql.NullInt64  `json:"is_default"`
	Enabled    sql.NullInt64  `json:"enabled"`
	Comment    sql.NullString `json:"comment"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateMapping(ctx context.Context, arg UpdateMappingParams) error {
	_, err := q.db.ExecContext(ctx, updateMapping,
		arg.Name,
		arg.Priority,
		arg.MatchRegex,
		arg.Template,
		arg.IsDefault,
		arg.Enabled,
		arg.Comment,
		arg.ID,
	)
	return err
}
