// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mtf_jobs.sql

package mtfquery

import (
	"context"
	"database/sql"
)

const countMtfJobs = `-- name: CountMtfJobs :one
SELECT COUNT(*) FROM mtf_jobs
`

func (q *Queries) CountMtfJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMtfJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMtfJob = `-- name: CreateMtfJob :exec
INSERT INTO mtf_jobs (
    id, source_kind, source_ref, datastore, namespace, comment,
    notification_mode, spanning, overwrite_mappings, keep_loaded, changer, drive,
    current_pid, last_run_upid, last_successful_upid,
    last_run_status, retry_count,
    last_run_starttime, last_run_endtime, last_successful_endtime, duration
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?
)
`

type CreateMtfJobParams struct {
	ID                    string         `json:"id"`
	SourceKind            string         `json:"source_kind"`
	SourceRef             string         `json:"source_ref"`
	Datastore             string         `json:"datastore"`
	Namespace             sql.NullString `json:"namespace"`
	Comment               sql.NullString `json:"comment"`
	NotificationMode      sql.NullString `json:"notification_mode"`
	Spanning              sql.NullInt64  `json:"spanning"`
	OverwriteMappings     sql.NullInt64  `json:"overwrite_mappings"`
	KeepLoaded            int64          `json:"keep_loaded"`
	Changer               sql.NullString `json:"changer"`
	Drive                 sql.NullString `json:"drive"`
	CurrentPid            sql.NullString `json:"current_pid"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	Duration              sql.NullInt64  `json:"duration"`
}

func (q *Queries) CreateMtfJob(ctx context.Context, arg CreateMtfJobParams) error {
	_, err := q.db.ExecContext(ctx, createMtfJob,
		arg.ID,
		arg.SourceKind,
		arg.SourceRef,
		arg.Datastore,
		arg.Namespace,
		arg.Comment,
		arg.NotificationMode,
		arg.Spanning,
		arg.OverwriteMappings,
		arg.KeepLoaded,
		arg.Changer,
		arg.Drive,
		arg.CurrentPid,
		arg.LastRunUpid,
		arg.LastSuccessfulUpid,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.LastRunStarttime,
		arg.LastRunEndtime,
		arg.LastSuccessfulEndtime,
		arg.Duration,
	)
	return err
}

const deleteMtfJob = `-- name: DeleteMtfJob :execrows
DELETE FROM mtf_jobs WHERE id = ?
`

func (q *Queries) DeleteMtfJob(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMtfJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMtfJob = `-- name: GetMtfJob :one
SELECT id, source_kind, source_ref, datastore, namespace, comment, notification_mode, spanning, overwrite_mappings, changer, drive, current_pid, last_run_upid, last_successful_upid, last_run_status, retry_count, last_run_starttime, last_run_endtime, last_successful_endtime, duration, created_at, keep_loaded FROM mtf_jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetMtfJob(ctx context.Context, id string) (MtfJob, error) {
	row := q.db.QueryRowContext(ctx, getMtfJob, id)
	var i MtfJob
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.SourceRef,
		&i.Datastore,
		&i.Namespace,
		&i.Comment,
		&i.NotificationMode,
		&i.Spanning,
		&i.OverwriteMappings,
		&i.Changer,
		&i.Drive,
		&i.CurrentPid,
		&i.LastRunUpid,
		&i.LastSuccessfulUpid,
		&i.LastRunStatus,
		&i.RetryCount,
		&i.LastRunStarttime,
		&i.LastRunEndtime,
		&i.LastSuccessfulEndtime,
		&i.Duration,
		&i.CreatedAt,
		&i.KeepLoaded,
	)
	return i, err
}

const listAllMtfJobs = `-- name: ListAllMtfJobs :many
SELECT id, source_kind, source_ref, datastore, namespace, comment, notification_mode, spanning, overwrite_mappings, changer, drive, current_pid, last_run_upid, last_successful_upid, last_run_status, retry_count, last_run_starttime, last_run_endtime, last_successful_endtime, duration, created_at, keep_loaded FROM mtf_jobs ORDER BY id
`

func (q *Queries) ListAllMtfJobs(ctx context.Context) ([]MtfJob, error) {
	rows, err := q.db.QueryContext(ctx, listAllMtfJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MtfJob{}
	for rows.Next() {
		var i MtfJob
		if err := rows.Scan(
			&i.ID,
			&i.SourceKind,
			&i.SourceRef,
			&i.Datastore,
			&i.Namespace,
			&i.Comment,
			&i.NotificationMode,
			&i.Spanning,
			&i.OverwriteMappings,
			&i.Changer,
			&i.Drive,
			&i.CurrentPid,
			&i.LastRunUpid,
			&i.LastSuccessfulUpid,
			&i.LastRunStatus,
			&i.RetryCount,
			&i.LastRunStarttime,
			&i.LastRunEndtime,
			&i.LastSuccessfulEndtime,
			&i.Duration,
			&i.CreatedAt,
			&i.KeepLoaded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedMtfJobs = `-- name: ListQueuedMtfJobs :many
SELECT id, source_kind, source_ref, datastore, namespace, comment, notification_mode, spanning, overwrite_mappings, changer, drive, current_pid, last_run_upid, last_successful_upid, last_run_status, retry_count, last_run_starttime, last_run_endtime, last_successful_endtime, duration, created_at, keep_loaded FROM mtf_jobs WHERE last_run_upid LIKE '%pbsplusgen-queue%' ORDER BY id
`

func (q *Queries) ListQueuedMtfJobs(ctx context.Context) ([]MtfJob, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedMtfJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MtfJob{}
	for rows.Next() {
		var i MtfJob
		if err := rows.Scan(
			&i.ID,
			&i.SourceKind,
			&i.SourceRef,
			&i.Datastore,
			&i.Namespace,
			&i.Comment,
			&i.NotificationMode,
			&i.Spanning,
			&i.OverwriteMappings,
			&i.Changer,
			&i.Drive,
			&i.CurrentPid,
			&i.LastRunUpid,
			&i.LastSuccessfulUpid,
			&i.LastRunStatus,
			&i.RetryCount,
			&i.LastRunStarttime,
			&i.LastRunEndtime,
			&i.LastSuccessfulEndtime,
			&i.Duration,
			&i.CreatedAt,
			&i.KeepLoaded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mtfJobExists = `-- name: MtfJobExists :one
SELECT 1 FROM mtf_jobs WHERE id = ? LIMIT 1
`

func (q *Queries) MtfJobExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, mtfJobExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateMtfJob = `-- name: UpdateMtfJob :exec
UPDATE mtf_jobs
SET source_kind = ?, source_ref = ?, datastore = ?, namespace = ?,
    comment = ?, notification_mode = ?, spanning = ?,
    overwrite_mappings = ?, keep_loaded = ?, changer = ?, drive = ?,
    last_run_upid = ?, last_successful_upid = ?,
    last_run_status = ?, retry_count = ?,
    last_run_starttime = ?, last_run_endtime = ?,
    last_successful_endtime = ?, duration = ?
WHERE id = ?
`

type UpdateMtfJobParams struct {
	SourceKind            string         `json:"source_kind"`
	SourceRef             string         `json:"source_ref"`
	Datastore             string         `json:"datastore"`
	Namespace             sql.NullString `json:"namespace"`
	Comment               sql.NullString `json:"comment"`
	NotificationMode      sql.NullString `json:"notification_mode"`
	Spanning              sql.NullInt64  `json:"spanning"`
	OverwriteMappings     sql.NullInt64  `json:"overwrite_mappings"`
	KeepLoaded            int64          `json:"keep_loaded"`
	Changer               sql.NullString `json:"changer"`
	Drive                 sql.NullString `json:"drive"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	Duration              sql.NullInt64  `json:"duration"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateMtfJob(ctx context.Context, arg UpdateMtfJobParams) error {
	_, err := q.db.ExecContext(ctx, updateMtfJob,
		arg.SourceKind,
		arg.SourceRef,
		arg.Datastore,
		arg.Namespace,
		arg.Comment,
		arg.NotificationMode,
		arg.Spanning,
		arg.OverwriteMappings,
		arg.KeepLoaded,
		arg.Changer,
		arg.Drive,
		arg.LastRunUpid,
		arg.LastSuccessfulUpid,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.LastRunStarttime,
		arg.LastRunEndtime,
		arg.LastSuccessfulEndtime,
		arg.Duration,
		arg.ID,
	)
	return err
}

const updateMtfJobHistory = `-- name: UpdateMtfJobHistory :exec
UPDATE mtf_jobs
SET current_pid = ?, last_run_upid = ?, last_successful_upid = ?,
    last_run_status = ?, retry_count = ?,
    last_run_starttime = ?, last_run_endtime = ?,
    last_successful_endtime = ?, duration = ?
WHERE id = ?
`

type UpdateMtfJobHistoryParams struct {
	CurrentPid            sql.NullString `json:"current_pid"`
	LastRunUpid           sql.NullString `json:"last_run_upid"`
	LastSuccessfulUpid    sql.NullString `json:"last_successful_upid"`
	LastRunStatus         sql.NullInt64  `json:"last_run_status"`
	RetryCount            sql.NullInt64  `json:"retry_count"`
	LastRunStarttime      sql.NullInt64  `json:"last_run_starttime"`
	LastRunEndtime        sql.NullInt64  `json:"last_run_endtime"`
	LastSuccessfulEndtime sql.NullInt64  `json:"last_successful_endtime"`
	Duration              sql.NullInt64  `json:"duration"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateMtfJobHistory(ctx context.Context, arg UpdateMtfJobHistoryParams) error {
	_, err := q.db.ExecContext(ctx, updateMtfJobHistory,
		arg.CurrentPid,
		arg.LastRunUpid,
		arg.LastSuccessfulUpid,
		arg.LastRunStatus,
		arg.RetryCount,
		arg.LastRunStarttime,
		arg.LastRunEndtime,
		arg.LastSuccessfulEndtime,
		arg.Duration,
		arg.ID,
	)
	return err
}
