// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mtfquery

import (
	"context"
)

type Querier interface {
	CartridgeExists(ctx context.Context, barcode string) (int64, error)
	CompleteInventoryRun(ctx context.Context, arg CompleteInventoryRunParams) error
	CountMappings(ctx context.Context) (int64, error)
	CountMtfJobs(ctx context.Context) (int64, error)
	CreateDataSet(ctx context.Context, arg CreateDataSetParams) (int64, error)
	CreateDataSetTape(ctx context.Context, arg CreateDataSetTapeParams) error
	CreateDataSetVolume(ctx context.Context, arg CreateDataSetVolumeParams) error
	CreateInventoryRun(ctx context.Context, arg CreateInventoryRunParams) (int64, error)
	CreateMapping(ctx context.Context, arg CreateMappingParams) (int64, error)
	CreateMtfJob(ctx context.Context, arg CreateMtfJobParams) error
	DeleteCartridge(ctx context.Context, barcode string) (int64, error)
	DeleteDataSetTapes(ctx context.Context, dataSetID int64) (int64, error)
	DeleteDataSetsByFamily(ctx context.Context, mediaFamilyID int64) (int64, error)
	DeleteMapping(ctx context.Context, id int64) (int64, error)
	DeleteMediaFamily(ctx context.Context, id int64) (int64, error)
	DeleteMtfJob(ctx context.Context, id string) (int64, error)
	DeleteVolumesByDataSet(ctx context.Context, dataSetID int64) (int64, error)
	FindDataSet(ctx context.Context, arg FindDataSetParams) (DataSet, error)
	GetCartridge(ctx context.Context, barcode string) (MtfCartridge, error)
	GetDataSet(ctx context.Context, id int64) (DataSet, error)
	GetDataSetTape(ctx context.Context, arg GetDataSetTapeParams) (DataSetTape, error)
	GetInventoryRun(ctx context.Context, id int64) (MtfInventoryRun, error)
	GetMapping(ctx context.Context, id int64) (NamespaceMapping, error)
	GetMediaFamily(ctx context.Context, id int64) (MediaFamily, error)
	GetMtfJob(ctx context.Context, id string) (MtfJob, error)
	ListAllDataSets(ctx context.Context) ([]DataSet, error)
	ListAllMtfJobs(ctx context.Context) ([]MtfJob, error)
	ListCartridges(ctx context.Context) ([]MtfCartridge, error)
	ListCartridgesByFamily(ctx context.Context, mediaFamilyID int64) ([]MtfCartridge, error)
	ListDataSetTapes(ctx context.Context, dataSetID int64) ([]DataSetTape, error)
	ListDataSetsByFamily(ctx context.Context, mediaFamilyID int64) ([]DataSet, error)
	ListEnabledMappings(ctx context.Context) ([]NamespaceMapping, error)
	ListInventoryRuns(ctx context.Context, limit int64) ([]MtfInventoryRun, error)
	ListMappings(ctx context.Context) ([]NamespaceMapping, error)
	ListMediaFamilies(ctx context.Context) ([]MediaFamily, error)
	ListQueuedMtfJobs(ctx context.Context) ([]MtfJob, error)
	ListVolumesByDataSet(ctx context.Context, dataSetID int64) ([]DataSetVolume, error)
	MappingExists(ctx context.Context, id int64) (int64, error)
	MtfJobExists(ctx context.Context, id string) (int64, error)
	UpdateDataSetSsetPba(ctx context.Context, arg UpdateDataSetSsetPbaParams) (int64, error)
	UpdateMapping(ctx context.Context, arg UpdateMappingParams) error
	UpdateMediaFamilyScan(ctx context.Context, arg UpdateMediaFamilyScanParams) error
	UpdateMtfJob(ctx context.Context, arg UpdateMtfJobParams) error
	UpdateMtfJobHistory(ctx context.Context, arg UpdateMtfJobHistoryParams) error
	UpsertCartridge(ctx context.Context, arg UpsertCartridgeParams) error
	UpsertDataSet(ctx context.Context, arg UpsertDataSetParams) (int64, error)
	UpsertMediaFamily(ctx context.Context, arg UpsertMediaFamilyParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
