//go:build linux

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/pbs-plus/pbs-plus/internal/conf"
	"github.com/pbs-plus/pbs-plus/internal/log"
	"github.com/pbs-plus/pbs-plus/internal/proxmox"
)

type Token struct {
	CSRFToken string `json:"CSRFPreventionToken"`
	Ticket    string `json:"ticket"`
	Username  string `json:"username"`
}

type TokenResponse struct {
	Data Token `json:"data"`
}

type TokenRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type APITokenRequest struct {
	Comment string `json:"comment"`
}

type APITokenResponse struct {
	Data APIToken `json:"data"`
}

type ACLRequest struct {
	Path   string `json:"path"`
	Role   string `json:"role"`
	AuthId string `json:"auth-id"`
}

type APIToken struct {
	TokenId string `json:"tokenid"`
	Value   string `json:"value"`
}

func runCommandAndIgnoreExists(cmd *exec.Cmd, alreadyExistsKeywords []string) error {
	cmd.Env = os.Environ()
	outputBytes, err := cmd.CombinedOutput()
	outputStr := string(outputBytes)

	if err != nil {
		isAlreadyExistsError := false
		if len(alreadyExistsKeywords) > 0 {
			for _, keyword := range alreadyExistsKeywords {
				if strings.Contains(outputStr, keyword) {
					isAlreadyExistsError = true
					log.Info("Resource already exists (ignored error): " + cmd.String() + " - Output: " + outputStr)
					break
				}
			}
		}

		if !isAlreadyExistsError {
			log.Error(err, "Command failed: "+cmd.String()+" - Output: "+outputStr)
			return err
		}
	}
	return nil
}

func extractJsonFromResult(output string) string {
	startIndex := strings.Index(output, "{")
	if startIndex == -1 {
		return ""
	}

	endIndex := strings.LastIndex(output, "}")
	if endIndex == -1 || endIndex < startIndex {
		return ""
	}
	return output[startIndex : endIndex+1]
}

func GetToken() string {
	token, err := getAPITokenFromFile()
	if err != nil {
		token, err = createAPIToken()
		if err == nil {
			if err := token.saveToFile(); err != nil {
				log.Error(err, "")
			}
		}
	}

	if token != nil {
		return token.Value
	}

	return ""
}

func createAPIToken() (*APIToken, error) {
	var cmdErr error
	var finalToken *APIToken

	cmdUserCreate := exec.Command(
		"proxmox-backup-manager",
		"user",
		"create",
		proxmox.AuthUser,
		"--comment",
		"Autogenerated user for PBS Plus",
		"--firstname",
		"PBS",
		"--lastname",
		"Plus",
	)
	if err := runCommandAndIgnoreExists(cmdUserCreate, []string{"user '" + proxmox.AuthUser + "' already exists"}); err != nil {
		return nil, err
	}

	cmdAclUser := exec.Command(
		"proxmox-backup-manager",
		"acl",
		"update",
		"/",
		"Admin",
		"--auth-id",
		proxmox.AuthUser,
		"--propagate",
		"true",
	)
	if err := runCommandAndIgnoreExists(cmdAclUser, []string{"entry '" + proxmox.AuthUser + "' already exists"}); err != nil {
		return nil, err
	}

	generateTokenCmd := func() *exec.Cmd {
		return exec.Command(
			"proxmox-backup-manager",
			"user",
			"generate-token",
			proxmox.AuthUser,
			proxmox.AuthToken,
			"--comment",
			"Autogenerated API Token for PBS Plus",
		)
	}

	processTokenGeneration := func(rawOutput string) (*APIToken, error) {
		jsonStr := extractJsonFromResult(rawOutput)
		if jsonStr == "" {
			err := fmt.Errorf("could not extract JSON from token generation output")
			log.Error(err, "Output was: "+rawOutput)
			return nil, err
		}

		var details APIToken
		if err := json.Unmarshal([]byte(jsonStr), &details); err != nil {
			log.Error(err, "Failed to parse token JSON: "+jsonStr)
			return nil, fmt.Errorf("failed to parse token JSON: %w", err)
		}
		if details.Value == "" {
			err := fmt.Errorf("token value is empty after parsing JSON")
			log.Error(err, "Parsed JSON: "+jsonStr)
			return nil, err
		}
		return &details, nil
	}

	cmd := generateTokenCmd()
	cmd.Env = os.Environ()
	outputBytes, cmdErr := cmd.CombinedOutput()
	rawOutputStr := string(outputBytes)

	if cmdErr != nil {
		alreadyExistsTokenMsg := "token '" + proxmox.AuthToken + "' for user '" + proxmox.AuthUser + "' already exists"
		if strings.Contains(rawOutputStr, alreadyExistsTokenMsg) {
			log.Info("Token " + proxmox.AuthID + " already exists. Attempting to delete and regenerate.")

			cmdTokenDelete := exec.Command(
				"proxmox-backup-manager",
				"user",
				"delete-token",
				proxmox.AuthUser,
				proxmox.AuthToken,
			)
			cmdTokenDelete.Env = os.Environ()
			deleteOutputBytes, deleteErr := cmdTokenDelete.CombinedOutput()
			deleteOutputStr := string(deleteOutputBytes)

			if deleteErr != nil {
				log.Error(deleteErr, "Failed to delete existing token '"+proxmox.AuthID+"'. Output: "+deleteOutputStr)
			} else {
				log.Info("Successfully deleted existing token: " + proxmox.AuthID + ". Output: " + deleteOutputStr)
			}
			log.Info("Retrying token generation for: " + proxmox.AuthID)
			cmdRetry := generateTokenCmd()
			cmdRetry.Env = os.Environ()
			outputBytesRetry, cmdErrRetry := cmdRetry.CombinedOutput()
			rawOutputStrRetry := string(outputBytesRetry)

			if cmdErrRetry != nil {
				log.Error(cmdErrRetry, "Failed to generate token on retry for '"+proxmox.AuthID+"'. Output: "+rawOutputStrRetry)
				return nil, cmdErrRetry
			}
			log.Info("Successfully generated token on retry for " + proxmox.AuthID + ".")
			var parseErr error
			finalToken, parseErr = processTokenGeneration(rawOutputStrRetry)
			if parseErr != nil {
				return nil, parseErr
			}
		} else {
			log.Error(cmdErr, "Failed to generate token '"+proxmox.AuthID+"'. Output: "+rawOutputStr)
			return nil, cmdErr
		}
	} else {
		log.Info("Successfully generated token on first try for " + proxmox.AuthID + ".")
		var parseErr error
		finalToken, parseErr = processTokenGeneration(rawOutputStr)
		if parseErr != nil {
			return nil, parseErr
		}
	}

	cmdAclToken := exec.Command(
		"proxmox-backup-manager",
		"acl",
		"update",
		"/",
		"Admin",
		"--auth-id",
		proxmox.AuthID,
		"--propagate",
		"true",
	)
	if err := runCommandAndIgnoreExists(cmdAclToken, []string{"entry '" + proxmox.AuthID + "' already exists"}); err != nil {
		return nil, err
	}
	log.Info("User token creation process completed successfully.")
	return finalToken, nil
}

func (token *APIToken) saveToFile() error {
	if token == nil {
		return nil
	}

	if err := os.MkdirAll(conf.DbBasePath, os.FileMode(0755)); err != nil {
		return err
	}

	tokenFileContent, err := json.Marshal(token)
	if err != nil {
		return err
	}
	file, err := os.OpenFile(filepath.Join(conf.DbBasePath, "pbs-plus-token.json"), os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0644)
	if err != nil {
		return err
	}
	defer func() {
		if err := file.Close(); err != nil {
			log.Error(err, "")
		}
	}()

	_, err = file.WriteString(string(tokenFileContent))
	if err != nil {
		return err
	}

	return nil
}

func getAPITokenFromFile() (*APIToken, error) {
	jsonFile, err := os.Open(filepath.Join(conf.DbBasePath, "pbs-plus-token.json"))
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := jsonFile.Close(); err != nil {
			log.Error(err, "")
		}
	}()

	byteValue, err := io.ReadAll(jsonFile)
	if err != nil {
		return nil, err
	}

	var result APIToken
	err = json.Unmarshal([]byte(byteValue), &result)
	if err != nil {
		return nil, err
	}

	return &result, nil
}
