// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package objectstorequery

type Object struct {
	Bucket       string `json:"bucket"`
	Key          string `json:"key"`
	Datastore    string `json:"datastore"`
	Namespace    string `json:"namespace"`
	BackupType   string `json:"backup_type"`
	BackupID     string `json:"backup_id"`
	SnapshotTime int64  `json:"snapshot_time"`
	Size         int64  `json:"size"`
	Etag         string `json:"etag"`
	ContentType  string `json:"content_type"`
	UserMetadata string `json:"user_metadata"`
}
