// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: objects.sql

package objectstorequery

import (
	"context"
)

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM objects WHERE bucket = ? AND key = ?
`

type DeleteObjectParams struct {
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteObject(ctx context.Context, arg DeleteObjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteObject, arg.Bucket, arg.Key)
	return err
}

const getObject = `-- name: GetObject :one
SELECT bucket, key, datastore, namespace, backup_type, backup_id,
    snapshot_time, size, etag, content_type, user_metadata
FROM objects
WHERE bucket = ? AND key = ?
`

type GetObjectParams struct {
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
}

func (q *Queries) GetObject(ctx context.Context, arg GetObjectParams) (Object, error) {
	row := q.db.QueryRowContext(ctx, getObject, arg.Bucket, arg.Key)
	var i Object
	err := row.Scan(
		&i.Bucket,
		&i.Key,
		&i.Datastore,
		&i.Namespace,
		&i.BackupType,
		&i.BackupID,
		&i.SnapshotTime,
		&i.Size,
		&i.Etag,
		&i.ContentType,
		&i.UserMetadata,
	)
	return i, err
}

const listObjectKeysByBucket = `-- name: ListObjectKeysByBucket :many
SELECT key FROM objects WHERE bucket = ?
`

func (q *Queries) ListObjectKeysByBucket(ctx context.Context, bucket string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listObjectKeysByBucket, bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertObject = `-- name: UpsertObject :exec
INSERT INTO objects (
    bucket, key, datastore, namespace, backup_type, backup_id,
    snapshot_time, size, etag, content_type, user_metadata
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(bucket, key) DO UPDATE SET
    datastore = excluded.datastore,
    namespace = excluded.namespace,
    backup_type = excluded.backup_type,
    backup_id = excluded.backup_id,
    snapshot_time = excluded.snapshot_time,
    size = excluded.size,
    etag = excluded.etag,
    content_type = excluded.content_type,
    user_metadata = excluded.user_metadata
`

type UpsertObjectParams struct {
	Bucket       string `json:"bucket"`
	Key          string `json:"key"`
	Datastore    string `json:"datastore"`
	Namespace    string `json:"namespace"`
	BackupType   string `json:"backup_type"`
	BackupID     string `json:"backup_id"`
	SnapshotTime int64  `json:"snapshot_time"`
	Size         int64  `json:"size"`
	Etag         string `json:"etag"`
	ContentType  string `json:"content_type"`
	UserMetadata string `json:"user_metadata"`
}

func (q *Queries) UpsertObject(ctx context.Context, arg UpsertObjectParams) error {
	_, err := q.db.ExecContext(ctx, upsertObject,
		arg.Bucket,
		arg.Key,
		arg.Datastore,
		arg.Namespace,
		arg.BackupType,
		arg.BackupID,
		arg.SnapshotTime,
		arg.Size,
		arg.Etag,
		arg.ContentType,
		arg.UserMetadata,
	)
	return err
}
