// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package objectstorequery

import (
	"context"
)

type Querier interface {
	DeleteObject(ctx context.Context, arg DeleteObjectParams) error
	GetObject(ctx context.Context, arg GetObjectParams) (Object, error)
	ListObjectKeysByBucket(ctx context.Context, bucket string) ([]string, error)
	UpsertObject(ctx context.Context, arg UpsertObjectParams) error
}

var _ Querier = (*Queries)(nil)
