name: Setup Test Environment
description: Install dependencies and setup Go

inputs:
  go-version:
    required: true
    description: Go version to install

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: Set up Rust
      uses: moonrepo/setup-rust@v1

    - name: Download dependencies
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y fuse3 libfuse3-dev uuid-dev libsystemd-dev libacl1-dev pkg-config build-essential
        go mod download
