// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exclusions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createExclusion = `-- name: CreateExclusion :exec
INSERT INTO exclusions (job_id, path, comment) 
VALUES (?, ?, ?)
`

type CreateExclusionParams struct {
	JobID   string         `json:"job_id"`
	Path    string         `json:"path"`
	Comment sql.NullString `json:"comment"`
}

func (q *Queries) CreateExclusion(ctx context.Context, arg CreateExclusionParams) error {
	_, err := q.db.ExecContext(ctx, createExclusion, arg.JobID, arg.Path, arg.Comment)
	return err
}

const deleteBackupExclusions = `-- name: DeleteBackupExclusions :exec
DELETE FROM exclusions WHERE job_id = ?
`

func (q *Queries) DeleteBackupExclusions(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupExclusions, jobID)
	return err
}

const deleteExclusion = `-- name: DeleteExclusion :exec
DELETE FROM exclusions 
WHERE job_id = ? AND path = ?
`

type DeleteExclusionParams struct {
	JobID string `json:"job_id"`
	Path  string `json:"path"`
}

func (q *Queries) DeleteExclusion(ctx context.Context, arg DeleteExclusionParams) error {
	_, err := q.db.ExecContext(ctx, deleteExclusion, arg.JobID, arg.Path)
	return err
}

const getBackupExclusions = `-- name: GetBackupExclusions :many
SELECT job_id, path, comment
FROM exclusions
WHERE job_id = ?
ORDER BY path
`

type GetBackupExclusionsRow struct {
	JobID   string         `json:"job_id"`
	Path    string         `json:"path"`
	Comment sql.NullString `json:"comment"`
}

func (q *Queries) GetBackupExclusions(ctx context.Context, jobID string) ([]GetBackupExclusionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBackupExclusions, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBackupExclusionsRow{}
	for rows.Next() {
		var i GetBackupExclusionsRow
		if err := rows.Scan(&i.JobID, &i.Path, &i.Comment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExclusion = `-- name: GetExclusion :one
SELECT job_id, path, comment 
FROM exclusions 
WHERE job_id = ? AND path = ?
LIMIT 1
`

type GetExclusionParams struct {
	JobID string `json:"job_id"`
	Path  string `json:"path"`
}

type GetExclusionRow struct {
	JobID   string         `json:"job_id"`
	Path    string         `json:"path"`
	Comment sql.NullString `json:"comment"`
}

func (q *Queries) GetExclusion(ctx context.Context, arg GetExclusionParams) (GetExclusionRow, error) {
	row := q.db.QueryRowContext(ctx, getExclusion, arg.JobID, arg.Path)
	var i GetExclusionRow
	err := row.Scan(&i.JobID, &i.Path, &i.Comment)
	return i, err
}

const listAllBackupExclusions = `-- name: ListAllBackupExclusions :many
SELECT job_id, path
FROM exclusions
ORDER BY job_id, path
`

type ListAllBackupExclusionsRow struct {
	JobID string `json:"job_id"`
	Path  string `json:"path"`
}

func (q *Queries) ListAllBackupExclusions(ctx context.Context) ([]ListAllBackupExclusionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllBackupExclusions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBackupExclusionsRow{}
	for rows.Next() {
		var i ListAllBackupExclusionsRow
		if err := rows.Scan(&i.JobID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalExclusions = `-- name: ListGlobalExclusions :many
SELECT path, comment 
FROM exclusions 
WHERE job_id = ''
`

type ListGlobalExclusionsRow struct {
	Path    string         `json:"path"`
	Comment sql.NullString `json:"comment"`
}

func (q *Queries) ListGlobalExclusions(ctx context.Context) ([]ListGlobalExclusionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalExclusions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlobalExclusionsRow{}
	for rows.Next() {
		var i ListGlobalExclusionsRow
		if err := rows.Scan(&i.Path, &i.Comment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExclusion = `-- name: UpdateExclusion :execrows
UPDATE exclusions 
SET job_id = ?, comment = ? 
WHERE path = ?
`

type UpdateExclusionParams struct {
	JobID   string         `json:"job_id"`
	Comment sql.NullString `json:"comment"`
	Path    string         `json:"path"`
}

func (q *Queries) UpdateExclusion(ctx context.Context, arg UpdateExclusionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateExclusion, arg.JobID, arg.Comment, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
