// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AgentHostExists(ctx context.Context, name string) (int64, error)
	BackupExists(ctx context.Context, id string) (int64, error)
	CreateAgentHost(ctx context.Context, arg CreateAgentHostParams) error
	CreateBackup(ctx context.Context, arg CreateBackupParams) error
	CreateExclusion(ctx context.Context, arg CreateExclusionParams) error
	CreateRestore(ctx context.Context, arg CreateRestoreParams) error
	CreateScript(ctx context.Context, arg CreateScriptParams) error
	CreateTarget(ctx context.Context, arg CreateTargetParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	DeleteAgentHost(ctx context.Context, name string) (int64, error)
	DeleteBackup(ctx context.Context, id string) (int64, error)
	DeleteBackupExclusions(ctx context.Context, jobID string) error
	DeleteExclusion(ctx context.Context, arg DeleteExclusionParams) error
	DeleteRestore(ctx context.Context, id string) (int64, error)
	DeleteScript(ctx context.Context, path string) (int64, error)
	DeleteTarget(ctx context.Context, name string) (int64, error)
	DeleteToken(ctx context.Context, token string) error
	GetAgentHost(ctx context.Context, name string) (AgentHost, error)
	GetAgentHostAuth(ctx context.Context, name string) (sql.NullString, error)
	GetBackup(ctx context.Context, id string) (GetBackupRow, error)
	GetBackupExclusions(ctx context.Context, jobID string) ([]GetBackupExclusionsRow, error)
	GetExclusion(ctx context.Context, arg GetExclusionParams) (GetExclusionRow, error)
	GetRestore(ctx context.Context, id string) (GetRestoreRow, error)
	GetScript(ctx context.Context, path string) (GetScriptRow, error)
	GetTarget(ctx context.Context, name string) (GetTargetRow, error)
	GetTargetS3Secret(ctx context.Context, name string) (string, error)
	GetToken(ctx context.Context, token string) (Token, error)
	ListAllAgentHosts(ctx context.Context) ([]AgentHost, error)
	ListAllBackupExclusions(ctx context.Context) ([]ListAllBackupExclusionsRow, error)
	ListAllBackups(ctx context.Context) ([]ListAllBackupsRow, error)
	ListAllRestores(ctx context.Context) ([]ListAllRestoresRow, error)
	ListAllScripts(ctx context.Context) ([]ListAllScriptsRow, error)
	ListAllTargets(ctx context.Context) ([]ListAllTargetsRow, error)
	ListAllTokens(ctx context.Context) ([]Token, error)
	ListAllTokensWithDetails(ctx context.Context) ([]ListAllTokensWithDetailsRow, error)
	ListGlobalExclusions(ctx context.Context) ([]ListGlobalExclusionsRow, error)
	ListNonRevokedTokens(ctx context.Context) ([]Token, error)
	ListQueuedBackups(ctx context.Context) ([]ListQueuedBackupsRow, error)
	ListQueuedRestores(ctx context.Context) ([]ListQueuedRestoresRow, error)
	ListTargetsByAgentHost(ctx context.Context, agentHost sql.NullString) ([]ListTargetsByAgentHostRow, error)
	RestoreExists(ctx context.Context, id string) (int64, error)
	RevokeToken(ctx context.Context, token string) error
	ScriptExists(ctx context.Context, path string) (int64, error)
	TargetExists(ctx context.Context, name string) (int64, error)
	UpdateAgentHost(ctx context.Context, arg UpdateAgentHostParams) error
	UpdateBackup(ctx context.Context, arg UpdateBackupParams) error
	UpdateExclusion(ctx context.Context, arg UpdateExclusionParams) (int64, error)
	UpdateRestore(ctx context.Context, arg UpdateRestoreParams) error
	UpdateScript(ctx context.Context, arg UpdateScriptParams) error
	UpdateTarget(ctx context.Context, arg UpdateTargetParams) error
	UpdateTargetS3Secret(ctx context.Context, arg UpdateTargetS3SecretParams) error
	UpsertTarget(ctx context.Context, arg UpsertTargetParams) error
}

var _ Querier = (*Queries)(nil)
