// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scripts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createScript = `-- name: CreateScript :exec
INSERT INTO scripts (path, description)
VALUES (?, ?)
`

type CreateScriptParams struct {
	Path        string         `json:"path"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateScript(ctx context.Context, arg CreateScriptParams) error {
	_, err := q.db.ExecContext(ctx, createScript, arg.Path, arg.Description)
	return err
}

const deleteScript = `-- name: DeleteScript :execrows
DELETE FROM scripts WHERE path = ?
`

func (q *Queries) DeleteScript(ctx context.Context, path string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScript, path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getScript = `-- name: GetScript :one
SELECT
    s.path, s.description,
    COUNT(DISTINCT CASE WHEN j.pre_script = s.path OR j.post_script = s.path THEN j.id END) as job_count,
    COUNT(DISTINCT CASE WHEN t.mount_script = s.path THEN t.name END) as target_count
FROM scripts s
LEFT JOIN backups j ON s.path = j.pre_script OR s.path = j.post_script
LEFT JOIN targets t ON s.path = t.mount_script
WHERE s.path = ?
GROUP BY s.path, s.description
`

type GetScriptRow struct {
	Path        string         `json:"path"`
	Description sql.NullString `json:"description"`
	JobCount    int64          `json:"job_count"`
	TargetCount int64          `json:"target_count"`
}

func (q *Queries) GetScript(ctx context.Context, path string) (GetScriptRow, error) {
	row := q.db.QueryRowContext(ctx, getScript, path)
	var i GetScriptRow
	err := row.Scan(
		&i.Path,
		&i.Description,
		&i.JobCount,
		&i.TargetCount,
	)
	return i, err
}

const listAllScripts = `-- name: ListAllScripts :many
SELECT
    s.path, s.description,
    COUNT(DISTINCT CASE WHEN j.pre_script = s.path OR j.post_script = s.path THEN j.id END) as job_count,
    COUNT(DISTINCT CASE WHEN t.mount_script = s.path THEN t.name END) as target_count
FROM scripts s
LEFT JOIN backups j ON s.path = j.pre_script OR s.path = j.post_script
LEFT JOIN targets t ON s.path = t.mount_script
GROUP BY s.path, s.description
ORDER BY s.path
`

type ListAllScriptsRow struct {
	Path        string         `json:"path"`
	Description sql.NullString `json:"description"`
	JobCount    int64          `json:"job_count"`
	TargetCount int64          `json:"target_count"`
}

func (q *Queries) ListAllScripts(ctx context.Context) ([]ListAllScriptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllScripts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllScriptsRow{}
	for rows.Next() {
		var i ListAllScriptsRow
		if err := rows.Scan(
			&i.Path,
			&i.Description,
			&i.JobCount,
			&i.TargetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scriptExists = `-- name: ScriptExists :one
SELECT 1 FROM scripts WHERE path = ? LIMIT 1
`

func (q *Queries) ScriptExists(ctx context.Context, path string) (int64, error) {
	row := q.db.QueryRowContext(ctx, scriptExists, path)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateScript = `-- name: UpdateScript :exec
UPDATE scripts 
SET description = ?
WHERE path = ?
`

type UpdateScriptParams struct {
	Description sql.NullString `json:"description"`
	Path        string         `json:"path"`
}

func (q *Queries) UpdateScript(ctx context.Context, arg UpdateScriptParams) error {
	_, err := q.db.ExecContext(ctx, updateScript, arg.Description, arg.Path)
	return err
}
